### ISSUE TITLE
How to enable the SSL in the Eureka Client Side?

### ISSUE THREAD

**Issue by ManteshJ** [SteeltoeOSS/steeltoe#10]
Hi,

I have gone through the EurekaClientConfig.cs code, there is no specific properties to set the certificate details like key-store, key-store-password, etc.
[EurekaClientConfig.cs Class](https://github.com/SteeltoeOSS/Discovery/blob/dev/src/Steeltoe.Discovery.EurekaBase/EurekaClientConfig.cs)
I want to know whether Steeltoe Discovery is supporting with SSL or not.

**Comment by diablo39** [comment]
Hello,
I've contributed to Eureka client and extended functionality of library by adding interface IEurekaDiscoveryClientHandlerProvider: https://github.com/SteeltoeOSS/steeltoe/blob/master/src/Discovery/src/EurekaBase/IEurekaDiscoveryClientHandlerProvider.cs

If you implement this interface and register in IoC container you should be able to add client certificate

**Comment by dtillman** [comment]
Thanks @diablo39 for that contribution.
We are also looking to add other ways to make this even easier in the future.
Dave

**Comment by TimHess** [comment]
#252 improves this experience by wiring up a [ClientCertificateHttpHandlerProvider](https://github.com/SteeltoeOSS/steeltoe/blob/master/src/Common/src/Common.Http/ClientCertificateHttpHandlerProvider.cs) when `CertificateOptions` are configured.

Usage of the new feature should look something like this in program.cs:
```
Host.CreateDefaultBuilder(args)
  .ConfigureAppConfiguration((ctx, config) =>
  {
       config.AddCertificateFile(<your PKCS#12/PFX path>);
       // or 
       config.AddPemCertificateFiles(<PEM Certificate Path>, <PEM RSA Key Path>);
       // or 
      config.Add(<YourCustomICertificateSourceHERE>)
  })
  .ConfigureServices((hostContext, services) =>
  {
       services.AddOptions();
       services.Configure<CertificateOptions>(configuration);

       services.AddSingleton<IConfigureOptions<CertificateOptions>, ConfigureCertificateOptions>();
       // or
       services.AddSingleton<IConfigureOptions<CertificateOptions>, PemConfigureCertificateOptions>();
       // or
       services.AddSingleton<IConfigureOptions<CertificateOptions>, {ConfigureYOURCertificateOptions}>();
  })
  .AddServiceDiscovery();
```
