### ISSUE TITLE
Discovery and IIS application pool recycle

### ISSUE THREAD

**Issue by kimbell** [SteeltoeOSS/steeltoe#102]
This is probably a bit on the side of the main functionality, but I'm interested in hearing if people have ideas or solutions to our problem. 

For various reasons, we are hosting ASP.NET Core behind IIS. We are also using the Discovery client to register the service in Eureka for use by Zuul. By default, IIS will recycle the application pool at regular intervals. This causes the service to get unregistered and registered again. This is when things start to get interesting. 

- Application pool recycle starts
- IIS starts a new process to handle new requests
- This process registers with Eureka
- The old process terminates
- The old process will unregister with Eureka

Since this happens on the same machine, the result is that the service is unregistered in Eureka until a heartbeat is triggered. Since we are using Zuul together with Eureka, it means that the service will not receive any traffic until it has been registered again. 

One thing we have done is disable recycling. We will have wait and see how this effects memory usage. One of the original reason for IIS recycling was to act as safety valve for bad code. 

We have also tried an approach of having Octopus deploy run a timed job that stops and starts the process. Then things get registered correctly. 

Open to other ideas.

**Comment by TimHess** [comment]
Hi @kimbell,

Are you still in need of a solution here? I just tried testing the out with the latest Steeltoe releases on local IIS and am not seeing this kind of failure -- the app appears appropriately to de-register and re-register during recycling

**Comment by kimbell** [comment]
Hi @TimHess 

I find it interesting that you don't see the same behavior with the latest release. I can't get my head around how that would actually works in IIS. Is there a delay after startup before register is sent, so that the terminating process is able to unregister first? Lucky in the sequence things happen? We use IHostedService infrastructure a lot, this may result in our services taking a longer time to shut down. 

As I said in the original post, this might be on the edge of what this component can handle. I don't know how to detect recycle events inside a .NET Core application. This might also differ depending on in-process and out-of-process hosting. We mainly use the latter for now. The quick fix for Steeltoe could just be to add a gotcha in the documentation that this is something that people may need to think about. IIS hosting should hopefully be a dying hosting model; considering it doesn't support newer things such as gRPC. 

For our case, the simple solution has been to disable automatic recycling. We are also considering other options as hosting in Windows Services and docker containers; these come with other pro/cons.

**Comment by TimHess** [comment]
@kimbell, 

I think I understand a little better now what you're seeing, and I think it's related to the way IIS starts apps, or rather doesn't start them until they receive traffic... Have you configured [Application Initialization](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization)?

I've been testing with [this sample](https://github.com/SteeltoeOSS/Samples/tree/2.x/Discovery/src/AspDotNetCore/Fortune-Teller-Service), targeting `netcoreapp2.1`, running out of process... I wasn't giving it enough time and/or exactly following the process you were describing, but I've now seen it fail. Adding this to the system.webserver section in the app's web.config seems effective in immediately warming up the process (thus triggering registration in Eureka) for me:
```
	    <applicationInitialization skipManagedModules="true">
		    <add initializationPage="/api/fortunes" />
	    </applicationInitialization>
```

**Comment by kimbell** [comment]
Hi,

We are running with the initialization module and 'always running' mode. Since we are running out-of-process, we have w3wp.exe and a separate executable running our code. We discovered that when there is no traffic, the external program gets terminated, but the w3wp is still running. We have added some self-ping code that should keep things alive all the time. If we moved over to in-process, things might change a bit. 

When I tested this, I configured recycling every minute. Then I refreshed the Eureka page showing all the registered services. I noticed that the service is unregistered for a period of time before showing up again. 

I'm fairly certain that the problem is related to how IIS starts and stops things. Since the old process is terminated after the new one starts, the shutdown event triggers the unregister call against Eureka. 
I imagine it would be hard to figure out if 'another process like me is running', and based on that not send the unregister call.

**Comment by TimHess** [comment]
Is it feasible to disable Overlapped Recycling?

**Comment by TimHess** [comment]
Assuming disabling overlapped recycling isn't viable, you could also try setting the instance id to include a random value... if you add the Placeholder and Random Value config providers, something like this should work as each process would have a different Id when registered with Eureka: `"instanceId": "${spring:application:name}-${random:int(1,5)}"`

**Comment by kimbell** [comment]
If recycling is enabled, I think it will always be overlapped. For our services we have disabled recycling to avoid this problem. 

The unique id sounds interesting. I'm working on a new service and will try it out on that.

**Comment by TimHess** [comment]
I wouldn't attempt to state definitively that this setting always works, but it _should_ bypass this problem, though it would introduce the potential for downtime while the old process shuts down and new process warms up
![image](https://user-images.githubusercontent.com/3947063/70180451-0c9da500-16ae-11ea-834c-b30ac29d187b.png)

**Comment by kimbell** [comment]
That also seems like an interesting option. We host our services on multiple servers, so we are able to handle some downtime. 

I've been poking around IIS for several years, and never noticed that setting.

**Comment by TimHess** [comment]
@kimbell is there anything else to do here, or are we fine to close this issue?

**Comment by kimbell** [comment]
I haven't had time to test this yet since I've been busy getting things out the door before Christmas. I mentioned these approaches to another guy at work, and he disabled overlapping recycle on one server of a non-critical application. I haven't heard anything, so I'm hoping that is a good sign. 

This can be closed for now. When I get around to look at this, I'll add a comment with the result.
