### ISSUE TITLE
DynamicSerilogLogger: unable to set initial minimum level

### ISSUE THREAD

**Issue by davgia** [SteeltoeOSS/Steeltoe#1022]
## Describe the bug

Currenly I am not able to set the desired minimum level for default and any other loggers. The configuration available in IConfiguration seems ignored or not used. I check the effective level through loggers actuator. As an additional note I'm still able to change the log level through the actuator.

### Scenario with implicit configuration

`.AddSteeltoe` extension method in `IHostBuilder`:

``` cs
public static IHostBuilder CreateHostBuilder(string[] args) => Host.CreateDefaultBuilder(args)
  .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
  .AddSteeltoe(loggerFactory: new LoggerFactory());
```

``` json
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Error",
      "Override": {
        "Microsoft": "Error",
        "Startup": "Error",
        "Steeltoe": "Debug",
        "System": "Error"
      }
    },
    "Using": ["Serilog.Sinks.Console"],
    "WriteTo": [
      {
        "Name": "Console"
      }
    ]
  }
}
```

The result is that I don't see any log whatsoever. This is coherent with the loggers actuator that reports all loggers effectiveLevel: OFF.

``` json
{
  "levels": [
    "OFF",
    "FATAL",
    "ERROR",
    "WARN",
    "INFO",
    "DEBUG",
    "TRACE"
  ],
  "loggers": {
      "Default": {
          "configuredLevel": "OFF",
          "effectiveLevel": "OFF"
      },
      "Microsoft": {
          "effectiveLevel": "OFF"
       },
      //all other loggers OFF
   }
}
```

### Scenario with explicit configuration

`.AddSteeltoe` and `ConfigureLogging` extension methods in `IHostBuilder`:

``` cs
public static IHostBuilder CreateHostBuilder(string[] args) => Host.CreateDefaultBuilder(args)
  .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
  .ConfigureLogging((builderContext, loggerBuilder) =>
  {
    var logConfig = new LoggerConfiguration().ReadFrom.Configuration(builderContext.Configuration);
    loggerBuilder.AddDynamicSerilog(logConfig);
   })
   .AddSteeltoe(loggerFactory: CreateAutoconfigLoggerFactory());
```

``` json
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Error",
      "Override": {
        "Microsoft": "Error",
        "Startup": "Error",
        "Steeltoe": "Debug",
        "System": "Error"
      }
    },
    "Using": ["Serilog.Sinks.Console"],
    "WriteTo": [
      {
        "Name": "Console"
      }
    ]
  }
}
```

The result is that I don't see any log whatsoever. This is coherent with the loggers actuator that reports all loggers effectiveLevel: VERBOSE.

``` json
{
  "levels": [
    "OFF",
    "FATAL",
    "ERROR",
    "WARN",
    "INFO",
    "DEBUG",
    "TRACE"
  ],
  "loggers": {
      "Default": {
          "configuredLevel": "VERBOSE",
          "effectiveLevel": "VERBOSE"
      },
      "Microsoft": {
          "effectiveLevel": "VERBOSE"
       },
      //all other loggers VERBOSE
   }
}
```

## Expected behavior

I should be able to define the log level for each logger through service configuration (potentially each one different from the other).

## Environment (please complete the following information):

 - Steeltoe Version: 3.2.1
 - Platform: Local / Kubernetes
 - OS: Windows / Linux
 - .NET Version: .NET 6
 - Any other library versions to note:
``` xml
<PackageReference Include="Serilog.AspNetCore" Version="6.0.1" />
<PackageReference Include="Serilog.Formatting.Elasticsearch" Version="8.4.1" />
<PackageReference Include="Serilog.Settings.Configuration" Version="3.4.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
<PackageReference Include="Serilog.Sinks.EventLog" Version="3.1.0" />
<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
<PackageReference Include="Serilog.Sinks.Http" Version="8.0.0" />
<PackageReference Include="Steeltoe.Bootstrap.Autoconfig" Version="3.2.1" />
<PackageReference Include="Steeltoe.Discovery.ClientCore" Version="3.2.1" />
<PackageReference Include="Steeltoe.Discovery.Eureka" Version="3.2.1" />
<PackageReference Include="Steeltoe.Discovery.Kubernetes" Version="3.2.1" />
<PackageReference Include="Steeltoe.Extensions.Configuration.ConfigServerCore" Version="3.2.1" />
<PackageReference Include="Steeltoe.Extensions.Configuration.KubernetesCore" Version="3.2.1" />
<PackageReference Include="Steeltoe.Extensions.Logging.DynamicSerilogBase" Version="3.2.1" />
<PackageReference Include="Steeltoe.Management.EndpointBase" Version="3.2.1" />
<PackageReference Include="Steeltoe.Management.EndpointCore" Version="3.2.1" />
<PackageReference Include="Steeltoe.Management.KubernetesCore" Version="3.2.1" />
<PackageReference Include="Steeltoe.Management.TracingCore" Version="3.2.1" />
<PackageReference Include="Serilog.AspNetCore" Version="6.0.1" />
<PackageReference Include="Serilog.Formatting.Elasticsearch" Version="8.4.1" />
<PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
```

**Comment by davgia** [comment]
@TimHess 
 Any update on this?

**Comment by TimHess** [comment]
@hananiel can you take a look here?

**Comment by hananiel** [comment]
@davgia When I use DynamicSerilogBase, I couldnt get it to pickup the serilog configuration. So I am not sure what is happening for you. Can you try to add a reference to DynamicSerilogCore and see if you are seeing the same behavior. Also can you add DynamicSerilog explcitly like so :https://github.com/SteeltoeOSS/Samples/blob/a77c7226ea2e1d333874baefd6a6c7f8bea91e76/Management/src/CloudFoundry/Program.cs#L19 to narrow down what is happening. A cursory look at using it with a dependency on DynamicSerilogCore seemed to work fine with version 3.2.1.

**Comment by davgia** [comment]
Hi @hananiel,

I've created a [sample project](https://github.com/davgia/steeltoe-issue-1022-sample) to allow you to better understand what's happening and how have I configured it. In the code you will see that I've tried to test for a possible workaround:

https://github.com/davgia/steeltoe-issue-1022-sample/blob/bb25e69fa7f056fdaa3a03e587ff637d2cf1d641/Program.cs#L40

**Comment by hananiel** [comment]
@davgia I started to look at your sample and I understand your issue better. I found poking around that the autoconfig project appears to have a wierd interaction with dynamic serilog. So removing autoconfig and adding it manually works.  Ill continue to work on this ... 

```
  return builder
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
                //.AddSteeltoe(loggerFactory: LoggerBuilder.CreateAutoconfigLoggerFactory());
                .AddDynamicSerilog()
                .AddAllActuators();
```

**Comment by davgia** [comment]
@hananiel, thanks for the reply. I've tried your solution bt for me it does not seem to work either. The problems are:
- "Startup" logger is not present in the list of available loggers
- "SampleController" logger is not added to the list of available loggers when echo endpoint is triggered
- in general I think that I can only see loggers that have been specified in the configuration
- "Default" level is not used as fallback when a new logger is created that does not exist yet and that hasn't been configured from appsettings

I would like to know if you experience the same problem as me. Regards.

**Comment by davgia** [comment]
Any update on this?

**Comment by hananiel** [comment]
Sorry, I haven't had a chance, I'll take a look again today.

**Comment by hananiel** [comment]
@davgia  Sorry, it took me this long - I had a disk failure shortly after I started looking and I lost track of it. Here is what I found ... 
> * "Startup" logger is not present in the list of available loggers

This is expected - since we are bypassing the [DynamicLoggerProvider ](https://github.com/SteeltoeOSS/Steeltoe/blob/1c57efac2ba48e6681f511c1943cf5c752f9625c/src/Logging/src/Abstractions/DynamicLoggerProviderBase.cs#L11)functionality which shows the list of loggers. 
> * "SampleController" logger is not added to the list of available loggers when echo endpoint is triggered

This was because we are not injecting an ILogger<SampleController> as expected. See[ the changes ](https://github.com/davgia/steeltoe-issue-1022-sample/compare/main...hananiel:steeltoe-issue-1022-sample:main#diff-be16bbb247fd1ebabbdf2b33c78c232899680d4d02de7eafcf9564087e1efe86R16)that worked for me.
> * in general I think that I can only see loggers that have been specified in the configuration

This is true if you don't use the ILogger<T> pattern for injecting. We use the factory method to override the created logger with a filtered version that uses either Serilog or dotnet logger with different log levels. 
> * "Default" level is not used as fallback when a new logger is created that does not exist yet and that hasn't been configured from appsettings

I am seeing new loggers created in the list, for example, the SampleController doesn't exist until you post to `/api/sample/echo endpoint`. 

![image](https://user-images.githubusercontent.com/887691/215203190-b48a8de0-b930-49f1-9a40-6162e2eeac52.png)

> I would like to know if you experience the same problem as me. Regards.

**Comment by davgia** [comment]
Hi @hananiel, 

ok got it. Thanks for the support. I think this issue can be closed.

**Comment by davgia** [comment]
@hananiel,

I've changed my codebase with the changes you suggested and I see all loggers from the actuator and I can change their level. But what I've noticed is that the Serilog configuration is not honored. For example, this is my appsettings.json:

``` json
{
    "Serilog": {
        "MinimumLevel": {
            "Default":  "Warning",
            "Override": {
                "MyCompany": "Verbose"
            }
        },
        "Using": [
            "Serilog.Sinks.Console"
        ],
        "WriteTo": [
            {
                "Name": "Console",
                "Args": {
                    "Formatter": {
                        "type": "Serilog.Formatting.Json.JsonFormatter, Serilog"
                    }
                }
            }
        ]
    }
}
```

If I just use `.AddSteeltoe()` the logger level are not set and the formatter is not used. Changing the logging level from the actuator results works fine but the format of the message is wrong (not json).

I'm using steeltoe 3.2.3

**Comment by davgia** [comment]
I finally managed to make everything work. Turns out that I was using the wrong nuget package `Steeltoe.Extensions.Logging.DynamicSerilogBase` instead of `Steeltoe.Extensions.Logging.DynamicSerilogCore`. This caused Autoconfig to skip DynamicSerilogLogger configuration.
