### ISSUE TITLE
EventCounterListener needs the Listener timer to be configurable

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#1026]
Currently the interval for the eventCounterListener is hardcoded to 1 second.
This needs to be configurable.

**Comment by thompson-tomo** [comment]
@TimHess has this not already been implemented in https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Management/src/Endpoint/Metrics/Observer/EventCounterListener.cs with it defaulting to 1 if not provided via config?

**Comment by TimHess** [comment]
@thompson-tomo you are right! This issue should have been closed with #1193, thanks for identifying that
