### ISSUE TITLE
Config Server Provider Config Setting value for Timeout

### ISSUE THREAD

**Issue by donssmith** [SteeltoeOSS/Steeltoe#1058]
## Is your feature request related to a problem? Please describe.
We currently have a lot of apps running on Tanzu Application Service using the Steeltoe Config Server Provider.  We've noticed at times some apps are failing to retrieve config values from a bound Spring Cloud Config Server service instance.  We finally determined that the bound SC config server service instance was taking too long to respond to the .NET app and the Steeltoe Config Server Provider was dropping the connection.  We determined the Config Server Provider default **timeout** is set to [6000 ms](https://docs.steeltoe.io/api/v3/configuration/config-server-provider.html#configure-settings), which seems low and kind of an arbitrary number.  Should this have been 60 seconds (60000 ms), which aligns with the default timeout for the Java Spring Cloud Client?   To address the issue, all of our application owners had to override the default in their **appsettings.json** file to something like:

`"spring": {
  "application": {
    "name": "my-app"
  },
  "cloud": {
    "config": {
      "timeout": 30000
    }
  }
},`

## Describe the solution you'd like
Can the default **timeout** value be set to 60000 to align with the Java Spring Cloud Client default timeout?

## Describe alternatives you've considered
None

## Additional context
None

**Comment by dtillman** [comment]
Thanks for finding and reporting this... I'll update the default timeout value to 60.
