### ISSUE TITLE
Consul health check path is not working

### ISSUE THREAD

**Issue by sergiojrdotnet** [SteeltoeOSS/Steeltoe#1062]
## Describe the bug
Consul health check path is not working

## Steps to reproduce 
1. Add `Consul:Discovery:HealthCheckPath` configuration

![image](https://user-images.githubusercontent.com/72770006/204257121-237e166b-0289-439d-ba06-bac7a553adc1.png)

## Expected behavior
Health check endpoint should be added to service instance on consul portal but it only shows the default TTL check.

![image](https://user-images.githubusercontent.com/72770006/204257340-9befcb16-52ce-433c-88ef-01325bbfa79c.png)

## Environment
 - Steeltoe Version: NuGet package **Steeltoe.Discovery.Consul 3.2.1**
 - Platform: **Local test / Azure**
 - OS: **Windows**
 - .NET Version: **.NET 5**

**Comment by TimHess** [comment]
Hi @sergiojrdotnet,

Thank you for reporting the bug, and I'm sorry for the delayed response! I've done some basic testing and can confirm that I'm seeing the same results even with an updated Consul nuget package and also with Consul server versions as old as 1.8, so it does not seem likely to me that this particular feature ever worked completely correctly. Unfortunately, the core Steeltoe team has a lot of work in flight already, so aside from confirming the bug report I'm not sure when we'll be able to make progress on a fix. Is this an issue important enough to you that you would consider tracking it down and contributing a fix?

**Comment by TimHess** [comment]
I've had a glance at the code and found [this block](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Discovery/src/Consul/Registry/ConsulRegistration.cs#L235) (`IsHeartBeatEnabled` is defined [here](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Discovery/src/Consul/Discovery/ConsulDiscoveryOptions.cs#L201)) is the reason that setting isn't working as expected.

Adding this to appsettings looks weird and wrong, but (as a quick hack) does appear to result in an enabled HTTP health check on the custom path:
```json
  "Consul": {
    "Discovery": {
      "HealthCheckPath": "/my/custom/health",
      "HeartBeat": {
        "Enabled": false
      }
    }
  }
```

**Comment by TimHess** [comment]
> I've had a glance at the code and found [this block](https://github.com/SteeltoeOSS/Steeltoe/blob/3.2.4/src/Discovery/src/Consul/Registry/ConsulRegistration.cs#L235) (`IsHeartBeatEnabled` is defined [here](https://github.com/SteeltoeOSS/Steeltoe/blob/3.2.4/src/Discovery/src/Consul/Discovery/ConsulDiscoveryOptions.cs#L201)) is the reason that setting isn't working as expected.
> 
> Adding this to appsettings looks weird and wrong, but (as a quick hack) does appear to result in an enabled HTTP health check on the custom path:
> 
> ```json
>   "Consul": {
>     "Discovery": {
>       "HealthCheckPath": "/my/custom/health",
>       "HeartBeat": {
>         "Enabled": false
>       }
>     }
>   }
> ```

It turns out our version of "As expected" was based on a assumptions due to missing detail in the documentation around TTL/HeartBeat checks and HTTP/Health Checks. The requirement to disable HeartBeat is actually "as designed" and not a hack.

I've added an issue to improve the docs and open to more input on improving how this works - especially with #1245 still open
