### ISSUE TITLE
Performance issue with Metrics endpoint

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#1079]
## Describe the bug
Performance load testing of metrics actuator endpoint resulted in several 500 errors and timeouts in Jmeter.

## Steps to reproduce 
1. Setup Jmeter to hit metrics endpoint at /metrics
2. Setup number of threads to 10 

## Expected behavior
Should work without undue errors

**Comment by TimHess** [comment]
Fixed in #1078
