### ISSUE TITLE
Connectors: Use DbConnectionStringBuilder instead of string concatenation

### ISSUE THREAD

**Issue by bart-vmware** [SteeltoeOSS/Steeltoe#1092]
[DbConnectionStringBuilder](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbconnectionstringbuilder?view=net-7.0&viewFallbackFrom=dotnet-plat-ext-7.0) has existed since the early days of .NET. It provides parsing, normalization and escaping of special characters such as `;`, `'` and `"` in key-value pairs, in order to produce a valid connection string.

Would be nice if we could use this builder, instead of the current string concatenation.

**Comment by ZuraizAhmedShehzad** [comment]
I have explored the code base and have identified scope of this enhancement. I want to contribute.

**Comment by bart-vmware** [comment]
Hi @ZuraizAhmedShehzad,

I'm working on a significant refactoring of connectors, which includes this change. It's a work in progress and things aren't quite polished yet, but there's a sample at https://github.com/SteeltoeOSS/Samples/blob/latest/Connectors/src/PostgreSqlEFCore/Program.cs in case you'd like to give it a try.

Is there anything in particular you'd like to see supported?
