### ISSUE TITLE
Read configuration for multiple apps

### ISSUE THREAD

**Issue by dominikjeske** [SteeltoeOSS/Steeltoe#1093]
I have situation when I would like to get configs from configuration server for my app (we can call it A) but apart for it I also want to read configuration for something that A is using - we can call it B and this is some configuration set globally that many application can use. The question is: how to read more then one application configuration using Steeltoe?

**Comment by hananiel** [comment]
@dominikjeske You can use different files on the server side. You can put shared configuration in Application.yml and app specific information in ApplicationA.yml and ApplicationB.yml. Please note that the closest equivalent to the spring profile concept is Environment in Dotnet as determined by`ASPNETCORE_ENVIRONMENT ` So if its set to Development, for example the specific configs will be found in ApplicationA-Development.yml

**Comment by dominikjeske** [comment]
@hananiel Application.yml is global for everyone and I would like to have a control of what configs are get. For example I have some global configuration C, D, E and for some applications I would get only C and for others C and D (of course as addition to application A individual config).

**Comment by hananiel** [comment]
@dominikjeske do you perhaps have a minimal spring sample that you can share that can achieve this. At the very least, if you have a solid spring cloud config server config on the server side, we can figure out how to consume it with the steel toe client.

**Comment by dominikjeske** [comment]
@hananiel Generally I'm trying to figure out how to do such use case with Steeltoe+config server. Each app have its own repository (I named apps sharka, sharkb...) this is easy with pattern for repositories but.. applications are using external components that have its own configuration I named it ProfileA, ProfileB... So the question is - how to load more then one configuration (for example sharka+ProfileB). I tried pattern matching magic to match more then one but it stops after first find. As far as I know I can configure only one app in Steeltoe/config server. I also tried composite but I failed to use it with multiple repositories (maybe it is possible but I can't figure it out). Below sample config 

`spring:
  profiles:
   active: git
  cloud:
    config:
      server:
        git:
          uri: https://xxx/scm/arch/poc_configserver_teama.git
          repos:
            ProfileA:
              pattern: 'ProfileA'
              uri: https://xxx/scm/arch/poc_configserver_profileA.git
            ProfileA:
              pattern: 'ProfileB'
              uri: https://xxx/scm/arch/poc_configserver_profileB.git
            sharka:
              pattern: sharka
              uri: https://xxx.com/scm/arch/poc_configserver_teama.git
            sharkb:
              pattern: sharkb
              uri: https://xxx.com/scm/arch/poc_configserver_teamb.git
              `

**Comment by dtillman** [comment]
@dominikjeske, I think, if I understand you correctly, the use of "spring profiles" is what you want to use.  This is best documented in the spring boot documentation (https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.profile-specific) and also in the Config Server documentation (https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_environment_repository)

On the Steeltoe side, you can configure what "profile(s)" you want the config server to return by specifying the "Spring:Cloud:Config:Env" configuration value in your "appsettings.json" file.  This can be a comma separated list, that specifies one or more "profiles" and the config server will return to you those specific configuration values defined as part of the profile(s).  As @hananiel mentioned earlier, the default for "Spring:Cloud:Config:Env" setting is ASPNETCORE_ENVIRONMENT .. which is usually "Production" or "Development".   But, if you specify it in appsettings.json, we should honor that setting, instead of the default, when making the request of the config server.

**Comment by dominikjeske** [comment]
@dtillman thanks for info. I'm aware of profiles and I know that I can use more then one and it can be anything. So in my example I could give multiple profiles but... keep in mind that **my requirement is to use multiple repositories**. If everything would live in one repository it would return me all profiles just like you say. But I want to get application data from one repo and component data from second repo. I tried to make patterns https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_pattern_matching_and_multiple_repositories in such way they should return me two repositories but the problem is that config server is always returning first repository ;(
Do you understand know what I'm trying to achieve?

**Comment by dtillman** [comment]
@dominikjeske : Ahh ... I think I get it... is this what you're looking for: 

https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#composite-environment-repositories

**Comment by dominikjeske** [comment]
I have tried this but I have concerns... It appears that only way to use it is to merge all repositories in composite and use it as whole. I'm not sure how it will perform when I will use 100 repositories in such composite? I tried to use composite inside multiple repos with patterns but it was not designed to use in such way. I will try with one huge composite but I feel it could be better to use multi repo way and client that can download more than one app - but maybe I'm wrong ;)

**Comment by Croitoru** [comment]
> Spring:Cloud:Config:Env

Could you please give an example for this?
I don't quite get it.
What I want to achieve is to get configs for multiple profiles for example the "global" one defined as application.yml,
appName-profileName.yml and I would like to also somehow get appName-commonProfileName.yml
