### ISSUE TITLE
Register Docker Application in Eureka with "preferIpAddress": true

### ISSUE THREAD

**Issue by Isuama** [SteeltoeOSS/Steeltoe#11]
When I register application in IIS and point it to Eureka as shown in this sample, it properly works with these parameters in appsetting.json.
 "eureka": {
    "client": {
      "serviceUrl": "http://172.15.100.155:8761/eureka/",
      "shouldFetchRegistry": false
    },
    "instance": {
      "port": 8091,
      "hostName": "fortune_service",
      "ipAddress": "http://172.15.100.11",

      "preferIpAddress": true
      // Remove comments to enable SSL requests
      // More changes in Program.cs are required if using direct C2C communications
      //,"securePortEnabled": true
    }
  }

When I point cursor over the Eureka Status it shows me the status url (IP I have given above)

But when I run application as a Docker and retrieve value from Confi-Server, it get registered with a dynamic IP for the status and I am unable to discover registered URL. Kindly expect help from someone.

**Comment by jkonicki** [comment]
This is worth investigating further and trying to address in a later release.

**Comment by bart-vmware** [comment]
I'm pretty confident this works as expected, after #1280 has been merged. I've added a test to verify:
```c#
[Fact]
public async Task ExplicitlyConfiguredIPAddressIsPreserved()
{
    var appSettings = new Dictionary<string, string?>
    {
        ["Eureka:Instance:hostName"] = "ignored-host-name",
        ["Eureka:Instance:ipAddress"] = "192.168.10.20",
        ["Eureka:Instance:preferIpAddress"] = "true"
    };

    WebApplicationBuilder builder = WebApplication.CreateBuilder();
    builder.Configuration.AddInMemoryCollection(appSettings);
    builder.Services.AddEurekaDiscoveryClient();

    await using WebApplication webApplication = builder.Build();
    var appManager = webApplication.Services.GetRequiredService<EurekaApplicationInfoManager>();

    appManager.Instance.IPAddress.Should().Be("192.168.10.20");
    appManager.Instance.HostName.Should().Be("192.168.10.20");
}
```
Please let me know if this is still causing problems.
