### ISSUE TITLE
Moving to the new .NET Foundation CLA service

### ISSUE THREAD

**Issue by dnfadmin** [SteeltoeOSS/Steeltoe#1111]
Hello everyone
The .NET Foundation is transitioning to a new CLA service and I'm posting here to let you know it's happening. Some background info:

The new CLA service is based off of https://github.com/microsoft/ContributorLicenseAgreement, except it uses the dotnet-policy-service app

- Current contributors do not need to sign the CLA again
- The CLA agreement itself is not changing
- As part of the install/configuration process, the following work items will be completed

1. Create a .github repo if it doesn't exist already
2. Install the dotnet-policy-service app
3. Create PRs for the platformcontext.xml and cla.yml files
4. Disable the existing CLA webhook
5. Push the PRs to enable the new CLA service

That's all there is to it. I'll update this issue once the work is complete

Thanks
Chris
.NET Foundation Operations team

**Comment by dnfadmin** [comment]
this work is complete

**Comment by bart-vmware** [comment]
Hi Chris,

Recently all of our open PRs started to hang indefinitely on the CLA check. Could this be related to your work?

![image](https://user-images.githubusercontent.com/104792814/225937443-f23d0737-adab-4ff0-8306-e1be709f591e.png)

Also, we didn't see any PRs or changes, as mentioned in step 3.

**Comment by ChrisSfanos** [comment]
Hi @bart-vmware  - I didn't see this, so sorry for not following up.  Let me take a look and see.  I may need to loop in the dev team for this also (side note - please @ me so I get a notification - thanks!)

**Comment by ChrisSfanos** [comment]
Ok looks like we didn't actually complete the work here

Hi @jkonicki  and @TimHess  - can you please add DNFAdmin as an owner at the organization level so my team can fix the CLA issue.  After it's done, I'll update here and you can demote DNFAdmin to member level if you prefer

**Comment by TimHess** [comment]
Hey @ChrisSfanos, it looks like DNFAdmin already is an owner at the org level

**Comment by ChrisSfanos** [comment]
Sigh my bad - when I was looking I was logged in as my personal account and didn't realize I couldn't see it.  We will work on the CLA shortly - thanks @TimHess

**Comment by ChrisSfanos** [comment]
Ok, the work should now be complete - the test PR shows the new CLA service working
https://github.com/SteeltoeOSS/.github/pull/4

**Comment by TimHess** [comment]
Thanks Chriss!

For reference, checks on an existing PR can be re-triggered by pushing an empty commit, which can be created like this:
```
git commit -m "re-trigger checks" --allow-empty
git push
```
