### ISSUE TITLE
Config with Consul KV

### ISSUE THREAD

**Issue by anperim** [SteeltoeOSS/Steeltoe#112]
Please provide a Consul Config Provider. Suggested code:
https://github.com/wintoncode/Winton.Extensions.Configuration.Consul

**Comment by TimHess** [comment]
Hi @anperim,

Thanks for the suggestion - but given that you've pointed us towards a solution that appears to be actively maintained, it's not clear what more you'd like us to provide... Could you please be a little more specific about what you'd like to see us do that isn't being accomplished with the other project?
