### ISSUE TITLE
Add IServiceCollection extension methods to enable Steeltoe

### ISSUE THREAD

**Issue by eerhardt** [SteeltoeOSS/Steeltoe#1123]
## Is your feature request related to a problem? Please describe.
With https://github.com/dotnet/runtime/issues/61634#issuecomment-1033038101 and https://github.com/dotnet/runtime/pull/65109, Microsoft.Extensions.Hosting added a new way of creating a hosted app that doesn't use IHostBuilder.

Along with that, in .NET 8, the "Worker" project template is getting updated to use these new APIs. See https://github.com/dotnet/aspnetcore/issues/43113.

## Describe the solution you'd like
We should add overloads to `HostBuilderExtensions` that accept an `IServiceCollection` or `HostApplicationBuilder` instead of an `IHostBuilder`. This will allow consumers using the new `HostApplicationBuilder` to use Steeltoe easily.

https://github.com/SteeltoeOSS/Steeltoe/blob/9e2cb52e6adab4c0b6c1c52161b59d4800189d40/src/Bootstrap/src/AutoConfiguration/HostBuilderExtensions.cs#L61

## Additional context
See also https://github.com/dotnet/runtime/pull/68580

**Comment by TimHess** [comment]
Hi @eerhardt,

Thanks for the note, I really appreciate the proactivity here. 

We do already have many extensions for `IServiceCollection` throughout Steeltoe, and aside from the one you've pointed out I think we're already in decent shape. We were planning to review all of these for our next major release anyway though, so I'll leave this issue open as we reconsider all instances of this type of extension.

**Comment by eerhardt** [comment]
Thanks, @TimHess. Also check out a proposal I just opened to add an abstraction for these new application builders in .NET 8:

https://github.com/dotnet/runtime/issues/85486

Looking at the above extension method, it would probably need an abstraction that is being proposed. The extension method is using a lot of things on IHostBuilder:

* Properties
* Configuration
* Services

**Comment by bart-vmware** [comment]
@eerhardt We've completed this work in #1317. Our chosen strategy is detailed below.

1. We've removed all redundant host builder extension methods.
    - No host builder extension methods are provided, if we only need `IConfigurationBuilder`, or only `IConfiguration`, or only `IServiceCollection`, or only `ILoggingBuilder`, etc.
    - No host builder extension methods are provided if we additionally need `IConfiguration`. It can be obtained from the `context` parameter. For example: `webHostBuilder.ConfigureServices((context, services) => { var configuration = context.Configuration; });`

2. In the cases where we need a combination (such as `IConfigurationBuilder` and `IServiceCollection`) for a feature to work properly, we offer host builder extension methods (on `IHostBuilder`, `IWebHostBuilder`, and `IHostApplicationBuilder`) for convenience. They call into our existing public extension methods on `IConfigurationBuilder`, `IServiceCollection`, etc.

3. The extension methods we do offer on the various host builders are unified internally through `HostBuilderWrapper`, which forwards callbacks to the underlying host builder-specific methods, such as `ConfigurationAppConfiguration`/`ConfigureLogging`, etc. This enables us to keep implementation minimal.

Here's an example. We offer extension methods on the various host builders, which all send their logic through the wrapper to call existing Steeltoe extension methods on `IServiceCollection` and others.
```c#
public static IHostBuilder AddEnvironmentActuator(this IHostBuilder builder)
{
    HostBuilderWrapper wrapper = HostBuilderWrapper.Wrap(builder);
    InternalAddEnvironmentActuator(wrapper);
    return builder;
}

public static IWebHostBuilder AddEnvironmentActuator(this IWebHostBuilder builder)
{
    HostBuilderWrapper wrapper = HostBuilderWrapper.Wrap(builder);
    InternalAddEnvironmentActuator(wrapper);
    return builder;
}

public static IHostApplicationBuilder AddEnvironmentActuator(this IHostApplicationBuilder builder)
{
    HostBuilderWrapper wrapper = HostBuilderWrapper.Wrap(builder);
    InternalAddEnvironmentActuator(wrapper);
    return builder;
}

private static void InternalAddEnvironmentActuator(HostBuilderWrapper wrapper)
{
    wrapper.ConfigureServices(services => services.AddEnvironmentActuator());
    wrapper.ConfigureServices(services => services.ActivateActuatorEndpoints());
    wrapper.ConfigureWebHost(webHostBuilder => webHostBuilder.AddManagementPort());
}
```
