### ISSUE TITLE
Prometheus endpoint error

### ISSUE THREAD

**Issue by davgia** [SteeltoeOSS/Steeltoe#1125]
## Describe the bug
Prometheus endpoint blank output when used in conjunction with OpenTelemetry.Exporter.OpenTelemetryProtocol 1.4.0 (works on 1.3.2). This is the reported error:

``` json
{"Timestamp":"2023-04-19T00:00:00+00:00","Level":"Error","MessageTemplate":"Collection failure.","Properties":{"SourceContext":"Steeltoe.Management.Endpoint.Metrics.PrometheusScraperEndpoint","RequestPath":"/actuator/prometheus"}
```

## Steps to reproduce 
1. Create a basic .net 6 microservice
2. Add Steeltoe management dependencies (EndpointCore, TracingCore) 3.2.3
3. Add OpenTelemetry.Exporter.OpenTelemetryProtocol 1.4.0

## Expected behavior
The endpoint should not fail.

## Environment (please complete the following information):
 - Steeltoe Version 3.2.3
 - Platform: Kubernetes or local (Windows)
 - OS: Linux or Windows
 - .NET Version .NET 6.0
 - OpenTelemetry.Exporter.OpenTelemetryProtocol 1.4.0

**Comment by hananiel** [comment]
Hi @davgia Thanks for bringing attention to this issue. The Steeltoe project in 3.x automatically takes a dependency on Otel 1.2. Adding any other assembly with a higher version causes this to become incompatible. We need to work on updating our dependency to 1.4 and resolving any compatibility issues. I have created #1127 to do this.

**Comment by hananiel** [comment]
@davgia after investigating and talking to the team, we decided the better option is to lock 3.x of Steeltoe to the version it has been built with. I am currently testing it with 1.3.2 and if it works, the next version of 3.x will have a constraint like 
    `<OpenTelemetryVersion>[1.2.0, 1.3.2]</OpenTelemetryVersion>`. So adding a dependency that requires a higher version will result in a compile error. 
The upgrade path is to use Steeltoe 4.x which does not take a direct dependency on Otel.
