### ISSUE TITLE
PlaceholderResolver filters out empty string values

### ISSUE THREAD

**Issue by jvmlet** [SteeltoeOSS/Steeltoe#1132]
PlaceholderResolver filters out empty string values, to reproduce :

````c#
        string v = "";
        string value = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string>()
            {
                ["key"] = v
            })
            .AddPlaceholderResolver() //comment this line and test passes
            .Build()
            .GetSection("key")
            .Value;

        value.Should().Be(v);
````
 
Empty value **DOES** matter, for example: the presence of key with empty value could be treated as value  equals to key

*  Steeltoe.Extensions.Configuration.PlaceholderCore Version="3.2.3"
*  .net 6

**Comment by TimHess** [comment]
Thanks for reporting this issue @jvmlet, it will be fixed for future Steeltoe releases

**Comment by jvmlet** [comment]
Thanks @TimHess , do you have the estimations for next release date?

**Comment by TimHess** [comment]
I don't have an estimated release date yet... We usually try to include a few fixes in patch releases, but I think this might be the only one queued up in 3.2.4. I can get the address to our dev feed if you'd like start using it sooner than the next release to nuget.org
