### ISSUE TITLE
IHttpClientHandlerProvider is not passed to EurekaDiscoveryClient

### ISSUE THREAD

**Issue by har-bw** [SteeltoeOSS/Steeltoe#1137]
## Describe the bug
When adding the Steeltoe Eureka Discovery Client to the service collection (e.g. serviceCollection.AddServiceDiscovery( b => b.UseEureka() );), the created EurekaDiscoveryClient will not pick up any IHttpClientHandlerProvider registered in the service collection.

In the corresponding code, it is attempted to cast ServiceDescriptor to IHttpClientHandlerProvider, which is not possible.

## Steps to reproduce 
1. Implement a custom IHttpClientHandlerProvider and add it to the service collection
2. Add the Eureka Discovery Client to the service collection
3. IHttpClientHandlerProvider.GetHttpClientHandler() will never be called

## Expected behavior
The EurekaDiscoveryClient should use a HttpClientHandler created by GetHttpClientHandler() of the IHttpClientHandlerProvider implementation.

## Environment (please complete the following information, if applicable):
 - Steeltoe Version 3.2.3
 - Platform: Windows, Linux/Kubernetes

## Additional context or links
It appears this line is not working as intended:
https://github.com/SteeltoeOSS/Steeltoe/blob/16a4b3a92fb97b5181a127e2a148a213a359db62/src/Discovery/src/Eureka/EurekaDiscoveryClientExtension.cs#L212

**Comment by TimHess** [comment]
Hi @har-bw,

Thanks for reporting the issue, I can confirm there is a problem here and I have a fix that I'll open a PR for next week. Can I ask what your use case is for `IHttpClientHandlerProvider`? The one built-in usage we had for it was removed in #778 and apparently there wasn't a test for this

**Comment by har-bw** [comment]
Hello @TimHess,

Thank you for your fast response!

We have a special case for some on-prem environments, where we need to use a custom trust store in our services. Therefore, we implemented a custom validator that is passed to the `HttpClientHandler` as `HttpClientHandler.ServerCertificateCustomValidationCallback` to validate server certificates. The client certificate is set this way as well.
