### ISSUE TITLE
StreamConfigurationProviders cannot be loaded more than once

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#1169]
## Describe the bug
Using SpringBootEnvProvider in conjunction with PlaceholderResolver results in an error: 
```
Unhandled exception. System.InvalidOperationException: StreamConfigurationProviders cannot be loaded more than once.
   at Microsoft.Extensions.Configuration.StreamConfigurationProvider.Load()
   at Steeltoe.Extensions.Configuration.SpringBoot.SpringBootEnvProvider.Load()
```

## Steps to reproduce 
1.AddPlaceholderResolver
2.Use any extension method that adds AddSpringBootFromEnvironmentVariable 

## Expected behavior
Should work without throwing errors

## Environment (please complete the following information):
 - Steeltoe Version [e.g. 3.2.3]
 - .NET Version [e.g. .NET 6] 
 - Any other library versions to note

**Comment by TimHess** [comment]
@hananiel does #1170 still need to be applied to `main`?

**Comment by hananiel** [comment]
Yes this needs to be applied to main as well.
