### ISSUE TITLE
RFC: Steeltoe support of .NET Framework components

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/steeltoe#117]
## Summary
As you may have heard, Microsoft recently announced [.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5). It is the next step in the .NET runtime's future. A significant feature of .NET 5 is creating a unified platform between .NET Framework and .NET Core. The Steeltoe community has shown, with its use of Steeltoe’s .NET Framework capabilities, that there is a need to unify our support of both versions of .NET, also. So, the Team is currently evaluating the best way to support both lines.

The plan is that there will be two active versions of Steeltoe going forward. The current 2.x releases will continue to enable those wanting to bring .NET Framework and .NET Core apps to a cloud platform. The 3.x release will focus on .NET Core and its future long term support features. 
  

## Why make this move?
Microsoft has announced that .NET Framework 4.8 will be the last minor release and that the future will be .NET 5 (.NET Core vNext) moving forward. It makes sense for the Steeltoe framework to follow the life cycle of .NET runtimes and Microsoft’s support policies..

## Why now?
Steeltoe 3.0 is a great time to make this move.  We will be developing new capabilities in 3.0 and want to encourage cloud-native .NET microservice development against the latest and most feature-rich releases from .NET.

## What does this mean for your .NET Framework applications?
We will still be support and building on our Steeltoe 2.x line.  If the community identifies, or requests, to add components that would be good for both our 2.x line and our 3.x line, then the Steeltoe team will make the decision to add that component to the 2.x line too.  

## What can you do?
We would love to hear from you!  If you have any questions or concerns about this change, please leave your comments below.  
We welcome you to bring your opinions in issues, contribute code, request features, and join the discussions.  Feel free to bring up any Steeltoe related questions or requests to our [Steeltoe Slack Channel](https://slack.steeltoe.io).

Thank you,

The Steeltoe Team

**Comment by TimHess** [comment]
Net461 features and testing have been dropped from `master` (3.x line) in #94 -- support remains in the `2.x` branch
