### ISSUE TITLE
Setting the "Spring:Cloud:Config:Timeout" configuration property doesn't affect the HttpClient timeout

### ISSUE THREAD

**Issue by douggish** [SteeltoeOSS/Steeltoe#1178]
## Describe the bug
Setting the "Spring:Cloud:Config:Timeout" configuration property doesn't seem to work. The library seems to use the default of 6 seconds (although I see this will soon be changed to 60s: https://github.com/SteeltoeOSS/Steeltoe/pull/1060) regardless of what the timeout config property is set to. If the config server takes longer than 6s to respond, it results in an exception like the following:

```
fail: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]
      Config Server exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 6 seconds elapsing.
       ---> System.TimeoutException: The operation was canceled.
       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
       ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cance
llationToken originalCancellationToken)
         --- End of inner exception stack trace ---
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsC
ts)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cance
llationToken originalCancellationToken)
         at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.RemoteLoadAsync(String requestUri), path: http%3A%2F%2Flocalhost%3A8763%2Ffoo%2FProduction
```

I got the above exception even when my appsettings.json looks like this:
```json
{
  "$schema": "https://steeltoe.io/schema/latest/schema.json",
  "Spring": {
    "Application": {
      "Name": "foo"
    },
    "Cloud": {
      "Config": {
        "HealthEnabled": true,
        "DiscoveryEnabled": true,
        "Uri": "http://localhost:8763",
        "ValidateCertificates": false,
        "Timeout": 20000
      }
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "Management": {
    "Endpoints": {
      "Actuator": {
        "Exposure": {
          "Include": [ "*" ],
          "Exclude": [ "env", "refresh" ]
        }
      }
    }
  }
  // Discovery-first
  //,"Eureka": {
  //  "Client": {
  //    "ServiceUrl": "http://localhost:8761/eureka/"
  //  }
  //}
}
```

## Steps to reproduce 
1. Start with the "Simple" configuration sample here: https://github.com/SteeltoeOSS/Samples/tree/main/Configuration/src/Simple
2. Change appsettings.json to add the Timeout property under the Spring:Cloud:Config section and set it to something other than 6000 (e.g. 20000).
3. Startup a dummy config server that is very slow to respond to requests. I just used a new .net web api project with a controller method that gets routed all requests and then does a Task.Delay:
``` c#
[ApiController]
[Route("{**catchAll}")]
public class WeatherForecastController : ControllerBase
{
	
	[Route("/{**catchAll}")]
	public async Task<IActionResult> Echo()
	{
		await Task.Delay(10000);
		return Ok();
	}
}
```
4. Change the Spring:Cloud:Config:Uri property in appsettings.json as required to point to the dummy config server.
5. Start the "Simple" configuration sample and see the exception in the console output mentioning the timeout of 6 seconds.

## Expected behavior
Expected result is that the timeout used by the HttpClient would match the configured Timeout value.

## Environment (please complete the following information):
 - Steeltoe Version: tried both 3.2.3 and 3.2.4
 - Platform: N/A
 - OS: Windows
 - .NET Version: 6.0

## Additional context or links
The issue may be due to the way _httpClient is initialized here:
https://github.com/SteeltoeOSS/Steeltoe/blob/3.2.3/src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs#L143
since the settings used are the "defaultSettings":
https://github.com/SteeltoeOSS/Steeltoe/blob/3.2.3/src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs#L122

**Comment by TimHess** [comment]
Hi @414004738,

I agree, it looks like there's a bug here. The solution might be as simple as calling `OnSettingsChanged();` before getting the HttpClient, but we probably need to do a bit more investigation to make sure - were you interested in contributing the fix via PR?

**Comment by 414004738** [comment]
> were you interested in contributing the fix via PR?
Perhaps I could try. What would be the process for contributing?

**Comment by 414004738** [comment]
I've discovered that the timeout configuration property worked as expected in version 3.1.3. I'm not sure if that is the most recent version without the bug, but it seems like the defect was introduced sometime after 3.1.3.

**Comment by TimHess** [comment]
The process is spelled out [here](https://github.com/SteeltoeOSS/.github/blob/main/CONTRIBUTING.md), and we're happy to help with any of the process, but the short version is this:

1. Fork the repo
2. Create a branch from the branch you want to change (`/release/3.2` in this case)
3. Make and commit your changes
4. Open a PR
5. Sign the .NET Foundation CLA (this can actually happen at any point in time)

I did spend a few more minutes looking at this, and my first instinct could probably work out, but it wouldn't help if the timeout is changed while the app is running. I think a better change is to add some logic in `OnSettingsChanged` to update the _httpClient timeout. However, that also has me wondering what else should be updatable on the http client (client certs, headers, etc), so could benefit from a little more thought. Additionally, adding the line to update the timeout makes a couple tests break because they are setting that timeout to 0 (I don't know why) which is invalid, so we might need to do some checks before assigning the timeout.

**Comment by 414004738** [comment]
OK, I'm just checking with my company about making an OSS contribution and signing the CLA.

**Comment by douggish** [comment]
Hi @TimHess. I submitted a PR (sorry for the delay). So far I went with the simpler approach of calling OnSettingsChanged() before initializing the _httpClient field. I thought a little bit about your other suggestion to update the http client when config settings change. I wasn't sure about the thread safety of modifying the existing _httpClient and I also was thinking you probably wouldn't want to change or replace an http client that was passed into the ConfigServerConfigurationProvider constructor, so there would probably have to be a way to track whether it was an internally created http client or not. Perhaps we can go with the simpler fix for now and defer getting it to update the http client if config changes?

**Comment by TimHess** [comment]
The simple fix seems appropriate for the 3.x line of Steeltoe, we can consider something more advanced for 4.0 or in the future

**Comment by douggish** [comment]
Thanks, @TimHess. I see my PR was merged and has a milestone of 3.2.5. Do you know when the 3.2.5 version is planned to be released?

**Comment by TimHess** [comment]
Hi @douggish, we don't have a set release schedule, so we can ship it whenever we feel [3.2.5](https://github.com/SteeltoeOSS/Steeltoe/milestone/41) contains a significant fix or enough changes to warrant completing the release process. At this time, there's only one other change I'm expecting to want to include in that patch release, so we may be able to release in the next week or two.

**Comment by donssmith** [comment]
The default value of 6 seconds seems odd and may be a typo?  60000ms instead of 6000ms.  I believe the default timeout value for the Spring Cloud Config Server is 60 seconds, which we may want to keep in parity with.
