### ISSUE TITLE
Add automated tasks to check for explicit version numbers

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#118]
## Is your feature request related to a problem? Please describe.
Dependencies should be driven off of versions.props to get a handle on the dependency tree and to avoid breaking changes by pulling in incompatible versions.  

## Describe the solution you'd like
Add an automated task to look for explicit dependencies such as . "2.2.0" instead of $someversion

**Comment by TimHess** [comment]
This was related to centralizing dependency versions outside of individual .csproj files, but we can handle that at PR time and likely don't need automation as this doesn't happen often.
