### ISSUE TITLE
Endpoint Routing: EndpointMiddlewares should be visible in Swagger

### ISSUE THREAD

**Issue by Lonli-Lokli** [SteeltoeOSS/Steeltoe#119]
## Is your feature request related to a problem? Please describe.

Currently we have project with https://github.com/microsoft/aspnet-api-versioning project integrated, and endpoints (/info, /health, etc) are not visible in swagger

## Describe the solution you'd like
I'd like to see the way how can I add them to the swagger.

**Comment by TimHess** [comment]
Using EndpointRouting might solve this issue for Asp.NET Core 3+ https://asp.net-hacker.rocks/2019/04/10/routed-middlewares.html?1

**Comment by TimHess** [comment]
Also evaluate whether we can improve the CORS configuration/configuration to be more narrowly focused on Steeltoe endpoints and/or more easily configurable. It looks like there are some changes in ASP.NET Core 3

https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.0

**Comment by jkonicki** [comment]
Need to register with routing so it will show up.

**Comment by TimHess** [comment]
Ideally this will work with `dotnet new webapi` in aspnet 3.1, without mvc integration (only endpoint routing)

**Comment by hananiel** [comment]
I looked into this - Swagger implementations use ApiExplorer for discovering Api to document and ApiExplorer uses attribute routing attributes to discover them. So they intentionally treat endpoints that are not attributed routed differently. So for example Microsoft AddHealthChecks middleware is not discovered and published in swagger either. In addition Steeltoe's Mappings endpoint treats the management endpoints differently as does Spring Boot. 
I think the best approach to help with discoverability one could create a custom Swagger content that loads the contents of /actuator.

**Comment by TimHess** [comment]
There are other benefits for hooking into Endpoint Routing, here's a recent video that explains more: https://channel9.msdn.com/Shows/On-NET/ASPNET-Core-Series-Endpoint-Routing

**Comment by Lonli-Lokli** [comment]
Just 2c, here is the implementation for gRPC 
https://github.com/aspnet/AspLabs/blob/master/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.Swagger/Internal/GrpcHttpApiDescriptionProvider.cs

**Comment by jkonicki** [comment]
Some of this work was done in PR #361.  The rest will be explored in #380
