### ISSUE TITLE
Support Tanzu Application Configuration Service

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#1195]
Given that [Tanzu Application Configuration Service](https://docs.vmware.com/en/Application-Configuration-Service-for-VMware-Tanzu/2.0/acs/GUID-overview.html) can be viewed as a successor to Spring Cloud Config Server, Steeltoe should also support reading configuration provided by it.

Preliminary support provided by the new Kubernetes.ServiceBindings package already reads in configuration provided by the service and for a configurationSlice named "spring-properties" will result in IConfiguration entries such as this:

```json
"k8s:bindings:spring-properties:cook.special": {
  "value": "Pickled Cactus"
},
"k8s:bindings:spring-properties:dessertMenu": {
  "value": "Strawberry Cake with Whipped Cream"
},
"k8s:bindings:spring-properties:provider": {
  "value": "acs"
},
"k8s:bindings:spring-properties:secretMenu": {
  "value": "Crawfish Casserole"
},
"k8s:bindings:spring-properties:type": {
  "value": "config"
}
```

We should remap any non-system keys to the root of the configuration so they can be easily accessed by developers. We should not map system keys like "provider" or "type" as those are only likely to cause confusion

**Comment by bart-vmware** [comment]
@TimHess Since the related PR has been closed unmerged, does this issue need to remain open?

**Comment by TimHess** [comment]
Steeltoe support for working with Tanzu Application Configuration Service is being put on hold at this point in time. For anyone looking to use Application Configuration Service in a .NET application, please reach out and let us know. It wouldn't take too much work, but we are not presently aware of any demand for this support and would like customer input before adding the code.
