### ISSUE TITLE
Handle Content Negotiation on endpoints correctly

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/steeltoe#120]
## Is your feature request related to a problem? Please describe.
The spring actuator endpoints response depends on the request headers passed in.For example: 
`curl -v -H "`**Accept: application/vnd.spring-boot.actuator.v2+json, application/vnd.spring-boot.actuator.v1+json, application/json**`" http://localhost:8083/actuator`

Responds with: 
`< HTTP/1.1 200 OK
< Content-Type: `**application/vnd.spring-boot.actuator.v2+json;charset=UTF-8**

Whereas:
`curl -v -H "`**Accept: application/json" http://localhost:8083/actuator**
responds with: 

`< Content-Type: `**application/json;charset=UTF-8**

Even though, the schema for the json is the same. 

For Steeltoe endpoints, when the schema is different we respond with the highest level of implementation available based on configured media type. 

This breaks apps like codecentric/spring-boot-admin which perform strict checking of headers and might break future versions of apps manager. 

## Describe the solution you'd like
The middleware should set the content headers based on accept headers on request. 

## Describe alternatives you've considered
A work around is to disable strict checking in other applications.

**Comment by Karql** [comment]
Hi @hananiel 

Imo there is a bug in this solution.

> trce: Steeltoe.Management.Endpoint.Metrics.MetricsEndpointMiddleware[0]
      setting contentType to application/json;charset=UTF-8
trce: Steeltoe.Management.Endpoint.Metrics.MetricsEndpointMiddleware[0]
      Header: Accept - application/vnd.spring-boot.actuator.v2+json,application/vnd.spring-boot.actuator.v1+json,application/json

Imo Content-type should be set to max supported version.
I've levead some comments in PR https://github.com/SteeltoeOSS/steeltoe/pull/124
