### ISSUE TITLE
Investigate removing the trace and metrics exporters that depend on OTEL

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#1202]
Currently a number of backend specific exporters including Jaeger exporter https://www.nuget.org/packages/OpenTelemetry.Exporter.Jaeger/ and https://www.nuget.org/packages/Wavefront.SDK.CSharp/1.8.0-beta are either deprecated or going to be deprecated in favor of using OTLP. 

Steeltoe wraps these Otel exporters to provide defaults that make sense on various platforms like TAS, TAP etc. 

This ticket is to check the feasibility and support level of various backends : Prometheus on TAS, Prometheus on TAP, Wavefront (Aria), Jaeger , Zipkin on standalone, TAS, TAP, ASA-E and replace with OTLP exporter when possible.

**Comment by TimHess** [comment]
Jaeger has already been removed... Closing the remainder of this issue in favor of #1279
