### ISSUE TITLE
Serilog.ILogger Cannot Be Used!

### ISSUE THREAD

**Issue by lastsignal** [SteeltoeOSS/Steeltoe#1203]
Working with a simple .NET 6 application like the following. I am not able to get a use of `Serilog.ILogger` in my code. Everything else work perfectly with `Microsoft.Extensions.Logging.ILogger`

``` csharp
using Serilog;
using Steelto.Extensions.Configuration.CloudFoundry;
using Steeltoe.Extensions.Logging.DynamicSerilog;
using Steeltoe.Management.Endpoint;
using Web.Application.Logging;

var builder = WebApplication.CreateBuilder(args);

builder.AddCloudFoundryConfiguration();

builder.AddDynamicSerilog(configurationLogger: (_, lg) =>
{
    lg.Initialize();
});

builder.WebHost.AddAllActuators();
builder.Services.AddControllers();
builder.Services.AddSingleton(Log.Logger);

var app = builder.Build();

app.MapControllers();

app.Run();
```
In the above code `Initialize()` just configures the logger with its sinks. 

If I don't add the line `builder.Services.AddSingleton(Log.Logger);`, `Serilog.ILogger` will be null. When I add it, it will resolved to `SilentLogger`;

I tried different way to get access to serilogLogger from the library before it turns to FrameworkLogger, no luck!

Any suggestion?

Dan

**Comment by bart-vmware** [comment]
Hi @lastsignal, thanks for asking.

I'm unsure if Steeltoe supports using `Serilog.ILogger` instead of `Microsoft.Extensions.Logging.ILogger`.
@hananiel Can you shed some light on this?

@lastsignal Is there any particular reason you prefer or need to use the Serilog-specific logger instead of the Microsoft abstraction?

**Comment by lastsignal** [comment]
@bart-vmware,
Several reasons:

- Some existing applications that already use `Serilog.ILogger` and `Steeltoe v2` that need to be upgraded. 
- `Serilog.ILogger` has some features that make the log statement simpler. 
  - It has extensions for LogContext that makes the Scope logging cleaner.
  - It has built-in destructured serializer feature
  - There are other add-ons like TimeOperation that makes some metrics easier
- Serilog has a very clean way of unit testing support.

All the features can be implemented in different way in the Framework Logger. But changing existing apps, with a lot of unit tests, wouldn't be practical. 

I think what can help is to expose the Serilog Logger from the provider:
https://github.com/SteeltoeOSS/Steeltoe/blob/9781c9ff24757dfd447dbedcae7fe4c7a82b8b55/src/Logging/src/DynamicSerilog/SerilogDynamicProvider.cs#L56


Thanks

**Comment by lastsignal** [comment]
In addition, 'Log.Logger' is very handy in many places like static classes that don't have DI. This package sets `Log.Logger` to `SilentLogger`. Maybe setting `Log.Logger` to `_serilogLogger` in the code about is an option? 

After all, this package is called `DynamicSerilog`. It gives the impression that it completely supports Serilog.

Cheers

**Comment by hananiel** [comment]
@lastsignal I understand the convenience that using the static logger provides. Steeltoe's `DynamicSerilog` package allows configuration to be changed at runtime. Steeltoe does this by using the infrastructure that targets Microsoft ILogger/ILoggerFactory abstractions. Using the static Serilog logger would bypass the filter mechanism Steeltoe uses to provide dynamic `LogLevel` filters (changed via [logger actuator](https://docs.steeltoe.io/api/v3/management/loggers.html)). So even though the configured logger would be exposed, it would only respect the configuration provided to it at startup. All other changes will be lost. If you do not need that,  then you can directly use the Serilog Logger directly.

**Comment by lastsignal** [comment]
@hananiel, I understand the trade off. But can we at least have Serilog.ILogger registered in the IoC? Can it be done right after the line that I mentioned above?

**Comment by hananiel** [comment]
@lastsignal I am unclear on why you need the Steeltoe extension to do this- which features of Steeltoe are you leveraging by doing this? Do you want to create a sample app we can walk through. I am also available for a zoom call to discuss if that will be better. We can continue via the [Steeltoe slack channel](https://steeltoeteam.slack.com/join/shared_invite/zt-1cd7lh4pi-BlfQsI6nEDEX2qbh5JrRZw#/shared-invite/email)

**Comment by bart-vmware** [comment]
As Hananiel explained, Steeltoe provides changing log levels at runtime using Serilog when utilizing the `Microsoft.Extensions.Logging.ILogger` infrastructure. If there's no need for dynamically changing log levels, feel free to use Serilog directly without its Steeltoe facilities.

Closing this issue, as I think there's nothing we can do. Please let us know if you need this to be reopened.
