### ISSUE TITLE
Introduce a nicer way of adding dynamic logging

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/steeltoe#122]
## Is your feature request related to a problem? Please describe.
Currently dynamic logging must be configured inside `.ConfigureLogging`, and if not done carefully may result in duplicate logs to the console

## Describe the solution you'd like
Add a new extension method for IWebHostBuilder/IHostBuilder that also removes any console logger before adding the dynamic console logger

## Additional context
Add any other context, code snippets, or examples of the feature here.

**Comment by jkonicki** [comment]
Samples will also need to be updated once this is complete
