### ISSUE TITLE
ConfigServerConfigurationProvider and PlaceholderResolverProvider should implement IDisposable

### ISSUE THREAD

**Issue by douggish** [SteeltoeOSS/Steeltoe#1226]
## Describe the bug
We ran into an issue affecting our integration tests where our test run would hang and/or exhibit strange connection issues. We first noticed the issue after setting PollingInterval to a non-zero value (which causes _refreshTimer in ConfigServerConfigurationProvider to be initialized). Our test infrastructure uses the TestServer class, which we start before every test and dispose after every test. So when each test is started, another timer is created and assigned to _refreshTimer that is not disposed at the end of the test when the TestServer is disposed. Eventually after about ~150 tests we see strange connection issues and stalls/hangs our integration test run.

We determined the issue to be caused by the ConfigServerConfigurationProvider not disposing of its disposable objects such as _refreshTimer, _tokenRenewTimer, and _httpClient. We were able to create a subclass of ConfigServerConfigurationProvider that implements IDisposable (as well a derived class of ConfigServerConfigurationSource and our own ConfigurationBuilderExtensions). Unfortunately, simply implementing IDisposable on ConfigServerConfigurationProvider was not enough since we are also using PlaceholderResolverProvider which nested the previously registered providers inside of it, and PlaceholderResolverProvider wasn't calling dispose on the providers nested inside it. However, we were able to keep a handle on our created derived ConfigServerConfigurationProvider class and manually call Dispose() on it when our service was shutting down as a "work-around". After modifying our service to call Dispose on our derived ConfigServerConfigurationSource when shutting down, we ran the test suite again and did not observe the issue.

The Host class will dispose of its ConfigurationRoot object when it is disposing and the ConfigurationRoot class will call [dispose on any configuration providers](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationRoot.cs#L108) it contains that implement IDisposable. So there is a mechanism that will call Dispose() on configuration providers when the service is shutting down. However, if there are configuration providers such as the PlaceholderResolverProvider that "wrap" or nest other configuration providers, they also need to implement IDisposable and call Dispose() on any of the providers that they are wrapping.

## Steps to reproduce 
1. Implement a service that uses both the ConfigServerConfigurationProvider and the PlaceholderResolverProvider.
2. Configure the PollingInterval on the ConfigServerConfigurationProvider so that _refreshTimer is initialized with a new Timer.
3. Create a test that creates, starts and disposes a TestServer for that service
4. See that Dispose is never called on _refreshTimer.

## Expected behavior
Expected behavior is for configuration providers to dispose of their disposable resources when the hosting service is shutting down (or when using TestServer, when the TestServer is disposed). For ConfigServerConfigurationProvider it should dispose of _refreshTimer, _tokenRenewTimer, and _httpClient (perhaps only dispose _httpClient if it was creating internally and not passed into the constructor). For PlaceholderResolverProvider it should dispose any of the nested providers/configuration that it contains that implement IDisposable.

## Environment (please complete the following information):
 - Steeltoe Version: 3.2.6
 - Platform: N/A
 - OS: Linux
 - .NET Version: 6.0

**Comment by bart-vmware** [comment]
Hi @douggish, thanks for the detailed report. I've opened PR #1228 which fixes this.

**Comment by douggish** [comment]
Hi @bart-vmware, thanks for taking a look at this! Will it be fixed on the 3.2 release branch as well?

**Comment by bart-vmware** [comment]
I suppose we could, right @TimHess? Let's first get my changes approved on main.

**Comment by TimHess** [comment]
> Hi @bart-vmware, thanks for taking a look at this! Will it be fixed on the 3.2 release branch as well?

I suppose I could have stated it outright, but when I applied the ReleaseLine labels for 3.x and 4.x this is what I was implying :)

**Comment by bart-vmware** [comment]
Reopening to backport to 3.x
