### ISSUE TITLE
Report hystrix metrics using System.Diagnostics.Metrics

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1236]
## Is your feature request related to a problem? Please describe.
I want my hystrix metrics reported alongside all my other metrics

## Describe the solution you'd like
Hystrix metrics are recorded using System.Diagnostics.Metrics so that my open telemetry collector can collect them and export them to my tools ie ELK/graphana

## Describe alternatives you've considered
Implenting middle ware to receive the hystrix dashboard calls & record them as metrics

## Additional context
I want to only have to use 1 tool to visualize my metrics

**Comment by TimHess** [comment]
Hi @thompson-tomo,

Can you share how broadly you are using Hystrix and any reasons you're using it over Polly?

Hystrix has been placed in maintenance mode (#1070) and the core team is unlikely to pick up feature work for it at this time, but we would be open to further discussion.

**Comment by thompson-tomo** [comment]
Hi @TimHess integrating a circuit breaker was a task I had been advised I should look at doing a while ago for work and was sitting in my Backlog for a while. At the time I had discussed it with a number of teams who advised me that they are using Hystrix on Java. Hence I thought it would be beneficial to try and use the same tool chain. Obviously I wasn't aware of the discontinuation but will now update my Backlog item to refer to Polly.

I am happy for this to be closed if you agree.

**Comment by TimHess** [comment]
@thompson-tomo that all makes sense, I hope the Java teams have already moved to Resilience4J!

To be clear, we will still provide support for Hystrix as long as there is a Steeltoe release that includes it and is still within our support policy, but I would not advise using it for new development efforts.

I'm going to close this issue for now, but if anybody else is interested in building out this functionality we would accept a PR

**Comment by thompson-tomo** [comment]
No worries at all Tim, perhaps the deprecation message suggestion could be worded such that it discourages new development, prompts others to plan a migration but know fixes if needed will provided until x date.
