### ISSUE TITLE
Newtonsoft.json has a high vulnerability

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1239]
## Describe the bug
A couple of the libraries are using Newtonsoft 11 which has 

## Steps to reproduce 
1. Open project in visual studio
2. Observe packages in Package Manager including Newtonsoft has a high vulnerability

## Expected behavior
Package updated to 13 or replaced with system.text.json

## Environment (please complete the following information):
 - Steeltoe 3.2.6

## Additional context or links

- https://github.com/advisories/GHSA-5crp-9r3c-p9vr

**Comment by TimHess** [comment]
We don't believe this change can happen in the v3 line of Steeltoe. Steeltoe v4 removes this dependency entirely, and end users of Steeltoe v3 should be able to choose to upgrade or ignore this issue at their discretion.
