### ISSUE TITLE
Switch to Central package management

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1270]
## Is your feature request related to a problem? Please describe.
I want to make it easier to manage packages.

## Describe the solution you'd like
I would like that all dependencies are managed using central package management and the custom variables are removed.

## Describe alternatives you've considered
Continue with current solution

## Additional context
Happy to take this task on.

**Comment by bart-vmware** [comment]
I've looked into this a few months back. While it sounds nice, the experience is still full of bugs. Fixing them doesn't get much attention. For example, it doesn't support floating versions. Multi-targeting and conditional versions aren't well-supported and the Visual Studio integration is poor. Anything non-trivial means adding workarounds and non-intuitive hacks. I wouldn't want to paint Steeltoe into a corner by jumping on this train, so I'm closing this.
