### ISSUE TITLE
System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance

### ISSUE THREAD

**Issue by yassinebennani** [SteeltoeOSS/Steeltoe#1288]
Hello Guys

## Describe the bug
I'm using Steeltoe.Discovery.Eureka last version on dotnet 8 web api service but trying to add service discovery using the default http client builder like this : 

 services.AddServiceDiscovery(options =>
 {
     options.UseEureka();
 });

services.ConfigureHttpClientDefaults(builder =>
{
    builder.AddServiceDiscovery();
});

I need to do it this way.

the service throw an exception on starting process with this exception : 

Unhandled exception. System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[TClient](IServiceProvider s, IHttpClientBuilder builder)

I think the problem is coming from a circular dependency injection not sure about this, could you check please ?

Thank you very much.

**Comment by bart-vmware** [comment]
Hi @yassinebennani, thanks for reporting this.

Yes, you're right. The Eureka client needs an `HttpClient` to access the Eureka server, which is causing a circular dependency. As a result, the currently released Steeltoe versions do not support global service discovery (ie for all HTTP clients).

The good news is that support for it was added in #1280, which will be part of Steeltoe v4.x. The code is feature-complete and fully tested, but I'm still working on an updated sample and documentation.

**Comment by bart-vmware** [comment]
Closing, as the additional work has been completed. An updated sample is available at https://github.com/SteeltoeOSS/Samples/tree/latest/Discovery/src/FortuneTeller. Updated documentation is at https://github.com/SteeltoeOSS/Documentation/tree/v4/api/v4/discovery.
