### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#129]
This Epic will track the work for Steeltoe components built to simplify the development process on Azure.

**Comment by Lechus** [comment]
allow to pass spring password using double underscores instead of colon?
spring__cloud__config__password
Right now the code uses hardcoded COLON_DELIMIT :( 
in private static string GetUserPassElement(string uri, int index)

**Comment by TimHess** [comment]
The core Steeltoe team does not have capacity to work on this effort for the foreseeable future. If this effort is important to you (yes _you_, the reader of this comment) or you can add some context or ideas around what it would look like, please open a new issue to restart the conversation.
