### ISSUE TITLE
Implementation of Eureka LeaseInfo timestamp

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1290]
## Is your feature request related to a problem? Please describe.
The eureka server is not being provided enough information

## Describe the solution you'd like
I would like for atleast the EvictionTimestamp to be set in the LeaseInfo object but ideally all the timestamps are set correctly,

- RegistrationTimestamp = time registration was performed
- LastRenewalTimestamp = When the last renewal occured
- EvictionTimestamp = Last Renewal/Registration  Time Stamp + Duration In seconds
- ServiceUpTimestamp = When the application started

## Describe alternatives you've considered
Tracking it on server side and calculating in the server but db structure can not be easily changed at this point in time.

## Additional context
n/a

**Comment by bart-vmware** [comment]
As far as I'm aware, this isn't possible. These four timestamps are assigned and calculated by the Eureka server. A client can only control the lease duration and renewal interval. Can you elaborate on what you're trying to achieve?

**Comment by thompson-tomo** [comment]
Interesting, that those fields are included in the payload for registration yet I have seen no way for the client to be informed of those values other perhaps an explicit get but then how come it is in the post.

Effectively I have a eureka endpoint running to accept registrations & another endpoint which is used by the client's to discover a list of services & addresses registered in the register.

**Comment by bart-vmware** [comment]
Eureka doesn't use separate models for requests and responses. In Java, both the server and the client use the same codebase. This is because a Eureka server may act as a client in server-to-server communication.

When getting application instances from Eureka, the timestamps are populated. See https://github.com/Netflix/eureka/wiki/Eureka-REST-operations.

**Comment by thompson-tomo** [comment]
Thanks for that info @bart-vmware i had seen that link & is what I had used to determine status codes etc. What I didn't notice was the full schema definition of lease info only having 1 property "evictionDurationInSecs". With that being said the renewal DurationInSecs is being sent which is not in the xsd?

**Comment by bart-vmware** [comment]
The page is outdated. The schema is incomplete and various endpoints are missing there as well. The ultimate truth can be found in the Java sources at https://github.com/Netflix/eureka and https://github.com/spring-cloud/spring-cloud-netflix.

**Comment by thompson-tomo** [comment]
Thanks @bart-vmware
