### ISSUE TITLE
Eureka service registration occurring for the wrong port.

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1291]
## Describe the bug
In my project i have overwritten the kestrel ports by using my app configuration however the eureka registration is still occurring using port 5000 & heartbeat is also using 5000 for default instance Id. Also localhost should not being used for registration.

## Steps to reproduce 
1. Configure kestrel information via app configuration layer (in my case i have a custom provider creating a dictionary). ie Kestrel:Endpoints:Http:Url or Kestrel:Endpoints:HttpsInlineCertStore:Url
2. Configure kestrel via: services.Configure<KestrelServerOptions>(Configuration.GetSection("Kestrel"));
3. Set the registration to talk to the Eureka server
4. Observe server has been registered using port 5000 and not overwritten port

## Expected behavior
The correct port number is used for registration as configured in my app settings and the default is not used. This also flows through for the instance id, which should also not be relying on localhost. If localhost it should resolve it to an actual ip.

## Environment (please complete the following information):
 - Steeltoe Version 3.2.6
 - OS: Windows
 - .NET Version: Net 8

## Screenshots
n/a

## Additional context or links
shortened ELK logs
`
{"@timestamp":"2024-05-06T09:11:24.3512889+10:00","log.level":"Info","message":"Start processing HTTP request PUT http://localhost:90/API/Eureka/v2/apps/WEBMANAGER/localhost:WebManager:5000?status=UP\u0026lastDirtyTimestamp=1714950650018","ecs.version":"8.11.0","log":{"logger":"System.Net.Http.HttpClient.Eureka.LogicalHandler"},"labels":{"HttpMethod":"PUT","Uri":"http://localhost:90/API/Eureka/v2/apps/WEBMANAGER/localhost:WebManager:5000?status=UP\u0026lastDirtyTimestamp=1714950650018","EventName":"RequestPipelineStart"},"agent":{"type":"Elastic.CommonSchema.NLog","version":"8.11.0\u002B20346170742d13e4c2b26ef5c7aaad534970f06b"},"event":{"code":"100","created":"2024-05-06T09:11:24.3512889+10:00","severity":6,"timezone":"AUS Eastern Standard Time"},"metadata":{"EventId":100},"MessageTemplate":"Start processing HTTP request {HttpMethod} {Uri}"}

**Comment by bart-vmware** [comment]
The currently released versions of Steeltoe don't take Kestrel bindings into account. This was fixed in #1280. Until then, as a workaround, explicit ports should be assigned in the Eureka instance configuration.

**Comment by bart-vmware** [comment]
> Is this telling me for a dynamic port to be transmitted I need to be specifying the instance Id & not rely on it being computed?

Yes.

> Also what about it transmitting the address as localhost?

This is useful when running everything locally. Depending on the context (ie Cloud Foundry, Kubernetes), warnings are logged and/or exceptions are thrown when using localhost. If you'd like to use the IP Address, set `PreferIPAddress` to `True` (this relies on another fix included in the PR). Note there are various ways to detect the IP Address, driven by instance configuration.

**Comment by thompson-tomo** [comment]
Great thanks @bart-vmware will workaround it in the meantime until v4 is out & look at it optimising my code.
