### ISSUE TITLE
When eureka registration is occuring the app name is empty in the payload

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1297]
## Describe the bug
The app name in the registration payload is empty

## Steps to reproduce 

1. Have application perform registration with eureka server
2. Observe body of request doesn't have app name set but is a url parameter

## Environment (please complete the following information):
 - Steeltoe Version 3.2.6
 - OS: Windows, 
 - .NET 8

**Comment by bart-vmware** [comment]
I'm afraid this doesn't provide sufficient information to help you. Can you be more specific?

**Comment by thompson-tomo** [comment]
Apologies for that @bart-vmware what I have noticed is that in the payload received by my custom eureka endpoint is that the app name is not set in the payload but the other fields ie app group is.

**Comment by bart-vmware** [comment]
Can you try debugging into Steeltoe to identify why?

**Comment by thompson-tomo** [comment]
Sure thing will do that tomorrow & report back

**Comment by thompson-tomo** [comment]
Interesting findings so far, is that data is correctly being included when the request is being constructed however it is not recieved when binding the body to the same class. What i do notice is the JsonProperty name differs to the property name, making them the same hasn't helped either. 


Next step for me is to make the post using postman and see if it is a de-serialisation problem or a serializatioon problem. Will let you know what i find.

**Comment by bart-vmware** [comment]
I'm closing this issue, as it concerns a serialization issue in custom code, not a bug in Steeltoe. Feel free to open a new issue when you've identified a Steeltoe bug.

**Comment by thompson-tomo** [comment]
found the root cause. I was using newtonsoft for my deserialisation rather than system.text.json hence it didn't respect the JsonPropertyName attributes.
