### ISSUE TITLE
Port information is not transferred as part of body request

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1298]
## Describe the bug
When a eureka registration is occurring the port number is not being set in the payload however the 

## Steps to reproduce 

1. Define your port information in configuration
```
Data.Add("eureka:instance:Port", "90");
Data.Add("eureka:instance:NonSecurePortEnabled", true.ToString());
Data.Add("eureka:instance:SecurePortEnabled", false.ToString());
```
3. Have an application perform a registration with eureka 
4. Observe payload coming in
5. Notice port numbers are not set
6. Observe all other urls are using the port ie info & health address

## Expected behavior
The port number number when configured is provided as part of the payload

## Environment (please complete the following information):
 - Steeltoe Version 3.2.6
 - OS: Windows, 
 - .NET Version Net 8

**Comment by bart-vmware** [comment]
I'm unable to reproduce this with the provided details. Can you try with the FortuneTeller sample at https://github.com/SteeltoeOSS/Samples/blob/main/Discovery/src/FortuneTeller.sln?

**Comment by thompson-tomo** [comment]
Sure will look at that sample tomorrow my time & report back.

**Comment by thompson-tomo** [comment]
so i have noticed a couple of things while debugging. The IsUnsecurePortEnabled flag is not being respected for some reason and always showing as false even when config is different. I have tried using the property: IsUnsecurePortEnabled and what the docs stated but it hasn't helped. I have pushed my reproduct6ion up to my eureka branch of the samples

**Comment by bart-vmware** [comment]
The configuration key is named `NonSecurePortEnabled`, not `IsUnsecurePortEnabled` (see https://docs.steeltoe.io/api/v3/discovery/netflix-eureka.html).

**Comment by thompson-tomo** [comment]
found the root cause. I was using newtonsoft for my deserialisation rather than system.text.json hence it didn't respect the JsonPropertyName attributes. Hence closing
