### ISSUE TITLE
EurekaBase potential for NullReferenceException when no instance id exists

### ISSUE THREAD

**Issue by putridparrot** [SteeltoeOSS/steeltoe#13]
Whilst testing the Eureka Discovery client found that applications were not being returned. Investigation showed that the Eureka app data was missing an instance id for one of the application elements causing a NullReferenceException within Applications.cs, method AddInstanceToVip on the following line (currently line number 147)

instances[info.InstanceId] = info;

**Comment by TimHess** [comment]
@putridparrot Sorry it took so long to get around to looking at this... Do you have any idea what the circumstances were around the InstanceId being `null`?

**Comment by TimHess** [comment]
After some investigation, as near as I can tell this issue should be prevented by https://github.com/SteeltoeOSS/Discovery/pull/54/files so I'm going to close this issue now. Please reopen if it persists

**Comment by putridparrot** [comment]
Sorry for the delay in getting back to you. The issue was spotted on a client's machine, I will try to recreate when I get a chance and see if I can give you better info.
