### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#130]
This Epic will track the work for Steeltoe components built to simplify the development process on Kubernetes.

**Comment by VenkateshSrini** [comment]
Hi,
As a part of this Epic, I would like to see the following To start with
1) Similarly to AddCloudfoundry there should be a method to called AddKubernetes that will add all Kubernetes specific stuff from ConfigMap and Secrets. Alternatively you can separate it out as AddConfigMap and Add Secrets also
2) services.ClonfigureCloudfoundry should be able to load all the backing services from config map and secrets.

**Comment by VenkateshSrini** [comment]
Hi,
Where are we with respect to this enhancement ?

**Comment by VenkateshSrinivasan** [comment]
@jkonicki thank you. Is these 3.0.0.m1 are all going to stable version. Also I'm interested to see what SDK are you using to access the K8s config map and secrets

**Comment by jkonicki** [comment]
3.0.0.M1 is a milestone release for the major 3.0.0 release.  Not recommended for production, more for introducing changes and for the community to begin testing, but many of the features (or parts of the new features) will be in there.  The plan is for several milestone releases before a 3.0.0 GA is released. 
W.R.T. the SDK, that is still being decided.  We are happy to hear from the community.

**Comment by VenkateshSrini** [comment]
Can you please look into this https://kubernetes.io/docs/reference/using-api/client-libraries/. This is already in .NET core and can be consumed readly

**Comment by jkonicki** [comment]
3.0.0-m3 will contain the work from #209, #316, #317, #338

3.0.0-rc1 will contain at least #107 and #358.

**Comment by VenkateshSrini** [comment]
Any idea when a production-ready version is expected that contains all these features. I see that m3 is 100% complete and Rc1 is not showing progress. Is there some way we can see some early bits with samples.

**Comment by jkonicki** [comment]
Hi @VenkateshSrini, The good new is that M3 is available now and samples are coming soon.  The bad news is that during publishing to Nuget.org they blocked our Kubernetes packages at this time and we need to get approval for our naming, so everything but the Kubernetes packages are on NuGet under 3.0.0.M3.   You can access the Kubernetes packages on MyGet.org (https://www.myget.org/feed/Packages/steeltoedev) until we can get them on NuGet.

RC1 is set for early August.

**Comment by VenkateshSrini** [comment]
Is M3 production ready?

**Comment by jkonicki** [comment]
Not recommended.  Here is a list of our release types: https://github.com/SteeltoeOSS/Steeltoe#release-types

**Comment by jkonicki** [comment]
3.0.0-rc1 contains the preview of what will be in released for 3.0.0 GA (expected in mid-August). See roadmap for updates.
