### ISSUE TITLE
Config server URLs appear encoded in logs

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/Steeltoe#1316]
## Describe the bug
The following appears in logs
```
info: Steeltoe.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]
      Fetching configuration from server at: http://127.0.0.1:8888            
info: Steeltoe.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]      
      Config Server returned status: OK invoking path: http%3A%2F%2F127.0.0.1%3A8888
info: Steeltoe.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]                                    
      Located environment name: cpdemo-blue, profiles: Development, labels: (null), version: (null), state: (null)
``` 

Those URLs look encoded

## Steps to reproduce 
1. Add config server using `WebApplicationBuilder` like so `builder.AddConfigServer();`

## Expected behavior
Urls to appear non-url encoded

## Environment (please complete the following information):
 - Steeltoe Version: 4.0.323-alpha
 - Platform: Local
 - OS: Windows
 - .NET Version: 8

**Comment by TimHess** [comment]
This would also be another opportunity to review the level at which Steeltoe is logging... The second and third entries should maybe be debug/trace instead of info
