### ISSUE TITLE
Hystrix- Add support for exporting events and other metrics to other monitoring systems

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#134]
Hystrix dashboard is no longer being supported.  We need to provide the ability to export metrics to external monitoring systems.  
Investigate using OpenTelemetry exporters for Hystrix events along with other metrics.

**Comment by hananiel** [comment]
#264 is closed in favor of subscribing to the existing hystrixmetricspublisher and republishing on eventsource format.
