### ISSUE TITLE
Support for Parameterized Keys in IConfiguration Placeholder Resolver

### ISSUE THREAD

**Issue by alexanderpino** [SteeltoeOSS/Steeltoe#1346]
We propose enhancing the IConfiguration placeholder resolver in Steeltoe to support parameterized keys, such as ${@environment@_database_password}, which would allow dynamic key resolution based on the current environment or other contextual variables. This feature would be particularly beneficial in development scenarios, such as when using appsettings.Development.json or other environment-specific configuration files.

Use Case:
In development and testing environments, it's common to have configuration values that vary significantly between environments. For example, database passwords, connection strings, or API keys might differ between Development, Staging, and Production. Instead of hardcoding these values or manually managing multiple configurations, parameterized keys allow developers to define a single template that adapts based on the environment or other factors:

`"${@environment@_database_password}"`

Example

```
{
  "Development_database_password": "dev_password",
  "Staging_database_password": "staging_password"
}
```

The placeholder ${@environment@_database_password} would resolve to ${Development_database_password} when the environment is Development, and subsequently retrieve the value dev_password.

**Comment by TimHess** [comment]
Hi @alexanderpino,

My initial reaction is that this seems like an anti-pattern, and does not sound like something that should be supported in placeholders. Given the environment-based support that already exists in .NET configuration and additional options like Spring Cloud Config Server, I'm not seeing the value in what you're suggesting
