### ISSUE TITLE
Authorization Header is shown by Actuator trace endpoint

### ISSUE THREAD

**Issue by FrankBirkmann** [SteeltoeOSS/Steeltoe#1351]
Hello

The actuator's trace endpoint shows the Authorization request header. Everybody who can access this endpoint can view basic authentication credentials or can stole bearer token.

In our case, system administrators and developers have access to this endpoint. So if one of this people is malicious he/she can usurp any user's identity.

Is there any way to prevent this?

Regards.

**Comment by bart-vmware** [comment]
Hi @FrankBirkmann, thanks for reporting this.

We should fix that. Until then, you can set `management:endpoints:trace:addRequestHeaders` to `false` in configuration to hide them.
