### ISSUE TITLE
Bring dependent HDRHistogram class into our Hystrix implementation

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#137]
Currently we grab the entire HDRHistogram library (this project no longer appears to be active) in order to use with our Hystrix implementation.  

We should take a look at bring in only the class(es) we need.  This will also get us closer to signed assemblies.

**Comment by TimHess** [comment]
Given Hystrix has moved to maintenance mode, this would not be worth the required effort
