### ISSUE TITLE
Complete (testing) support for Entity Framework 6.3.0

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#140]
Entity Framework 6.3.0 works with .NET Core 3.0, and Steeltoe's Entity Framework Connectors appear to as well, however there is mixed support among the DB driver providers. 

With #94 we add testing SQL Server, but we will need to come back to this once MySQL and Oracle drivers add support to confirm they also work in a .NET Core 3 world

**Comment by jkonicki** [comment]
Open #619 to address oracle support.
