### ISSUE TITLE
Support for multiple configuration fragment loads for an application

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#16]
This request was taken from #29  by @ahusic-clgx

I would very much like a support for multiple configuration fragment loads for an application. What I was thinking about was extending "Pivotal.Extensions.Configuration.ConfigServer.ConfigServerClientSettings" with new property called "Fragments":

public class ConfigServerClientSettings
{
public Collection Fragments{ get; } = new Collection();
}

and then use this collection of strings in "ConfigServerConfigurationProvider" class to load each fragment along side application configuration. It would be app's responsibility to provide fragments it needs (besides its own) to successfully work.

This way, I can load not only app configuration, but any other "shared fragment" application needs.

Thank you very much.

**Comment by dtillman** [comment]
Feel free to provide a PR to address this.   If we understand your need, we believe the config server already provides this kind of functionality.
