### ISSUE TITLE
Unable to activate both CF Actuators and Endpoints together

### ISSUE THREAD

**Issue by alfusinigoj** [SteeltoeOSS/steeltoe#161]
## Describe the bug

Package `steeltoe.management.endpointweb.2.4.0-rc1`

Trying to enable actuators for an ASP.NET full framework application using `ActuatorConfigurator` as below. The problem is that when I set the context to `ActuatorContext.Actuator` I am able to hit the endpoints, say `/actuator/health`, but since I need the Cf Actuators to be enabled for AppsMan, I set the context to `ActuatorContext.ActuatorAndCloudFoundry` where I can see the actuators enabled in AppsMan, but I am getting `401 UnAuthorized` when trying to access the endpoints say `/actuator/health` or `/actuator/info`

```
ActuatorConfigurator.UseCloudFoundryActuators(configuration,
                                                            dynamicLoggerProvider,
                                                            MediaTypeVersion.V1,
                                                            ActuatorContext.ActuatorAndCloudFoundry,
                                                            GetHealthContributors(),
                                                            GlobalConfiguration.Configuration.Services.GetApiExplorer(),
                                                            loggerFactory);
```
## Expected behavior
When context is set to `ActuatorContext.ActuatorAndCloudFoundry`, we should be able to hit the endpoints, together with AppsMan actuators.

## Environment (please complete the following information):
 - Platform: PCF
 - OS: Windows
 - .NET Framework 4.6.2 
 - Steeltoe Version 2.4.0-rc1

**Comment by alfusinigoj** [comment]
@hananiel At this point, do we need to enable /info and /health endpoints explicitly via configuration or they exposed by default. Any samples are welcome. Thanks!

**Comment by hananiel** [comment]
@alfusinigoj  health and info should be exposed by default. Here is a sample:  https://github.com/SteeltoeOSS/Samples/blob/master/Management/src/AspDotNetCore/CloudFoundry/Startup.cs

**Comment by alfusinigoj** [comment]
@hananiel the sample still uses steeltoe 2.4.0-rc1 which has this issue, i will test and let you know. thanks!

**Comment by alfusinigoj** [comment]
@hananiel I still think we will not be able to use cloudfoundry actuators and hypermedia actuators together. Is that true? Because it doesn't seem to work when i used ActuatorContext.ActuatorAndCloudFoundry

**Comment by hananiel** [comment]
It was working before - let me take a look.

**Comment by alfusinigoj** [comment]
ok thanks @hananiel . Here is my code (using in a .NET app.

```
ActuatorConfigurator.UseCloudFoundryActuators(configuration,
                                                            dynamicLoggerProvider,
                                                            MediaTypeVersion.V1,
                                                            ActuatorContext.ActuatorAndCloudFoundry,
                                                            GetHealthContributors(),
                                                            GlobalConfiguration.Configuration.Services.GetApiExplorer(),
                                                            loggerFactory);
```

**Comment by hananiel** [comment]
@alfusinigoj looking at the decompiled code now -- it does not match the latest version of 2.x. 2.4.0 is the latest stable and it was cut on Nov13th. For now myget is the latest version. I'll update the 4.x sample to reflect this once released - which should be soon.

**Comment by jkonicki** [comment]
This fix will be in 2.4.1 set to be released 1/17.

**Comment by alfusinigoj** [comment]
tested with steeltoe dev version, works perfect. thanks!

**Comment by VenkateshSrini** [comment]
@alfusinigoj , can you please provide me a sample where you have got the actuator work. I'm still not able to get it working

**Comment by alfusinigoj** [comment]
@VenkateshSrini here is a working sample https://github.com/alfusinigoj/pivotal_aspnet_bootstrap_cloudfoundry_extensions/tree/master/samples/Actuators/ActuatorSample

**Comment by VenkateshSrini** [comment]
Thanks alfus it  worked
