### ISSUE TITLE
Unable to set a more strict CORS policy

### ISSUE THREAD

**Issue by tutuio** [SteeltoeOSS/steeltoe#166]
Issue on `Steeltoe.Management.CloudFoundry.CloudFoundryApplicationBuilderExtensions` for ASP NET Core 2.2

## Problem description
We need to set a more strict CORS policy and we checked that the method `AddCloudFoundryActuators()` automatically sets the policy to allow all origins. A lot of alternatives were tried, but it doesn't seem possible to overwrite it.

## Proposed solution
Add a configuration parameter to the above method.

## Alternatives considered
The only alternative that was tried and worked was intercepting the response and forcing the desired origins on the headers, but it isn't a elegant way to do it.

Also, we have a concern that this policy is necessary and need to be enforced because it's needed somewhere, so it's good also to have a confirmation if this concern is valid.

**Comment by TimHess** [comment]
Hi @tutuio,

Thanks for filing an issue - you're right, we should provide better control over the CORS policy.  I just pushed a commit that could help, is something like that what you're looking for?

**Comment by tutuio** [comment]
@TimHess 

Yes, that's right. Thank you for the incredibly fast response!
