### ISSUE TITLE
InvalidOperationException thrown when using LoggingActuators

### ISSUE THREAD

**Issue by tom-mckinney** [SteeltoeOSS/steeltoe#167]
## Describe the bug
The following exception is being thrown while use actuators with Steeltoe v2.4.0-rc1:

> Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint Lifetime: Singleton ImplementationType: Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint': Unable to resolve service for type 'Steeltoe.Extensions.Logging.IDynamicLoggerProvider' while attempting to activate 'Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint'.)

## Steps to reproduce 
1. Create a new .NET Core web application (dotnet new webapp)
2. Add the Steeltoe.Management.CloudFoundryCore package (dotnet add package Steeltoe.Management.CloudFoundryCore)
3. Add and use actuators with the AddCloudFoundryActuators() and UseCloudFoundryActuators() methods
4. Run application

## Expected behavior
App should start up. Instead, an `InvalidOperationException` is thrown

## Environment (please complete the following information):
 - OS: Windows 10 x64
 - .NET Core 3.0
 - Steeltoe Version 2.4.0-rc1

## Screenshots
![image](https://user-images.githubusercontent.com/12684522/68612752-3f77c300-048b-11ea-8742-ef81666fdf83.png)
![image](https://user-images.githubusercontent.com/12684522/68612816-61714580-048b-11ea-9ac3-34b448d369a4.png)

**Comment by TimHess** [comment]
Hello @tom-mckinney,

Thanks for the bug report - this issue happens when [dynamic logging hasn't been configured](https://steeltoe.io/logging/docs) in program.cs. 

I did some work last week to streamline this process a bit with new extensions on (Web)HostBuilder that will configured dynamic logging for you. Those extensions will be in the next release, or are available in the dev feed

**Comment by tom-mckinney** [comment]
Hi @TimHess, thanks for the quick reply! In that case, does that make this a duplicate of #122? I'm happy to close this if so.
