### ISSUE TITLE
Steeltoe assemblies do not have strong name information

### ISSUE THREAD

**Issue by sankar1204** [SteeltoeOSS/Steeltoe#18]
When I use nuget package Steeltoe.Extensions.Configuration.CloudFoundry I am getting an error that assembly Steeltoe.Extensions.Configuration.CloudFoundry does not have strong name

`CSC : error CS8002: Referenced assembly 'Steeltoe.Extensions.Configuration.CloudFoundry, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`
Yes its optional to sign the C# assemblies. but
but if assemblies are signed it will be useful for consumers who have to work with projects with strong signature.

**Comment by TimHess** [comment]
Possible tool to aid in this issue: https://github.com/dsplaisted/strongnamer

**Comment by TimHess** [comment]
- HdrHistogram appears to be stable and/or not very actively developed anymore. We can likely publish a strongnamed variant of in its current state and take it as our dependency if we can work around the rest of the issues.
- Strongnamer does not work with assemblies built for `netstandard`. There is a [PR](https://github.com/dsplaisted/strongnamer/pull/31) that has been hanging for a while that is intended to solve the issues, but I couldn't get it to work with the amount of time I had available.

**Comment by bart-vmware** [comment]
Is assembly signing still relevant to pursue for Steeltoe v4, given that since Steeltoe v3 it no longer supports running on .NET Framework?

- From https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md:
  > For the most part, the majority of applications do not need strong-names. Strong-names are left over from previous eras of .NET where [sandboxing](https://en.wikipedia.org/wiki/Sandbox_(computer_security)) needed to differentiate between code that was trusted, versus code that was untrusted. However in recent years, sandboxing via AppDomains, especially to [isolate ASP.NET web applications](https://support.microsoft.com/en-us/help/2698981/asp-net-partial-trust-does-not-guarantee-application-isolation), is no longer guaranteed and is not recommended.
- From https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named:
  > For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.
- From https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming:
  > When .NET developers complain about strong naming, what they're usually complaining about is strict assembly loading. Fortunately, this issue is isolated to .NET Framework. .NET 5+, .NET Core, Xamarin, UWP, and most other .NET implementations don't have strict assembly loading, which is the main downside of strong naming.
  > One important aspect of strong naming is that it's viral: a strong named assembly can only reference other strong named assemblies. If your library isn't strong named, then you have excluded developers who are building an application or library that needs strong naming from using it.
