### ISSUE TITLE
SerilogDynamicProvider.CreateLogger negates Serilog destructuring configurations

### ISSUE THREAD

**Issue by nelsontbrandon** [SteeltoeOSS/steeltoe#182]
## Describe the bug
When using the SerilogDynamicLogger serilog destructuring configurations are ignored.

## Steps to reproduce 
1. Create a project using Steeltoe SerilogDynamicLogger and Destructurama.Attributed
2. Add the UseAttribute destructuring configuration
3. Add an object model containing a destructuring attribute to the log scope to be destructured
4. Write to the log

## Expected behavior
The expected behavior is for properties tagged with [NotLogged] will not show up in the log and [LogMasked] will show up masked.

## Environment (please complete the following information):
 - Platform: Any
 - OS: Any
 - .NET Version .NET Core 2.2.0 & 3.0.0
 - Steeltoe Version 2.3.0 & 2.4.0
 - Any other library versions to note

## Additional context or links
Serilog handles destructuring and building the property tree before writing to any sinks, the current implementation of SerilogDynamicProvider.CreateLogger creates a new logger for each category and sets the global logger as the sink, all of the destructuring happens before serilog pipes to the sink and since the category logger has no destructuring configs it uses the defaults. By the time the properties reach the global logger where your serilog configs are loaded they are already translated to key/value pairs of strings with no additional type information or metadata.

problem is with this line: https://github.com/SteeltoeOSS/steeltoe/blob/master/src/Logging/src/SerilogDynamicLoggerCore/SerilogDynamicProvider.cs#L106

**Comment by jkonicki** [comment]
This did not make it to our 2.4.1 release.  Moving to 2.5.0-RC1 for now.

**Comment by hananiel** [comment]
@nelsontbrandon currently it is not possible to support 3rd party extensions that don't use configuration settings with existing setup. I am curious as to where you are adding the Destructure.UsingAttributes line with the current setup? Are you using the "UseDynamicSerilog" extension? Ideally Destructure.UsingAttributes could be a configuration. I am open to other ideas - if you have a PR that would be great.

**Comment by nelsontbrandon** [comment]
I don't know if my solution is the best one, but it is how I worked around this issue in my project.

Basically the solution I came up with was just preserving the IConfiguration from the constructor and using it to add the Serilog:Destructure configurations to the serilogger before the sink

**Comment by hananiel** [comment]
@nelsontbrandon I have added some tests and slightly changed how configs are applied to subloggers. I wasn't able to make changes to your PR so ended up as a new PR but has all your commits. Thank you so much for your contribution.  Resolved by #235
