### ISSUE TITLE
Configprovider : configuration changes are not reflecting when we delete any setting/feature toggle

### ISSUE THREAD

**Issue by vivekkjain** [SteeltoeOSS/steeltoe#184]
When Steeltoe ConfigServer reads/Load config settings that get stored in the Dictionary of ConfigurationProvider Data (Base abstract class). Now if we change anything any config setting and trigger Reload/Load it will maintain the old data and only add/update the settings in the Dictionary.

## Step to Reproduce
1) Initial Configuration Value:  setting{ "1", "2","3"}
      Data Dictionary will have. below: 
              KEY        | Value
             setting:0 | "1"
             setting:1 | "2"
             setting:2 | "3"
2) Change the configurations like this: setting{ "none"} and reload the configuration while calling config.Reload().
       Now Data Dictionary will have. below: 
              KEY        | Value
             setting:0 | "none"
             setting:1 | "2"
             setting:2 | "3"

## Expected behavior
Data dictionary should have these value on step 2 above:
               KEY        | Value
             setting:0 | "none"

## Environment (please complete the following information):
 - Platform: Cloud Foundry
 - OS: Linux
- ..NET Core 2.2.0 
 - Steeltoe.Extensions.Configuration.ConfigServerBase, Version=2.1.1.0 
 - Any other library versions to note

**Comment by dtillman** [comment]
@vivekkjain : Do you have a sample app we can run to reproduce the problem?

**Comment by vivekkjain** [comment]
@dtillman I don't have any sample application which I can share here. 
Let me know if you have any sample which I can use and modify to replicate this issue.

**Comment by vivekkjain** [comment]
@dtillman  Please find attached ConfigServerConfigurationProviderTest.zip with test project to reproduce this issue.  

[ConfigServerConfigurationProviderTest.zip](https://github.com/SteeltoeOSS/steeltoe/files/3903684/ConfigServerConfigurationProviderTest.zip)

**Comment by dtillman** [comment]
Thanks for the sample test... I've pushed a fix .. and added your unit test .  Should see this appear in the next 2.x release.
Dave

**Comment by vivekkjain** [comment]
@dtillman added review comment please address.

**Comment by vivekkjain** [comment]
@dtillman any update on PR. It’s not yet merged.
