### ISSUE TITLE
After executing a HytrixCommand, the application will not shut down cleanly.  

### ISSUE THREAD

**Issue by brian-bell** [SteeltoeOSS/steeltoe#189]
## Describe the bug
After executing a HytrixCommand, the application will not shut down cleanly.  

## Steps to reproduce 
1. Clone the sample app created by my colleague from here: https://github.com/alan-bentley-dsg/dotnet-hystrix-demo
2. Run the application via command line (dotnet run)
3. Make an API request (curl http://localhost:5000/api/v1/Values/test)
4. Attempt to stop the application using Ctrl-C. A message appears saying "Application is shutting down...". But the app does not actually stop running. 

## Expected behavior
The application should shut down cleanly.

## Environment (please complete the following information):
 - Platform: all (PCF and local dev) 
 - OS: Mac (local), Ubuntu (PCF)
 - .NET Version .NET core 3.0 and 2.2
 - Steeltoe Version 2.4.0

**Comment by dtillman** [comment]
Thanks for the report... We will be making a change to Hystrix in 2.5 to properly shutdown threads that are left running after CTRL-C .. As a work around you should be able to use the code below to shutdown the running threads.

Add something like the following to your startup.cs: 
 
```chsarp
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IApplicationLifetime lifetime)
{
........
 lifetime.ApplicationStopping.Register(() =>
     {
           CumulativeCommandEventCounterStream.Reset();
           CumulativeThreadPoolEventCounterStream.Reset();
           RollingCommandEventCounterStream.Reset();
           RollingThreadPoolEventCounterStream.Reset();
           RollingCollapserEventCounterStream.Reset();
           RollingCollapserEventCounterStream.Reset();
           HealthCountsStream.Reset();
           RollingCollapserBatchSizeDistributionStream.Reset();
           RollingCommandLatencyDistributionStream.Reset();
           RollingCommandUserLatencyDistributionStream.Reset();
           RollingCommandMaxConcurrencyStream.Reset();
           RollingThreadPoolMaxConcurrencyStream.Reset();
      });
......
}
````

Let me know of this doesn't work for you ...
Dave

**Comment by brian-bell** [comment]
@dtillman I verified the workaround solves it for me. Thank you!
