### ISSUE TITLE
Automatically disable color in console logging on PCF

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/steeltoe#196]
In Dynamic Console logging, `if (Platform.IsCloudFoundry)` then configure color to be disabled in the underlying console loggers so that Steeltoe users to not have to set `logging:console:disablecolors` to `true`

**Comment by cesinhaugusto** [comment]
Would overriding the Configure method in ConsoleLoggerOptionsSetup (DynamicLoggingBuilder class) be a good approach to this?

Something like this:
```C#
internal class ConsoleLoggerOptionsSetup : ConfigureFromConfigurationOptions<ConsoleLoggerOptions>
{
    public ConsoleLoggerOptionsSetup(ILoggerProviderConfiguration<ConsoleLoggerProvider> providerConfiguration)
        : base(providerConfiguration.Configuration)
    {
    }

    public override void Configure(ConsoleLoggerOptions options)
    {
        if (Platform.IsCloudFoundry)
        {
            options.DisableColors = true;
        }

        base.Configure(options);
    }
}
`

**Comment by TimHess** [comment]
Yeah @cesinhaugusto, I think that looks like a good place for it

**Comment by cesinhaugusto** [comment]
Great, I'll prepare a pull request for that. I'm just having a little trouble creating a test to assert this.
