### ISSUE TITLE
Log on Error-Level in management endpoints

### ISSUE THREAD

**Issue by Burnaster** [SteeltoeOSS/steeltoe#197]
## Describe the bug
Management endpoints log on error level about "setting contentType to application/json;charset=UTF-8"

## Steps to reproduce 
1. In your Startup class add any management endpoint for example health or info

## Environment (please complete the following information):
 - Platform: Cloud Foundry, Windows
 - OS: Windows, cflinuxfs3
 - .NET Version .NET Core 2.1.802
 - Steeltoe Version 2.4.0

## Additional context or links
I believe the following line in your code is on the wrong log level, which is currently Error but should be Debug

https://github.com/SteeltoeOSS/steeltoe/blob/f0598f7a71307a257dffdad927087d344447c7a5/src/Management/src/EndpointCore/ContentNegotiation/ContentNegotiationExtensions.cs#L37

**Comment by TimHess** [comment]
Hi @Burnaster,

Thanks for the report - I would tend to agree, that is definitely the wrong level for that message! If you'd like to submit a PR against the 2.x branch, we'd be glad to accept it, otherwise we'll get it changed some time before we ship the next release

**Comment by Burnaster** [comment]
Thanks @TimHess 
I created an PR #198

**Comment by TimHess** [comment]
Thank you!
