### ISSUE TITLE
GetStringAsync in synchronization?

### ISSUE THREAD

**Issue by yuezhongxin** [SteeltoeOSS/steeltoe#20]
@TimHess hi, when I use steeltoe in synchronization method, there is an error, sample code:

```cs
[HttpGet]
public IHttpActionResult GetServices()
{
    var data = DiscoveryHttpClientHelper._httpClient.GetStringAsync(GET_SERVICES_URL).Result;
    return Ok(data);
}
```

I read the code of [DiscoveryHttpClientHandlerBase.cs](https://github.com/SteeltoeOSS/Common/blob/dev/src/Steeltoe.Common.Http/Discovery/DiscoveryHttpClientHandlerBase.cs) and found this line:

```cs
return await base.SendAsync(request, cancellationToken);
```

I modified and it work(reference [HttpClient.cs](https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs)):

```cs
var task = base.SendAsync(request, cancellationToken);
return await task.ConfigureAwait(false);
```

**Comment by TimHess** [comment]
This should be addressed via #71
