### ISSUE TITLE
Provide service to service authentication using rotating certificates

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#208]
Use Case:  Provide a way to do service to service authentication utilizing the certificates that are automatically provided (and rotated) by PCF

**Comment by TimHess** [comment]
With this item, a mechanism should be provided for generating certificates during local development. These local certificates should look similar to certificates provided by PCF, such that authorization policies requiring the apps be in the same space and/or org work locally as well as on the platform.

**Comment by TimHess** [comment]
Blocked on Linux on PCF by [this issue](https://github.com/dotnet/runtime/issues/32558)

Potential workaround could be to duplicate most of the functionality provided by `Microsoft.AspNetCore.Authentication.Certificate` using BouncyCastle for all certificate components

**Comment by TimHess** [comment]
Relevant links for easy retrieval in case this work gets mothballed:

- https://docs.pivotal.io/platform/2-8/security/pcf-infrastructure/certificates-index.html
- https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html

**Comment by jkonicki** [comment]
Waiting on Docs

**Comment by jkonicki** [comment]
Closing now.  Docs to come in #297
