### ISSUE TITLE
HttpClient Should static  can't Creating a new HttpClient instance per request.

### ISSUE THREAD

**Issue by liningit** [SteeltoeOSS/Steeltoe#21]
HttpClient Should static  can't Creating a new HttpClient instance per request.

see
https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client

_Originally posted by @liningit in https://github.com/SteeltoeOSS/Common/issues/8#issuecomment-471146807_

**Comment by jkonicki** [comment]
We will look into this during the 3.x timeline

**Comment by TimHess** [comment]
`HttpClientHelper.GetHttpClient` appears to be used in the following:

- ConfigServerBase
- EurekaBase
- Authentication.CloudFoundryCore
- EndpointBase (Cloud Foundry Security)
- CredHubBase

[This SO question/answer](https://stackoverflow.com/a/52622851/761468) may help for cases where we can't rely on DI to provide instances of HttpClient

**Comment by liningit** [comment]
> `HttpClientHelper.GetHttpClient` appears to be used in the following:
> 
> * ConfigServerBase
> * EurekaBase
> * Authentication.CloudFoundryCore
> * EndpointBase (Cloud Foundry Security)
> * CredHubBase
> 
> [This SO question/answer](https://stackoverflow.com/a/52622851/761468) may help for cases where we can't rely on DI to provide instances of HttpClient

you can use HttpClientFactory or use static
if you new many HttpClient then Consume a lot of TCP

**Comment by liningit** [comment]
HttpClient.Dispose() not release TCP
