### ISSUE TITLE
Load services that are configured in Kubernetes

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#210]
Add the ability to load service bindings that are configured in Kubernetes environments with [Kubernetes Service Bindings](https://github.com/servicebinding/spec)

**Comment by TimHess** [comment]
In my view, this feature is effectively providing support for working with [Service Catalog](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/) and various [open service broker api implementations](https://github.com/openservicebrokerapi/servicebroker/blob/master/gettingStarted.md#example-service-brokers) but I'm not clear on how in-demand this functionality is. 

If this feature is important to you (the reader of this message) please give a thumbs up or comment on this issue with how you'd like to use it or if you've got other related ideas

**Comment by VenkateshSrini** [comment]
I code in .NET core. I would like to load the default settings from appSetting.json and as we are doing that in cloud foundry I would like to override the environment-specific backing services from Config map and secrets.

**Comment by TimHess** [comment]
@VenkateshSrini that (general) scenario should be supported by #304, provided you use the same config keys for values you want to override and add your config providers in the desired order.

This feature expects there to be some alternative format for providing service credentials, where a simple config key-based environment override isn't directly applicable

**Comment by VenkateshSrini** [comment]
@TimHess ,
Thanks for the clarification. Since the description is so lean, I thought it was linked the issue to 304.

**Comment by TimHess** [comment]
More relevant links:

- https://github.com/buildpacks/spec/blob/master/extensions/bindings.md
- https://github.com/spring-projects/spring-boot/issues/21322
- https://github.com/dsyer/spring-boot-bindings

**Comment by VenkateshSrini** [comment]
All this is true if we use buildpacks to create our container even in case of k8s. But that will not be the case when a more descriptive and more flexible Docker file approach is available. This is just my take

**Comment by TimHess** [comment]
Support for Cloud Native Bindings (in 3.2 and 4.0/`main`) and a significant overhaul to connectors (in `main`) have been completed. Further effort in this area, such as support for "more flexible Docker file approach" would need further definition. If desired, please open a new issue with more information about what should be supported
