### ISSUE TITLE
Add Prometheus support to our OpenCensus implementation

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/steeltoe#211]
Use Case: Add support for prometheus endpoint to allow prometheus capable applications to pull data from it.

PCF Metrics Registrar will look for this endpoint and pull data into PCF Metrics. This should also support other Prometheus services.

**Comment by hananiel** [comment]
resolved by #215

**Comment by jkonicki** [comment]
See documentation for this feature here: https://steeltoe.io/docs/7-management/13-%252fprometheus
