### ISSUE TITLE
PropertyPlaceholderHelper does not resolve ${x.y} placeholders 

### ISSUE THREAD

**Issue by jclagache** [SteeltoeOSS/steeltoe#22]
Related to #5 

[This repository](https://github.com/jclagache/SteeltoeSamples) helps to reproduce : 

- [spring-config-server-sample](https://github.com/jclagache/SteeltoeSamples/tree/master/Configuration/spring-config-server-sample)
is a spring boot config server with [native](https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#_file_system_backend) profile that embeds [the configuration](https://github.com/jclagache/SteeltoeSamples/tree/master/Configuration/spring-config-server-sample/src/main/resources/config).
 - [ClientConfigServerTest](https://github.com/jclagache/SteeltoeSamples/tree/master/Configuration/ClientConfigServerTest) is a test program that adds this config server to its ConfigurationBuilder with differents profiles and use the ```AddPlaceholderResolver``` extension.

Conclusion : 
```${foo:bar}``` is resolved
```${foo[bar]}``` is resolved
```${foo.bar}``` is not resolved

**Comment by TheBritz** [comment]
I created a fix to this in the PropertyPlaceholderHelper class; just a simple, single-line replacement of Spring '.' characters for ':' characters before resolution - should I wait for this to be assigned to me or go ahead and submit a PR?

```csharp
int startIndex = property.IndexOf(PREFIX);
while (startIndex != -1)
{
    int endIndex = FindEndIndex(result, startIndex);
    if (endIndex != -1)
    {
        string placeholder = result.Substring(startIndex + PREFIX.Length, endIndex);

        // Replace Spring delimiters ('.') with MS-friendly delimiters (':') so Spring placeholders can also be resolved
        placeholder = placeholder.Replace(".", ":");

        string originalPlaceholder = placeholder;

        if (!visitedPlaceHolders.Add(originalPlaceholder))
        {
            throw new ArgumentException($"Circular placeholder reference '{originalPlaceholder}' in property definitions");
        }

        // Recursive invocation, parsing placeholders contained in the placeholder key.
        placeholder = ParseStringValue(placeholder, config, visitedPlaceHolders);
```

Not sure if this might introduce problems or not... may be an issue if MS, ':' delimited configuration properties can legally contain '.' as part of the configuration value name.
