### ISSUE TITLE
ConfigServerConfigurationProvider and CloundFoundryConfigurationProvider are not added as configuration providers to ConfigurationRoot

### ISSUE THREAD

**Issue by antonpopov** [SteeltoeOSS/steeltoe#221]
## Describe the bug
**ConfigServerConfigurationProvider** and **CloundFoundryConfigurationProvider** are not added as configuration providers to **ConfigurationRoot** when using Steeltoe's extension method for **IConfigurationBuilder**.
I was able to get my settings from our Spring Cloud Config Server on application boot, but when I called IConfigurationRoot.Reload(), to reload the settings no request was made to the config server.
I had **no problem** when I tried the alternative approach - using the AddConfigServer() extension method for the **IWebHostBuilder**.

In addition when using the Steeltoe's **Refresh actuator** (which I saw is also using **IConfigurationRoot.Reload()**) to reload application settings, no request is made to the Spring Cloud Config server.

1. Install **Steeltoe.Extensions.Configuration.ConfigServerCore**.
2. Configure Steeltoe by using AddConfigServer() extension method for **IConfigurationBuilder**.
3. Inject **IConfiguration** into a controller.
4. Check the listed providers.

## Expected behavior
**ConfigServerConfigurationProvider** and **CloundFoundryConfigurationProvider** to be part of the provider collection.

## Environment:
 - OS: Windows
 - .NET Version: .NET Core 3.1.0
 - Steeltoe Version: 2.4.0, 2.4.1

## Screenshots
![image](https://user-images.githubusercontent.com/5244097/72680118-e21d7500-3abe-11ea-82b1-4d5513e3c413.png)

--------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/5244097/72680105-bbf7d500-3abe-11ea-88a9-22541b638731.png)

--------------------------------------------------------------------------------------------------------

When using the extension method for **IWebHostBuilder**:
![image](https://user-images.githubusercontent.com/5244097/72680149-37f21d00-3abf-11ea-8048-d2a3d53b415b.png)

**Comment by TimHess** [comment]
Configuration should be built inside program.cs, not startup.cs. The results should be as expected if you use it inside `IHostBuilder.ConfigureAppConfiguration`.

**Comment by antonpopov** [comment]
As advised I moved the configuration to `IHostBuilder.ConfigureAppConfiguration`. The providers are still not listed when **IConfiguration** is injected into **Startup.cs** constructor:
![image](https://user-images.githubusercontent.com/5244097/72812130-9e1aa380-3c69-11ea-8761-ca52de8444c4.png)

![image](https://user-images.githubusercontent.com/5244097/72812297-ed60d400-3c69-11ea-8a54-c8ac1555210b.png)

I need the configuration to work as showed here on Steeltoe's doc page:
![image](https://user-images.githubusercontent.com/5244097/72812619-80017300-3c6a-11ea-98a5-021cd9ca538c.png)
We use custom **ConfigurationBuilder** implementation which need to be instantiated.

**Comment by TimHess** [comment]
Why do you need a custom `ConfigurationBuilder`? 

I don't think that you can just set `context.Configuration` that way. I think ASP.NET will set that property later when it uses the config builder, and also provides that other instance to the DI container.

**Comment by antonpopov** [comment]
Out team implemented a custom 'DecryptionConfigurationBuilder' which handles some sensitive information we have as configuration. Possibly using the **AddConfigServer()** extension method for **IConfigurationBuilder** will allow us to continue using it.
I agree with you, perhaps the `context.Configuration` is overwritten later by ASP.NET Core. Tim I'm just trying to configure out project to use Steeltoe following [both the examples](https://github.com/SteeltoeOSS/Documentation/blob/master/docs/2-configuration/config-server-provider.md#add-configuration-provider) in your documentation. Would you please point me to a working example using this particular one:
```csharp
using Steeltoe.Extensions.Configuration;
...

var builder = new ConfigurationBuilder()
    .SetBasePath(env.ContentRootPath)
    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true)
    .AddConfigServer(env)
    .AddEnvironmentVariables();

var config = builder.Build();
...
```

**Comment by TimHess** [comment]
Well, if you simply must have a custom ConfigurationBuilder, you should probably either register it under a different interface (if you want to retrieve it via DI), otherwise (going back to your original example) you should be able to retrieve it via Startup.Configuration instead of relying on the injected version.

Something else to consider would be changing your configuration decryption to work as a config provider instead... Steeltoe's Placeholder config provider might be conceptually similar to what you're trying to accomplish

**Comment by antonpopov** [comment]
I think I misunderstood the documentation. I got it working as you suggested. I'm posting screens if anyone comes across a similar problem:
**Program.cs**
![image](https://user-images.githubusercontent.com/5244097/72871017-6e63ae00-3cf2-11ea-8b42-1d18425110ab.png)

**Startup.cs**
![image](https://user-images.githubusercontent.com/5244097/72871044-80dde780-3cf2-11ea-9481-6cd21558b14c.png)

Custom config provider sounds like a good idea. I'll go for it. Thank you for the time and support and since my problem obviously is not a bug I'm closing the issue.
