### ISSUE TITLE
Async Health() method in IHealthContributor interface

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#23]
Note: Moved from Connectors repository

Origin: User feedback
Issue 1: Is there a reason Steeltoe doesn't have an async Health() method within this Steeltoe.Common.HealthChecks.IHealthContributor interface?

Issue 2: Any reason a noun like Health() was chosen as a method name vs. something like AssessHealth()? Could we look into changing this?

**Comment by ahaleiii** [comment]
Does Steeltoe block the thread when running `Health()` on IHealthContributor? Does this mean that there should not be implementations of IHealthContributor for external network calls?

**Comment by hananiel** [comment]
No it doesn’t block. The middleware is invoked asynchronously.

**Comment by hananiel** [comment]
Steeltoe supports the IHealthContributor to mirror the Spring Boot [interfaces](https://github.com/spring-projects/spring-boot/blob/v2.3.1.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/HealthIndicator.java). 
Steeltoe also supports the Microsoft IHealthCheck [interfaces](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.healthchecks.ihealthcheck?view=dotnet-plat-ext-3.1).

We will create a sample using IHealthCheck, continue supporting IHealthContributor for teams already using them and change the healthCheck middleware to check health in parallel.

**Comment by hananiel** [comment]
resolved by #371

**Comment by jkonicki** [comment]
PR #364 added parallel processing for existing Steeltoe Health checks.
