### ISSUE TITLE
Not able to get configuration from  SCS 3.0 config server

### ISSUE THREAD

**Issue by deepuvikraman** [SteeltoeOSS/steeltoe#234]
We are currently migrating our PCF config server from SCS2 to SCS3.0 and experiencing some issue with retrieving configuration.
With old version of config server (p-config-server), we were able to get configuration without specifying the configuration spring: cloud:config:label in our application.
But with SCS3.0 versin of config server (p.config-server), we are getting a http 404 (NotFound) error if the spring: cloud:config:label is not specified. If this configuration is set to 'dev' (the name of the backing git repo branch name), the configuration is retrieved successfully.
Is this an expected behavior?
When we are creating an instance of config server in PCF, we are specifying the label for config server.

**Comment by jkonicki** [comment]
Hello @deepuvikraman.  What version of Steeltoe are you using?  This was resolved in 2.3.0.  See #92 for more info.

**Comment by jkonicki** [comment]
Reopen if you still have the issue.  Thank you.

**Comment by deepuvikraman** [comment]
I am using 2.4.1 version of steeltoe. The above mentioned issue #92 was related to not able to retrieve configuration for config server (p.config-server). The issue that I am facing is, I need to have a configuration spring: cloud:config:label in my appsettings.json file. This was not required with SCS2.0

**Comment by deepuvikraman** [comment]
> Reopen if you still have the issue. Thank you.

I am not able to reopen the issue. Can you reopen it please

**Comment by jkonicki** [comment]
Thank you.  We are taking a closer look.

**Comment by hananiel** [comment]
@deepuvikraman looks like there was an issue with scs 3.0 fixed as of https://docs.pivotal.io/spring-cloud-services/3-0/release-notes.html#3-0-11. It sounds to me like its not automatically defaulting when label is not available. Can you check what version of SCS is running in your environment. Here is a way to be able to check: https://community.pivotal.io/s/article/How-to-Check-Spring-Cloud-Services-Instance-version. 
If your environment is not up to the latest, then path forward is to update to latest or later than 3.0.11. The next best workaround is what you have already found.

**Comment by jkonicki** [comment]
Closing as resolved.  Reopen if needed.  Thank you.
