### ISSUE TITLE
Resilience4j support

### ISSUE THREAD

**Issue by DOMZE** [SteeltoeOSS/steeltoe#24]
I've come accross Netflix Hystrix and Netflix has put it on maintenance mode.

Hystrix is known for its circuit breaking capabilities, but it doesn't stack well with other concerns such as
Rate limiting
Bulkheading
Automatic retrying (sync and async)
Response caching
Timeout handling

They point to Resilience4j which should be used for new project and which is better to play with (stack on) the concerns above.

Are you guys planning to support this, i.e. make a lib for that?

**Comment by TimHess** [comment]
We don't currently have plans for anything with regard to resilience4j, but have been kicking around the ida that we should see if there's a way to connect somehow with [Polly](https://github.com/App-vNext/Polly) even prior to #25

**Comment by jkonicki** [comment]
Closing this in favor of #280
