### ISSUE TITLE
Reuse polly

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Steeltoe#25]
Hi Team,
Is there a way where SteelToe can leverage the complete set of Polly capability. This library is far matured. What I would suggest is a capability to create a wrapper for this project which will allow it to work easily with CF. Polly is a very battle tested old library in .NET. During Lift and shift we see this library used extensively. So this will reduce the migration effort for us.

**Comment by jkonicki** [comment]
Related to #280

**Comment by TimHess** [comment]
I don't think Steeltoe is going to be providing an abstraction over Polly, especially now that we've put Hystrix into maintenance mode. A metrics implementation for Polly would belong in the Polly project.
