### ISSUE TITLE
How do you add a custom ServiceInfoFactory?

### ISSUE THREAD

**Issue by tillig** [SteeltoeOSS/Steeltoe#26]
We are using the Vault service broker for PCF and I'm trying to follow the pattern in this repo for a nice, robust connection mechanism.

The roadblock I'm hitting is that most of these start with something like:

```csharp
config.GetSingletonServiceInfo<RedisServiceInfo>();
```

This invokes, a roundabout way, [the `CloudFoundryServiceInfoCreator.BuildServiceInfoFactories` method](https://github.com/SteeltoeOSS/Connectors/blob/master/src/Steeltoe.CloudFoundry.Connector/CloudFoundryServiceInfoCreator.cs#L117), which scans _only the `Steeltoe.CloudFoundry.Connector` assembly_ for service info factory implementations.

This `ServiceInfo` that gets created is later used in [extension methods like this one for Redis](https://github.com/SteeltoeOSS/Connectors/blob/master/src/Steeltoe.CloudFoundry.Connector.Redis/RedisCacheServiceCollectionExtensions.cs#L45) as the "base configuration" for a connection, left to be enhanced by additional client configuration.

Problem is, I can't figure out how to get my service info factory into play to be used when service info is getting retrieved. The set of service info objects gets cached with individual `CloudFoundryServiceInfoCreator` instances so while I could create some sort of additional extension method that might work like this...

```csharp
config
  .AddVaultServiceInfo()
  .GetSingletonServiceInfo<VaultServiceInfo>();
```

...having to remember to add that call every time isn't so cool.

If there's _not_ already a solution for this, I could imagine one possible solution being the `ServiceInfo` implementation getting marked with an attribute indicating its factory type and having the `CloudFoundryServiceInfoCreator` discover factories in that way rather than (or in addition to?) assembly scanning.

However, I didn't see anything in the samples repo showing this so I figured I'd ask.

**Comment by jkonicki** [comment]
Need to keep in mind during the 3.x refactoring.
