### ISSUE TITLE
Cloud Foundry Service Options not mapping Credentials 

### ISSUE THREAD

**Issue by mjnorman** [SteeltoeOSS/steeltoe#262]
## Describe the bug
When attempting to use the Cloud Foundry service mapper, my credentials are not being mapped.  I get the base service properties,  but the credentials are all null.

## Steps to reproduce 
My classes look like the below--
```
     public class SquidProxyOptions : AbstractServiceOptions
     {
         public SquidProxyOptions() { }
         
         public SquidProxyCredentials Credentials { get; set; }
 
     }
 
     public class SquidProxyCredentials
     {
         public string Host { get; set; }
         public string Password { get; set; }
         public int Port { get; set; }
         public string Uri { get; set; }
         public string Username { get; set; }
 
 
     }
```
It's just coming through with the base service members:
```
   "Services": {
     "c-proxy": [
       {
         "Name": "my-proxy",
         "Label": "c-proxy",
         "Tags": [
           "proxy"
         ],
         "Plan": "shared",
         "Credentials": {
           "host": {},
           "password": {},
           "port": {},
           "uri": {},
           "username": {}
         }
       }
     ]
   }
```
## Expected behavior
I should be able to access the credentials section.

## Environment (please complete the following information):
 - Platform: Cloud Foundry
 - OS: [e.g. Windows, Linux, Mac OSX]
 - .NET Version 3.1
 - Steeltoe Version 2.4.2 and also tried 2.4.0
 - Any other library versions to note

**Comment by mjnorman** [comment]
Added repro, https://github.com/mjnorman/steeltoetest

**Comment by jkonicki** [comment]
Discussion in Slack: https://steeltoeteam.slack.com/archives/C0ENXS0M8/p1584239497027100

**Comment by hananiel** [comment]
Basically works as expected:  
 1.  services.ConfigureCloudFoundryServices (with s) is the correct overload and the expected string is the name of the service(not config key)
2. using either overload IOptionsSnapshot requires you to get the Option by name (of the service).
