### ISSUE TITLE
Missing IntelliSense comments

### ISSUE THREAD

**Issue by Tandis5** [SteeltoeOSS/Steeltoe#27]
There is a lot of missing IntelliSense comments in the Connectors code, especially in the EFCore and ConnectorBase projects.

**Comment by TimHess** [comment]
@Tandis5, I know you started working on this item - were you able to make some progress?

**Comment by jkonicki** [comment]
Hello @Tandis5, 

Were you still planning on creating a PR for this work?  We would like to get this issue closed out and into our next release.  

Thanks for looking into it.

**Comment by Tandis5** [comment]
@jkonicki I’m sorry but I never really got any time to work on this.
