### ISSUE TITLE
Update metrics to use Opentelemetry Beta

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#276]
Currently opentelemetry [opentelemetry-dotnet)](https://github.com/open-telemetry/opentelemetry-dotnet)  is in alpha. #274 Takes us part of the way. As they publish updates, we need to update our implementation of metrics.

**Comment by jkonicki** [comment]
From Discussion: Waiting on beta release of OpenTelemetry to update this ticket.

**Comment by TimHess** [comment]
replaced by #604
