### ISSUE TITLE
Investigate: enhancement of Circuitbreaker functionality

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#280]
Currently, we use our implementation of Hystrix for circuit breaker capabilities.  We need to take a look at if supporting and enhancing our implementation is the best way forward or contribute some of the functionality of our implementation to another project. 

Some areas for enhancement include (as mentioned in #24 and #25 ):
Rate limiting
Bulkheading
Automatic retrying (sync and async)
Response caching
Timeout handling

**Comment by TimHess** [comment]
With the decision to move Hystrix to maintenance mode, I don't see further enhancements happening here.
