### ISSUE TITLE
Refactoring of connectors

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#285]
Originally connectors were built for CF.  With our move to a more platform agnostic approach to Steeltoe, we need to take a look at how we can better abstract out connector functionality for usage on other platforms.  

related ticket: #26

**Comment by TimHess** [comment]
Consider better compatibility with [`GetConnectionString` ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationextensions.getconnectionstring?view=dotnet-plat-ext-3.1)
