### ISSUE TITLE
Inconsistent accessor

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/steeltoe#29]
https://github.com/SteeltoeOSS/Connectors/blob/035cf250e8c2b22722142b8cf349e791f9bd952f/src/Steeltoe.CloudFoundry.ConnectorBase/DocumentDB/MongoDb/MongoDbConnectorOptions.cs#L45

The access modifier seems inconsistent, allowing values to be set ONLY through config but not through code. Why not allow the dictionary to just be deserialized as is?

**Comment by TimHess** [comment]
So just make `Options` public? I don't remember why I did it this way, it may take some time to dig far enough in to find a reason... Are you directly interacting with the connector options classes?

**Comment by macsux** [comment]
Don't remember where I was doing it, I think some kind of manual bootstrap
test before I realized it was impossible without using config file
