### ISSUE TITLE
LoadBalancerDelegatingHandler can't be instantiated

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#293]
## Describe the bug
Applications using `Hostbuilder.AddServiceDiscovery()` fail to start with exception:
```
InvalidOperationException: No constructor for type 'Steeltoe.Common.Http.LoadBalancer.LoadBalancerDelegatingHandler' can be instantiated using services from the service container and default values.
```

**Comment by TimHess** [comment]
`LoadBalancerHttpClientBuilderExtensions.AddLoadBalancer<T>()` has this line, which causes the problem and serves no apparent purpose:
```
httpClientBuilder.Services.TryAddTransient<LoadBalancerDelegatingHandler>();
```

**Comment by zh6335901** [comment]
I am new to steeltoe. What way can replace use `Hostbuilder.AddServiceDiscovery()` in 2.4.3?

**Comment by TimHess** [comment]
@zh6335901 the workaround for the bug in HostBuilder.AddServiceDiscovery in 2.4.3 is to call `services.AddDiscoveryClient(Configuration)` and `app.UseDiscoveryClient()` in `startup.cs`

**Comment by zh6335901** [comment]
@TimHess  Thanks:)
