### ISSUE TITLE
Kubernetes adding config map and secrets

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Steeltoe#296]
## Is your feature request related to a problem? Please describe.
I have cloned the code for 3.0.0.m-2. I still do not see the way of adding config map and secrets with simple extension methods like what we have CF. 

## Describe the solution you'd like
I would like to see methods like UseKubernetesHosting, services.ConfigureCloudFoundrySettings() to read from K8s secret or config map. What ever the Config map definitions are I expect to see them injected via appSettings.Json and as long as they map we can read those application level settings

**Comment by jkonicki** [comment]
Transferred issue from `Samples` repo to `Steeltoe` repo as this request pertains to the core codebase not the samples.

**Comment by jkonicki** [comment]
This work directly reflects the work being done in #209.

**Comment by VenkateshSrini** [comment]
Can I know when the initial merge to the master repo will be available for us to review?

**Comment by jkonicki** [comment]
@VenkateshSrini 
Yes.  The best way would be to subscribe to #209 for ticket updates.  Once that work is complete it will be added to our myget.org steeltoedev feed.  Feel free to reach out with any other questions.

I am closing this ticket in favor of #209.
