### ISSUE TITLE
Failing Health checks may cause app to be restarted

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#3]
On some platforms (for example, PCF) when the health actuator is configured as the application's health check endpoint and a non-200 status code is returned on an HTTP health check, the application is restarted.

Steeltoe should provide an optional means of indicating that a dependency is down, without failing the entire healthcheck failing

**Comment by macsux** [comment]
This has been addressed on Java Spring side via Health Groups. See https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#health-groups

Would be good to see Steeltoe add this feature

**Comment by billkable** [comment]
In Spring Boot 2.3.x, Liveness and Readiness checks will be first class citizens (building on Health Groups).  It would be nice to see a similar roadmap.

See [Liveness and Readiness Probes with Spring Boot](https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot)

**Comment by jkonicki** [comment]
Thanks @billkable.  Those are already captured in #316 #317 - They will likely be on the roadmap for Steeltoe 3.1.0.

**Comment by TimHess** [comment]
Health groups are included as of #371
