### ISSUE TITLE
PostgreSQL connector support for 'Search Path'

### ISSUE THREAD

**Issue by jpmorin** [SteeltoeOSS/steeltoe#30]
PostgreSQL connector does not supports `Search Path` when the connectionString is built from a cloud foundry binding. Note that adding `Search Path=myschema;` dirrectly to the connectionString  when working locally works fine.

**This works fine locally, but is overridden when deploy in cloud foundry.**
```json
{
  "postgres": {
    "client": {
      "ConnectionString": "User ID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;Search Path=mySchema"
    }
  }
}
```

**I would suggest adding support for `postgres:client:searchpath`.**
```json
{
  "postgres": {
    "client": {
      "ConnectionString": "User ID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;",
      "SearchPath": "mySchema"
    }
  }
}
```

**Comment by jkonicki** [comment]
Work was done during the repo restructure:  https://github.com/SteeltoeOSS/Connectors/pull/53

**Comment by jkonicki** [comment]
@jpmorin Thanks again.  We ended up bringing in the code from your PR.  You should see it in our 2.3.0 release.
