### ISSUE TITLE
When using basic authentication the username:password is logged in clear text.

### ISSUE THREAD

**Issue by HerrLiljegren** [SteeltoeOSS/steeltoe#31]
If you configure Eureka to use basic authentication and then configure Steeltoe Discoveryclient to use the URL https://username:password@localhost/eureka/ then the credentials-part will be logged in clear text.

e.g
[EurekaHttpClient.cs#L226](https://github.com/SteeltoeOSS/steeltoe/blob/c623ad18ac23651ee6178fd3a2dc113af4bc0f9f/src/Discovery/src/EurekaBase/Transport/EurekaHttpClient.cs#L226)
[EurekaHttpClient.cs#L893](https://github.com/SteeltoeOSS/steeltoe/blob/c623ad18ac23651ee6178fd3a2dc113af4bc0f9f/src/Discovery/src/EurekaBase/Transport/EurekaHttpClient.cs#L893)
[EurekaHttpClient.cs#L913](https://github.com/SteeltoeOSS/steeltoe/blob/c623ad18ac23651ee6178fd3a2dc113af4bc0f9f/src/Discovery/src/EurekaBase/Transport/EurekaHttpClient.cs#L913)

**Comment by TimHess** [comment]
Tiny oops, looks like we both forgot to include a [close keyword](https://help.github.com/en/articles/closing-issues-using-keywords) in the issue linking from the pr.

Thanks again for your contribution!
