### ISSUE TITLE
K8s - Add readiness endpoint for use with readiness probe in containers

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#317]
`readiness` probes are used to know when a container is ready to start accepting traffic. A Pod is considered ready when all of its containers are ready. One use of this signal is to control which Pods are used as backends for Services. When a Pod is not ready, it is removed from Service load balancers.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by seif** [comment]
Just stumbled upon this while checking out what you are building for 3.0 and was curious how this will work and interact with discovery as we've had similar issue on our internal discovery solution. Ended up hooking the announcement to discovery to an event triggered in the ready controller once it passes.

Is there a case where we could announce to discovery but have not passed ready and so not routable? Or is the assumption that if readiness is enabled then we are using native k8s discovery?

Thanks for great work btw

**Comment by jkonicki** [comment]
@seif Thanks for reaching out.  
We are still working through the design and implementation for this piece, so at this time very little discussion about details.  Once we are active on this issue, we will be better able to answer some questions here.   
If you have suggestions or use cases you would like us to consider, please add them here. 
Thanks.
