### ISSUE TITLE
investigate versioning alternatives

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Steeltoe#349]
The current versioning implementation is functional but is daunting to the uninitiated.

A recent chatroom discussion mentioned a couple of alternatives:
* use build ID from build system (in case of DevOps, `BUILD_BUILDNUMBER`)
* [GitVersion](https://gitversion.net/docs/)

This is by no means an exhaustive list.  Additional ideas can be added as comments.

The team needs pro/con assessment of alternatives vs the _status quo_ in order to determine what, if any actions, should be taken.

**Comment by macsux** [comment]
I recommend https://github.com/dotnet/Nerdbank.GitVersioning over GitVersion. It is more robust as it doesn't depend on branches / tags to calculate version number. GitVerison suffers from a problem that if you delete a branch or tag that was used in versioning strategy, the whole numbering will shift. NBGV instead uses this info only during version "split", such as a new release branch being cut, to calculate major/minor and then persists this into a `version.json` file.
