### ISSUE TITLE
Credentials in URIs need to be encoded

### ISSUE THREAD

**Issue by christianerbsmehl** [SteeltoeOSS/Steeltoe#365]
## Describe the bug
When using Eureka, Steeltoe Connector creates ServiceInfos for all bound services, such as Databases or similar. When this happens, it creates an uri from the supplied credentials of the bound service (using `scheme`, `host`, `port`, `username`, `password`, `path` and `query` values). If the supplied credentials include a username and/or password with special charcaters (like the hash sign `#` in my case), an exception is thrown in `Steeltoe.Connector.Services.UriInfo.MakeUri(...)`, because special characters are not encoded, which causes the following exception:

`System.UriFormatException: 'Invalid URI: Invalid port specified.'`

This is somewhat misleading, because the port supplied is correct.

## Steps to reproduce 
1. Bind a service which supplies credentials containing a hash sign
2. Call `services.AddDiscoveryClient(Configuration)` in `Startup.cs`

Or simply call
```csharp
new UriBuilder()
{
    Scheme = "http",
    Host = "foo.bar",
    Port = 1337,
    UserName = "SomeUser",
    Password = "P4SSW0RD#",
    Path = "/baz"
}.Uri;
```

## Expected behavior
No exception should be thrown, credentials should be urlencoded before passing them to the `UriBuilder` instance.

## Environment (please complete the following information):
 - Platform: CloudFoundry
 - OS: Linux
 - .NET Version .NET Core 3.1.4
 - Steeltoe Version 2.4.4

## Screenshots
n/a

## Additional context or links
n/a

**Comment by jkonicki** [comment]
In addition to the expected behavior above, there should also be a better/more accurate error message from the URI validation.
