### ISSUE TITLE
Consider adding Swagger support for our endpoints

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#380]
#119 started to look into this, but only endpoint routing was added to actuators. See that ticket for additional details.

Look into whether we should make additional changes to fully support Swagger.  

This implementation might help: https://github.com/aspnet/AspLabs/blob/master/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.Swagger/Internal/GrpcHttpApiDescriptionProvider.cs

**Comment by TimHess** [comment]
Closing due to lack of interest. If you would like to see this supported, please respond to this issue
