### ISSUE TITLE
NullReference exception while running Management endpoints sample

### ISSUE THREAD

**Issue by kishoreallwynraj** [SteeltoeOSS/steeltoe#39]
Hi,

I ran the "CloudFoundryWeb" sample below
https://github.com/SteeltoeOSS/Samples/tree/dev/Management/src/AspDotNet4/CloudFoundryWeb

The sample run as it is in my laptop. But when i comment out below line in ManagementConfig.cs and enabled only the ActuatorConfigurator.UseHealthActuator i am getting NullReference exception while accessing the Health endpoint.

ActuatorConfigurator.UseCloudFoundryActuators(configuration, dynamicLogger, GetHealthContributors(configuration), apiExplorer, loggerFactory);

The sample runs only when i also uncomment the "ActuatorConfigurator.UseCloudFoundrySecurity" line as well. My intention is to run this health endpoint in an API which is already running in a VM in OnPrem environment. So having a line in codebase which refers to CF security would be confusing and also maynot go well with internal security team. Please clarify if there is a workaround to use this Health endpoint without all the added CF related complexities.

Regards
Kishore Allwynraj

**Comment by kishoreallwynraj** [comment]
Below the exception stacktrace

[NullReferenceException: Object reference not set to an instance of an object.]
   Steeltoe.Management.Endpoint.Handler.<IsAccessAllowed>d__5.MoveNext() +80
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Steeltoe.Management.Endpoint.Module.<FilterAndPreProcessRequest>d__6.MoveNext() +439
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +63
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +483
   System.Web.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0() +24
   System.Web.StepInvoker.Invoke(Action executionStep) +100
   System.Web.<>c__DisplayClass4_0.<Invoke>b__0() +17
   Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.OnExecuteRequestStep(HttpContextBase context, Action step) +64
   System.Web.<>c__DisplayClass284_0.<OnExecuteRequestStep>b__0(Action nextStepAction) +55
   System.Web.StepInvoker.Invoke(Action executionStep) +84
   System.Web.<>c__DisplayClass4_0.<Invoke>b__0() +17
   Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.OnExecuteRequestStep(HttpContextBase context, Action step) +64
   System.Web.<>c__DisplayClass284_0.<OnExecuteRequestStep>b__0(Action nextStepAction) +55
   System.Web.StepInvoker.Invoke(Action executionStep) +84
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +100
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

**Comment by kishoreallwynraj** [comment]
After looking through the code in file, it looks like the ISecurityService is going as NULL and it is getting initialized in the samples code only if we also enable the "ActuatorConfigurator.UseCloudFoundrySecurity" line.

https://github.com/SteeltoeOSS/Management/blob/dev/src/Steeltoe.Management.EndpointWeb/Security/SecurityServiceExtension.cs

**Comment by hananiel** [comment]
@kishoreallwynraj I tried to reproduce this issue but then noticed that the sample was not updated to 2.2. We made a lot of changes and bug fixes in that release , so can you checkout the latest version of the sample you refer to from master and confirm this is still an issue for you?

**Comment by kishoreallwynraj** [comment]
@hananiel  I downloaded the samples from master branch and tried again. I did not get the NullReference exception. But instead getting only 404 error when i comment out "ActuatorConfigurator.UseCloudFoundryActuators" and enabled only "ActuatorConfigurator.UseHealthActuator" in the ManagementConfig.cs file.

In appsettings.json file i replaced the "management" section with below snippet. This setting was working with the previous version the same way as i mentioned in the issue description. Is there any other changes required to be done?.

"management": {
    "endpoints": {
      "health": {
        "showdetails": "always",
        "claim": {
          "type": "health_actuator",
          "value": "see_details"
        }
      }
    }
  }

**Comment by kishoreallwynraj** [comment]
I was getting below error as well when i ran the project.

**Could not find a part of the path 'D:\SteeltoeSamples-master\Management\src\AspDotNet4\CloudFoundryWeb\bin\roslyn\csc.exe'**

I had to add the below snippet in the "CloudFoundryWeb.csproj" file to resolve this.

`<Target Name="CopyRoslynFiles" AfterTargets="AfterBuild" Condition="!$(Disable_CopyWebApplication) And '$(OutDir)' != '$(OutputPath)'">
    <ItemGroup>
      <RoslynFiles Include="$(CscToolPath)\*" />
    </ItemGroup>
    <MakeDir Directories="$(WebProjectOutputDir)\bin\roslyn" />
    <Copy SourceFiles="@(RoslynFiles)" DestinationFolder="$(WebProjectOutputDir)\bin\roslyn" SkipUnchangedFiles="true" Retries="$(CopyRetryCount)" RetryDelayMilliseconds="$(CopyRetryDelayMilliseconds)" />
</Target>`

**Comment by hananiel** [comment]
For your 404 issue, your path needs to be set - previously, if it is not set, it would respond at /health, now it defaults **`/actuator/health`**. For your configuration, by default `health.showdetails` is set to  `always`. When it is always the`claim type` and `value` will not be checked so it will not be verified. So as far as health, your settings can be empty. This is described in the docs here:  [GlobalSettings](https://steeltoe.io/docs/steeltoe-management/#1-2-2-configure-global-settings) and [Hypermedia](https://steeltoe.io/docs/steeltoe-management/#1-2-3-hypermedia) . 
      The difficulty when not using either the Cloudfoundy Actuator or the Hypermedia Actuator, is that the context path actuator may not be live, but the context path still exists. You can still override the context path by forcing the **management:endpoints:path: "/"**
     For the compiler error, which version of visual studio are you using? I have not had this issue with vs2017.

**Comment by kishoreallwynraj** [comment]
@hananiel i am able to hit the health endpoint now. Since our service will be hosted onprem and this /health endpoint will be mainly used by our load balancer to check on application health, i am checking if there is a simple way to enforce authentication by using basic auth credentials. The documentation for "whenauthorized" shows only a claim. I assume it is for a CF setup. Is there an option to enable basic auth for this health endpoint?

**Comment by hananiel** [comment]
@kishoreallwynraj we originally had plans to support this but followed he spring boot actuators direction with removing security concerns from actuators code. The when authorized is not for a CF setup. It is for any mechanism that can provide a claim in the security context. So in other words, if your application already provides some security middleware, just enter the claims it would have into the claimtype and value (it also supports roles). Or add a special middleware for routes to "/actuator/health" that will enforce basic auth and add the appropriate claim.

**Comment by hananiel** [comment]
@kishoreallwynraj it sounds like you have a resolution. Feel free to open if you have any more questions.
