### ISSUE TITLE
Steeltoe.Security.DataProtection.RedisCore still depends on earlier StackExchange Redis library

### ISSUE THREAD

**Issue by crudlyf** [SteeltoeOSS/steeltoe#40]
Hi,

I'm trying to upgrade the Redis client library in my projects to the latest version. I found that **Steeltoe.Security.DataProtection.RedisCore** still references `Microsoft.AspNetCore.DataProtection.Redis (>= 0.3.0)` instead of the new `Microsoft.AspNetCore.DataProtection.StackExchangeRedis` library. 

Is this in the pipeline?

**Comment by TimHess** [comment]
This was floating around in the back of my mind, but wasn't in the backlog until now. I see that `Microsoft.AspNetCore.DataProtection.Redis` has been unlisted from nuget.org, so that definitely raises the priority on making the change. I'll take a look
