### ISSUE TITLE
Steeltoe.CloudFoundry.ConnectorCore 2.4.4 or 3.0.0-m1 does not work with MySqlConnector >= 1.0.0

### ISSUE THREAD

**Issue by TravisBoatman** [SteeltoeOSS/Steeltoe#402]
When using MySqlConnector version >= 1.0.0 ConnectorCore cannot find the service.

`Value cannot be null. (Parameter 'serviceType')`

![image](https://user-images.githubusercontent.com/16249995/89963464-84887b80-dbfc-11ea-939c-e8783bd811d7.png)

This is probably due to a namespace change in version 1.0.0.
See here: https://github.com/mysql-net/MySqlConnector/issues/824

## Steps to reproduce 
1. Create a new ASP.NET Core API project
2. Add Steeltoe.CloudFoundry.ConnectorCore 2.4.4 or 3.0.0-m1
3. Add MySqlConnector 1.0.0
4. Run

## Expected behavior
Should find the service without error.

## Environment:
 - Platform: PCF/Local
 - OS: Linux/Windows
 - .NET Version: 3.1
 - Steeltoe Version: 2.4.4 or 3.0.0-m1
 - MySqlConnector Version: 1.0.0

## Additional notes
Reverting back to any MySqlConnector version lower than 1.0.0 will restore functionality.

**Comment by jkonicki** [comment]
Thank you @TravisBoatman
