### ISSUE TITLE
RFC: Create a Steeltoe Reference application

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#410]
Build a reference application that utilizes many/most of the components our libraries provide.  

This will allow the team and users a way to observe our recommended way to utilize our features, testing of new features and a central area for referencing our features.  

We would love to get ideas for this application from the community.

**Comment by TimHess** [comment]
A possible candidate would be a compatible port of [PetClinic](https://github.com/spring-projects/spring-petclinic)

**Comment by jkonicki** [comment]
Work is being done here: https://github.com/steeltoeoss-incubator/spring-petclinic-microservices/issues/3
