### ISSUE TITLE
Missing Management extension methods for IWebHostBuilder

### ISSUE THREAD

**Issue by tscrypter** [SteeltoeOSS/Steeltoe#413]
## Describe the bug
There are no management extension methods for `IWebHostBuilder` to for adding the endpoints.

## Steps to reproduce 
1. clone the `https://github.com/SteeltoeOSS/Samples` repository
2. attempt to configure the the HealthCheckActuator.

## Expected behavior
I expected to be able to call `WebHost.CreateDefaultBuilder(args).AddHealthCheckActuator()` in `Program.cs`

## Environment (please complete the following information):
 - Platform: Kubernetes 
 - OS: Linux
 - .NET Version: .NET Core 3.1.102 
 - Steeltoe Version: 3.0.0-3468

## Screenshots
![Screenshot from 2020-08-17 15-52-38](https://user-images.githubusercontent.com/413144/90438295-bb014300-e0a1-11ea-892f-4de3154dcd9b.png)

## Additional Notes
There is a workaround by switching from `IWebHostBuilder` to `IHostBuilder` (I provide an example in the screenshot).

**Comment by tscrypter** [comment]
With some initial investigation, this goes a bit down a rabbit hole because the `AddCloudFoundryActuators()` and `AddLoggingActuator()` automatically configure the `DynamicConsoleLogger`, which doesn't have extension methods for `IWebHostBuilder`. Given that Web Host only remains available for backwards compatibility ([according to the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1)) and there is a workaround, how much effort should be put into this? Getting all other actuators without the logging one is pretty straight forward.

**Comment by TimHess** [comment]
I could be wrong, but I think we might have lost some of these in the move to 3.0... I was in this general area anyway and a basic copy/paste went pretty far and IMO seems worthwhile to include. I don't know that I'd want to go further, but feel free to take a look at #414

**Comment by tscrypter** [comment]
I just pulled in that branch and confirmed it resolves this issue. Since it was pretty straight forward, this will work.
