### ISSUE TITLE
Handle passthrough of error messages on IIS

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#418]
## Problem Summary:
* There was a change to Steeltoe quite some time ago to comply with the Spring spec for returning HTTP 503 in cases of HealthStatus.DOWN or HealthStatus.OUT_OF_SERVICE. 

* For 500 series errors, however, HWC is configured by default to substitute a canned message for the http response content - so, instead of getting back any failed health checks, the monitor just gets a 503 with “Service Not Available” instead of the healthcheck JSON. 

* Thus, in the default case, health monitoring with HWC and Steeltoe no longer works. People who were using AppsManager and were able to see rich information in their health checks might not be able to see this information anymore, and will likely not know the cause. 

## Exploration:
We validated in our exploration that HWC’s setting for 500 errors can be changed via a Web.config file in an application. 
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.webServer>
        <httpErrors existingResponse="PassThrough"/>
    </system.webServer>
</configuration>
```
This would be achieved by setting httpErrors existingResponse to “PassThrough”.

We explored changing this setting globally in HWC, but this would change the default error page behavior of every existing app using default settings for HWC. We decided this was a risk.

The defaults we have right now in HWC match the IIS defaults, so we’re more inclined to keep these default settings as they are.

Note: The Web API will return the correct HTTP response code regardless of this setting. It’s just the content of the API response that is different. 

## Possible Resolution:
* Add a note to the Steeltoe documentation about this, warning users of this issue and noting that a customer can change this setting in their application Web.config file.  A further solution would be for Steeltoe to check for this setting programmatically and fail with a message to correct this in the Web.config file.
* We could change add a property like so:
``` 
if (!config["management:endpoints:health:alwaysOK"])
{
    context.Response.StatusCode = ((HealthEndpoint)_endpoint).GetStatusCode(result);
} 
```
This would be a new config switch we'd add that would allow you to override our behavior of setting the status code so that it always returns 200 or at least the actual health response wouldn't affect what code we return... there could still be other unhandled exceptions making it not a 200.
This could be acceptable since the health response is generally more important than the status code.

Note: This same issue would exist for any K8s users using Microsoft dotnet/framework/aspnet images and apps with Steeltoe.

**Comment by emgrig** [comment]
Do you want the change in Management -> EndpointBase -> EndpointMiddleware or Management -> EndpointCore ->HealthEndpointMiddleware ? 
This is my first time of looking into the project.

**Comment by TimHess** [comment]
503 return status should also be overridable for other things like cf security response
