### ISSUE TITLE
User defined services for Mongo DB

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Steeltoe#422]
Hi,
I'm using a MongoDB connector in my application. We need to create a user defined service for MongoDB instead of using CF version of mongo DB broker. The ask here is how should I define the user defined service. As per the documentation i see this
```
{
  "MongoDb": {
    "Client": {
     "ConnectionString":"xxxxx"
      }
    }
  }
}
```
If I were to use cups, how should this be provided. I guess it should be with in VCAP:services etc:-. Can you please provide me with format of cups service for MongoDB. If the document can be updated with this details then it will be very helpful

**Comment by TimHess** [comment]
Hi @VenkateshSrini,

Most Connectors can read from a Uri property that has been formatted appropriately, please see [this example](https://github.com/SteeltoeOSS/Steeltoe/commit/1271da6586e17bee00e7865a1a66b2616e42effe#diff-cf28c4f817787f97c49a20914cca570d) for MongoDB

**Comment by VenkateshSrini** [comment]
Hi,
This did not work for me, my VCAP services part is as below
`{
   "vcap:services:{
       "user-provided":[
         {
          "label": "user-provided",
          "instance_name":"service1"
          "name": "servcie1"
         "binding": null,
         "credentials":{
                 "bucketname":"aa"
                 "password":"bb"
              }
         },
        {
          "label": "user-provided",
          "instance_name":"service2"
         "name": "service2"
         "credentials":{
              "uri":"mongodb://"
        }
        ]
     }
}
`
In the start up I have give 'services.AddMongoClient(Configuration)'
I get that the database name in mongourl is not set. That means the mongourl is getting set as null at the injection point. I think when adding the mongo client I need tell some how that the I should tell that steel toe needs to use service 2 to get the DB connection parameters. Please help

**Comment by TimHess** [comment]
Steeltoe usually identifies the type of service by label, tag, or scheme. In this case, the scheme `mongodb://` in the uri is all you need for Steeltoe to select the binding, but if there's no connection info inside that Uri then it won't work.

Please see [the test binding](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Connectors/test/ConnectorCore.Test/MongoDbTestHelpers.cs#L12) and corresponding [test](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Connectors/test/ConnectorCore.Test/MongoDbProviderServiceCollectionExtensionsTest.cs#L185) to see how the parts of the uri get mapped into `MongoClient`

**Comment by VenkateshSrini** [comment]
@TimHess ,
I tested in XUnit test it is working. When providing in appSettings.json for loacl development. Should I add vcap:services or not ?

**Comment by VenkateshSrini** [comment]
@TimHess,

The code that is not woking is attached here with. Coul you please help me on this regard
[SampleWebApi.zip](https://github.com/SteeltoeOSS/Steeltoe/files/5262851/SampleWebApi.zip)

**Comment by TimHess** [comment]
For local development, since host and port appear to be defaults, you should be able to use this:
```
{
  "MongoDb": {
    "Client": {
      "Database": "KnowledgeDB"
    }
  }
}
```

If you want to use the `vcap:services` so that you're more closely matching what the app will see when it is deployed, you'd need to be sure to add a reference to `Steeltoe.Connector.CloudFoundry` and set some value in an environment variable named `VCAP_APPLICATION`... Which might be more of a hassle than it's worth since you need to do it in a way that won't interfere when you eventually deploy to CF.

A third option is to remove vcap from the config hierarchy in your config file, like this:
```
  "services": {
    "user-provided": [
      {
        "name": "mongodb-user-provided-service",
        "instance_name": "mongodb-user-provided-service",
        "binding_name": null,
        "credentials": {
          "uri": "mongodb://localhost:27017/KnowledgeDB"
        },
        "syslog_drain_url": "",
        "volume_mounts": [],
        "label": "user-provided",
        "tags": []
      },
      {
        "name": "Other-user-provided-service",
        "instance_name": "Other-user-provided-service",
        "binding_name": null,
        "credentials": {
          "Host": "www.dell/EMCServer",
          "bucket": "mybucket"
        },
        "syslog_drain_url": "",
        "volume_mounts": [],
        "label": "user-provided",
        "tags": []
      }
    ]
  }
```

**Comment by VenkateshSrini** [comment]
> For local development, since host and port appear to be defaults, you should be able to use this:
> 
> ```
> {
>   "MongoDb": {
>     "Client": {
>       "Database": "KnowledgeDB"
>     }
>   }
> }
> ```
> 
> If you want to use the `vcap:services` so that you're more closely matching what the app will see when it is deployed, you'd need to be sure to add a reference to `Steeltoe.Connector.CloudFoundry` and set some value in an environment variable named `VCAP_APPLICATION`... Which might be more of a hassle than it's worth since you need to do it in a way that won't interfere when you eventually deploy to CF.
> 
> A third option is to remove vcap from the config hierarchy in your config file, like this:
> 
> ```
>   "services": {
>     "user-provided": [
>       {
>         "name": "mongodb-user-provided-service",
>         "instance_name": "mongodb-user-provided-service",
>         "binding_name": null,
>         "credentials": {
>           "uri": "mongodb://localhost:27017/KnowledgeDB"
>         },
>         "syslog_drain_url": "",
>         "volume_mounts": [],
>         "label": "user-provided",
>         "tags": []
>       },
>       {
>         "name": "Other-user-provided-service",
>         "instance_name": "Other-user-provided-service",
>         "binding_name": null,
>         "credentials": {
>           "Host": "www.dell/EMCServer",
>           "bucket": "mybucket"
>         },
>         "syslog_drain_url": "",
>         "volume_mounts": [],
>         "label": "user-provided",
>         "tags": []
>       }
>     ]
>   }
> ```

if I remove vCap then.This has lead to another problem in which I'm unable to get the CloudFoundryServiceOptions.GetServiceList() method is returning Count as Zero as a result we are unable to access other services

**Comment by VenkateshSrini** [comment]
There is also another problem here. I was thought of combining the approach 1 for approach 3. where I will keep the mongod outside the vcap services while the the other service as vcap. But that again did not work. I get an error cannot create mongodbclient

**Comment by TimHess** [comment]
`MongoDb:Client:Database` should be only the database name (KnowledgeDB), not the full connection string.

Oh, that's how you're using `ConfigureCloudFoundryOptions`... Yeah, Connectors aren't currently built on (or really connected with) those options, so they're effectively two different ways to access the same configuration. For that method of access you would need to keep `vcap` in the config hierarchy

**Comment by TimHess** [comment]
For quicker turnaround on checking your settings, you can use this code to get at what Steeltoe is determining the connection string to be

```
var cmgr = new ConnectionStringManager(Configuration);
var cinfo = cmgr.Get<MongoDbConnectionInfo>();
var connectionstring = cinfo.ConnectionString;
```

**Comment by VenkateshSrinivasan** [comment]
> `MongoDb:Client:Database` should be only the database name (KnowledgeDB), not the full connection string.
> 
> Oh, that's how you're using `ConfigureCloudFoundryOptions`... Yeah, Connectors aren't currently built on (or really connected with) those options, so they're effectively two different ways to access the same configuration. For that method of access you would need to keep `vcap` in the config hierarchy
`MongoDb:Client:Database` >  how will we give connection string of we were to give only database name. I need to give other aspect also. The point is full connection string if we remove the VCAP. This gets into trouble when VCAP services is given. I think In connector code where it says HasCloudFoundry flag is set when VCAP is given. Hence Mongo Db connector starts looking for instance in user provided services

I have gone ahead created my own extension method as below 
`public static class ServiceExtension
    {
        public static IServiceCollection AddMongoDBClient(this IServiceCollection services, IConfiguration configuration,
            string vcapServiceName )
        {
            //var cloudfoundryServiceOptions = new CloudFoundryServicesOptions();
            //configuration.GetSection("vcap:services").Bind(cloudfoundryServiceOptions);
            var serviceProvider = services.BuildServiceProvider();
            var cloudfoundryServiceOptions = serviceProvider.GetRequiredService<IOptions<CloudFoundryServicesOptions>>();

            var credential = cloudfoundryServiceOptions.Value?.GetServicesList()
                             .FirstOrDefault(services => services.Name.CompareTo(vcapServiceName) == 0)
                             .Credentials;
            var mongoUrl = new MongoUrl(credential["uri"].Value);
            var mongoClient = new MongoClient(mongoUrl);
            services.AddSingleton<MongoUrl>(mongoUrl);
            services.AddSingleton<IMongoClient>(mongoClient);
            return services;
        }
    }`
if you could bridge in connector then it will be great. I ask to adopt method signature. You could still use the refelection approach to avoid adding the MongoDb.Driver to reference list

**Comment by VenkateshSrini** [comment]
MongoDb:Client:Database > how will we give connection string if we were to give only database name. I need to give other aspect also. The point is full connection string works if we remove the VCAP:service section itself from appSettings.json. This gets into trouble when VCAP:services is given. I think In connector code where it says HasCloudFoundry flag is set when VCAP is given. Hence Mongo Db connector starts looking for instance in user provided services

I have gone ahead created my own extension method as below

```
public static class ServiceExtension
    {
        public static IServiceCollection AddMongoDBClient(this IServiceCollection services, IConfiguration configuration,
            string vcapServiceName )
        {
            //var cloudfoundryServiceOptions = new CloudFoundryServicesOptions();
            //configuration.GetSection("vcap:services").Bind(cloudfoundryServiceOptions);
            var serviceProvider = services.BuildServiceProvider();
            var cloudfoundryServiceOptions = serviceProvider.GetRequiredService<IOptions<CloudFoundryServicesOptions>>();

            var credential = cloudfoundryServiceOptions.Value?.GetServicesList()
                             .FirstOrDefault(services => services.Name.CompareTo(vcapServiceName) == 0)
                             .Credentials;
            var mongoUrl = new MongoUrl(credential["uri"].Value);
            var mongoClient = new MongoClient(mongoUrl);
            services.AddSingleton<MongoUrl>(mongoUrl);
            services.AddSingleton<IMongoClient>(mongoClient);
            return services;
        }
    }

```
if you could bridge in connector then it will be great. I ask to adopt method signature. You could still use the refelection approach to avoid adding the MongoDb.Driver to reference list

**Comment by TimHess** [comment]
Steeltoe builds connection strings by calling `ToString()` on the ConnectorOptions class. See [MongoDbConnectorOptions](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Connectors/src/ConnectorBase/MongoDb/MongoDbConnectorOptions.cs#L54) ~ you'll notice default values for server and port that match what's expected for running locally, so all that should be needed is the db name.

We already have a [very similar signature](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Connectors/src/ConnectorCore/MongoDbProviderServiceCollectionExtensions.cs#L54). We had wanted to look at a broader refactoring of Connectors for 3.0 that could have been based on something like`CloudFoundryServicesOptions` but there wasn't enough time to include it, and I'd be hesitant to add a one-off that is built so differently from the rest of what's in Connectors.
