### ISSUE TITLE
services.AddDistributedRedisCache(config) throw exception after updated to Steeltoe latest nuget packages

### ISSUE THREAD

**Issue by pnguyen535** [SteeltoeOSS/Steeltoe#427]
Hi, 

After updated nuget package, the Redis cache failed to initiate. Am I missing somthing? 

Unable to load one or more of the requested types.
Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by jkonicki** [comment]
Hello, those interfaces have been moved to the Steeltoe.Common.Abstractions nuget package.

**Comment by TimHess** [comment]
@pnguyen535 can you share more info about your app? Target framework, other Steeltoe packages (and versions)?

That error shouldn't happen as we should be having direct references in the packages to tie that all together for you

**Comment by pnguyen535** [comment]
my project is target .net core 3.1, below is my project references

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <CodeAnalysisRuleSet>../AllRulesDefault.ruleset</CodeAnalysisRuleSet>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="CorrelationId" Version="3.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="9.2.0" />
    <PackageReference Include="IdentityModel" Version="4.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OData.Versioning.ApiExplorer" Version="4.1.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="3.1.7" />
    <PackageReference Include="Steeltoe.CloudFoundry.Connector.EFCore" Version="2.4.4" />
    <PackageReference Include="Steeltoe.CloudFoundry.ConnectorCore" Version="2.4.4" />
    <PackageReference Include="Steeltoe.Discovery.ClientCore" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Management.CloudFoundryCore" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Security.Authentication.CloudFoundryCore" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.5.1" />
    <PackageReference Include="ZNetCS.AspNetCore.Authentication.Basic" Version="4.0.0" />
  </ItemGroup>
</Project>

**Comment by TimHess** [comment]
Was this project upgraded from netcoreapp2.something? There are some references in there that don't look right for a 3.1 app... 

Regardless, these are likely the cause of the problem you're seeing:
```
<PackageReference Include="Steeltoe.CloudFoundry.Connector.EFCore" Version="2.4.4" />
<PackageReference Include="Steeltoe.CloudFoundry.ConnectorCore" Version="2.4.4" />
```

Try changing to this:
```
<PackageReference Include="Steeltoe.Connector.ConnectorCore" Version="3.0.0" />
<PackageReference Include="Steeltoe.Connector.CloudFoundry" Version="3.0.0" />
<PackageReference Include="Steeltoe.Connector.EFCore" Version="3.0.0" />
```

**Comment by pnguyen535** [comment]
Thanks Tim,

It solved my problem.
