### ISSUE TITLE
Eureka registration payload is serialized incorrectly

### ISSUE THREAD

**Issue by Hawxy** [SteeltoeOSS/Steeltoe#435]
## Describe the bug
Whilst validating that Eureka does work with gRPC (#433), I came across an issue.

gRPC requires https for HTTP/2 negotiation, so I configured eureka within my service to enable https and disable http:

```json
  "Eureka": {
    "Instance": {
      "appName": "admin",
      "nonSecurePortEnabled": false,
      "securePortEnabled": true,
      "securePort": 5001,
      "hostName": "localhost"
    } 
  },
```
This results in a payload that looks like this:
```json
"port":{"@enabled":"False","$":80},"securePort":{"@enabled":"True","$":5001},
```
However, when you inspect Eureka's service metadata, you'll find SecurePort to be false.
```xml
<port enabled="false">80</port>
<securePort enabled="false">5001</securePort>
```

This then goes on to resolve within the calling service and implode when the request is done over http instead of https:
```
[17:48:58 INF] Start processing HTTP request POST https://admin/user.UserService/GetUser
[17:48:58 DBG] LookupService(https://admin/user.UserService/GetUser)
[17:48:58 DBG] GetInstances returning: Instance[InstanceId=***:unknown:80,HostName=localhost,IpAddr=****,Status=UP,IsUnsecurePortEnabled=False,Port=80,IsSecurePortEnabled=False,SecurePort=5001,VipAddress=admin,SecureVipAddress=admin,ActionType=ADDED]
[17:48:58 INF] Sending HTTP request POST http://localhost/user.UserService/GetUser
[17:48:58 DBG] Sending message.
[17:48:58 INF] Received HTTP response after 99.0835ms - NotFound
[17:48:58 INF] End processing HTTP request after 113.969ms - NotFound
[17:48:58 INF] Call failed with gRPC error status. Status code: 'Internal', Message: 'Bad gRPC response. Response protocol downgraded to HTTP/1.1.'.
```

## Expected behavior
It seems Eureka expects the lowercase form of `"@enabled":"true"` or `"@enabled": true` instead of `"@enabled":"True"`

As a side note, it would probably be useful if the library warned the developer if a request is attempted on a service with both `IsUnsecurePortEnabled` and `IsSecurePortEnabled` set to `false` instead of silently defaulting to http.

## Environment (please complete the following information):
 - Platform: local
 - OS: Windows
 - .NET Version: .NET Core 3.1 & 5 Preview 8
 - Steeltoe Version: 3.0.0
 - spring-cloud-starter-netflix-eureka-server 2.2.5-RELEASE

**Comment by TimHess** [comment]
This is probably a relatively new bug, thanks for digging deep enough to get what looks like a pretty good definition of the problem - I probably introduced it when I switched our Eureka code from using Newtonsoft to System.Text.Json... and it's probably [this line]( https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Discovery/src/Eureka/Transport/JsonInstanceInfo.cs#L108), but I haven't verified anything here yet

**Comment by TimHess** [comment]
We [have](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Discovery/test/Eureka.Test/Transport/JsonApplicationTest.cs#L26) [tests](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Discovery/test/Eureka.Test/Transport/JsonInstanceInfoTest.cs#L25) [with](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Discovery/test/Eureka.Test/Transport/JsonApplicationsRootTest.cs#L31) mocked response data showing this value to be a string... might just be old test data, but that's likely why there is a string converter in there right now

**Comment by Hawxy** [comment]
> might just be old test data

I did some manual testing against the registration endpoint and as far as I can tell, Eureka will accept both the boolean and string form of `true`. It just doesn't accept `"True"` with a capital `T` that's currently being sent. The converter calls `boolean.ToString()` which outputs with a capital, so I assume removing the converter would fix the issue.

**Comment by TimHess** [comment]
Removing the converter broke the tests... adding `.ToLower()` when we write a `bool` seems to fix registration without breaking tests

We should plan to add more tests for this (de)serialization area in #384
