### ISSUE TITLE
Consider making the heap dump collection logic work on Linux for .NET Core 3

### ISSUE THREAD

**Issue by cshung** [SteeltoeOSS/steeltoe#44]
In .NET Core 3, it is possible to collect a heap dump of a process running on Linux using [`Microsoft.Diagnostics.Tools.RuntimeClient.GenerateCoreDump`](https://github.com/dotnet/diagnostics/blob/03c882f585f599df1a419f00ad3bdfc29e87a116/src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticHelpers.cs#L34).

**Comment by jkonicki** [comment]
Duplicate of #100
