### ISSUE TITLE
Steeltoe (Wavefront) Observability support

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#444]
Currently metrics integration with Steeltoe uses Telegraf which can be configured to receive prometheus format metrics and translated to a wavefront format which wavefront proxy can then relay. This induces too much delay from events to observation - There is batching of metrics with prometheus and then again at telegraf and once again at wavefront proxy. The ideal solution would use a WavefrontReporter built for Steeltoe Metrics or OpenTelemetry like the one Wavefront team built for [AppMetrics](https://github.com/wavefrontHQ/wavefront-appmetrics-sdk-csharp/blob/master/src/Wavefront.AppMetrics.SDK.CSharp/App.Metrics.Reporting.Wavefront/WavefrontReporter.cs)

Additionally the Spring boot starter for [Wavefront](https://github.com/wavefrontHQ/wavefront-spring-boot) has features like a wavefront actuator that takes them to the dashboard.

**Comment by hananiel** [comment]
Resolved partially by #831 Still need Wavefront actuator

**Comment by TimHess** [comment]
@hananiel can you please create a separate issue for the actuator? I'm going to close this one in 3.2
