### ISSUE TITLE
Null Reference in EurekaInstanceOptions.ApplyConfigUrls

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#465]
Running an application in docker using default ports and the autoregister from aspnetcore urls feature could result in a null reference exception somewhere in [here](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Discovery/src/Eureka/EurekaInstanceOptions.cs#L123)

**Comment by jkonicki** [comment]
Issue resolved in 2.x branch and brought into 3.x

**Comment by fjvela** [comment]
Hello!

Same problem in 3.0.1 but not in 3.0.0.

**Comment by TimHess** [comment]
@fjvela yeah, sorry about that - there was an extra character that slipped into the string replacement and wasn't caught in the tests... That is fixed for 3.0.2 (pre-release builds are available on the [Steeltoe dev feed ](https://www.myget.org/F/steeltoedev/api/v3/index.json)
