### ISSUE TITLE
My  custom health check does not get reported in the PCF dash board when using the SteelToe3.0

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Steeltoe#471]
## Describe the bug
I have custom health check that implements `IHealthContributor` interface.

### In Program.cs
```
public static IHostBuilder CreateHostBuilder(string[] args)=>
Host.CreateDefaultBuilder(args)
.ConfigureWebHostBuilder(webBuilder=>{
webBuilder.UseDefaultServiceProvider(configure=>configure.ValidateScopes=false)
.UseCloudHosting()
.AddCloudFoundryConfiguration()
.AddCloudFoundryActuator()
.UseStartup<Startup>();
});
```
### In startup,cs
```
public void ConfigureServices(IServiceCollection service)
{
services.AddCloudFoundryActutator(Configuration, MediaVersion.V1);
services.AddSingleton<IHealthContributor, CustomContributor>();
services.AddAllActuator(Configuration);
}
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
app.UseCloudFoundrySecurity();
app,UseBasePath("/abc");
app.UseEndpoints(endpoints =>
endpoints.MapRazorPages();
endpoints.MapControllers();
endpoints.MapFallBackToFIle("index.html");
endpoints.MapAllActuators();
});
}
```
### In app Settings.json
```
{
....
"Management":{
"Endpoints":{
"CloudFoundry":{
"Enabled": true,
"ValidateCertificate":false
}
}
}
}
```
In spite of this though I get to see the steeltoe icon in the app, the health check is coming as "-" and the custom health check is not getting shown.
## Steps to reproduce 
please copy paste the above code 
## Expected behavior
Health check should be reported

## Environment (please complete the following information):
 - Platform: [e.g. Cloud Foundry, Azure, etc.) :PCF
 - OS: [e.g. Windows, Linux, Mac OSX]:CFLINUX3 (PCF linux file system on Ubuntu Bionic)
 - .NET Version [e.g. .NET Core 2.1.0, .NET Framework 4.7.1, etc.] :.NET core 3.1 
 - Steeltoe Version [e.g. 2.3.0]:3.0

**Comment by hananiel** [comment]
@VenkateshSrini does it work locally but not in CF? so when you go to `/actuator/health` does it show output from your custom health contributor?

**Comment by hananiel** [comment]
@VenkateshSrini I deployed this app to CF and the custom health Contributor works fine.  Can you please double-check what is different? https://github.com/SteeltoeOSS/Samples/tree/master/Management/src/CloudFoundry

**Comment by VenkateshSrini** [comment]
@hananiel , 
The sample that you showed is pointing to 2.4.3 version of steel toe. But I was able to get the same working. I had to comment `services.AddAllActuator(Configuration);` as `servces.AddClouFoundryActutator` is already added. Also I had to comment out `endpoints.MapAllActuators();`
