### ISSUE TITLE
Allow user to add custom header(s) with Config Server

### ISSUE THREAD

**Issue by ghanshyamjaswal** [SteeltoeOSS/Steeltoe#472]
## Is your feature request related to a problem? Please describe.
I am using spring cloud config server and not able to pass token to other header key. 
Our spring config server is expected token with "x-service-token" header instead of "X-Config-Token"
.

## Describe the solution you'd like

Allow us to add other header into httpclient.

## Additional context
Add any other context, code snippets, or examples of the feature here.

**Comment by TimHess** [comment]
This header name [is currently defined as a constant](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs#L37) and is not currently override-able... Is it just the name of that header you want to adjust or is there more you need to control?

**Comment by ghanshyamjaswal** [comment]
Is there an option to add multiple header with different values
