### ISSUE TITLE
Steeltoe discovery client doesnot pick service url from appsettings

### ISSUE THREAD

**Issue by ghanshyamjaswal** [SteeltoeOSS/Steeltoe#473]
## Describe the bug
Steeltoe.discovery.client doesnot pick eureka service url from appsettings.json
Eureka client config.cs have default_serverserviceurl which is not get override and try that hardcode url to registry the client or service

## Steps to reproduce 
1.set valuea in appsettings.json
2. Use adddiacovery client and usediscovery client and check the servic url which is in appsetring getting used or not.
![20201016_222331](https://user-images.githubusercontent.com/17565824/96286614-480f3c80-0ffe-11eb-8fea-f612207e1fdf.jpg)

2.

## Environment (please complete the following information):
 - Platform: [e.g. Cloud Foundry, Azure, etc.) 
 - OS: [e.g. Windows, Linux, Mac OSX]
 - .NET Version [e.g. .NET Core 2.1.0, .NET Framework 4.7.1, etc.] 
 - Steeltoe Version [e.g. 2.3.0]
 - Any other library versions to note

**Comment by TimHess** [comment]
@ghanshyamjaswal please provide (at least the relevant parts of) your appsettings.json and which version of Steeltoe you're using

**Comment by ghanshyamjaswal** [comment]
Closing issue. It is not picking because of wrong appsetting file
