### ISSUE TITLE
Whether there is a way to implement distributed transactions is between Java services

### ISSUE THREAD

**Issue by windsOne** [SteeltoeOSS/Steeltoe#476]
Whether there is a way to implement distributed transactions is between Java services。
How to implement distributed transactions when both Java services and. net core services are invoked

**Comment by TimHess** [comment]
The core Steeltoe team does not have capacity to work on this effort for the foreseeable future. If this effort is important to you (yes _you_, the reader of this comment) or you can add some context or ideas around what it would look like, please open a new issue to restart the conversation.
