### ISSUE TITLE
Trace Actuator issues

### ISSUE THREAD

**Issue by DanielRekowski** [SteeltoeOSS/Steeltoe#477]
Hey,

1. When I use AddTraceActuator() on the IHostBuilder, the documentation is telling me the default value of the trace actuator endpoint is "trace" where actually it is "httptrace". Similar to that, the configuration entries for the trace actuator are "httptrace" instead of "trace" without any clue in the docs.
This is only working when I add "Management": {"Endpoints": { "Path": "/" } } to the configuration which should be the default value according to the docs.

1. In addition the application is not even starting when I use AddTraceActuator(MediaTypeVersion.V1). The error is: "Unable to resolve service for type 'Steeltoe.Management.Endpoint.Trace.HttpTraceEndpoint' while attempting to activate 'Steeltoe.Management.Endpoint.Trace.HttpTraceEndpointMiddleware'."

Tested with a new .NetCore 3.1application (Web Api Template). I just added Steeltoe.Management.EndpointCore 3.0.1.

Kind Regards
Daniel Rekowski

**Comment by hananiel** [comment]
@DanielRekowski  thanks for reporting this issue. We are in the process of fixing the docs, the httptrace is the new default when using v2. If you want to use the AddTraceActuator(MediaTypeVersion.V1) You must also use the corresponding UseTraceActuator(MediaTypeVersion.V1). Btw, Management": {"Endpoints": { "Path": "/" } }  is not the default, its /actuator - We should wrap the docs up this week. Sorry about that!

**Comment by DanielRekowski** [comment]
@hananiel ok so this seems to be mostly a documentation issue, except the MediaTypeVersion.V1:

1.  I can activate the trace actuator with .AddTraceActuator(MediaTypeVersion.V2) on **IHostBuilder**.
1. But .AddTraceActuator(MediaTypeVersion.V1) on **IHostBuilder** is not working (the error in my first post)

1.  I can activate the trace actuator with  AddTraceActuator() on **IServiceCollection** + Map\<TraceEndpoint\>
1. But I cannot find a possibility to switch to MediaTypeVersion.V1 with this method. (And I cannot find UseTraceActuator, am I missing another Nuget package?)

**Comment by hananiel** [comment]
@DanielRekowski let me clarify.  The UseXXX are only for Steeltoe2.x. In Steeltoe 3.x, 

To add TraceActuator V2, 
  - Using IHostBuilderExtensions: ` hostBuilder.AddTraceActuator()` - Defaults to v2.
  - Using IServiceCollectionExtensions:  `services.AddTraceActuator()` - Defaults to v2
               then use IEndpointRouteBuilderExtension - `endpoints.Map<HttpTraceActuator>() `
To Add TraceActuator V1
  - Using IHostBuilderExtensions:  `hostBuilder.AddTraceActuator(MediaTypeVersion.V1)`  - just tested this works. Remember to look for http://<yourhost>:<port>/actuator/trace
 - Using IServiceCollectionExtensions: `services.AddTraceActuator(MediaTypeVersion.V1)`
           and then use  IEndpointRouteBuilderExtension - `endpoints.Map<TraceActuator>() `

**Comment by DanielRekowski** [comment]
@hananiel  for me this is still not working. Can you have a look at the attached sample?

[TestApp.zip](https://github.com/SteeltoeOSS/Steeltoe/files/5443397/TestApp.zip)

**Comment by hananiel** [comment]
I found a couple of issues - missing appsettings.json to expose trace which is not exposed by default. Second there is indeed an issue with Steeltoe.Management.EndpointCore 3.0.1, updating to 3.1.1 fixes it.
