### ISSUE TITLE
Steeltoe Connectors are not reading values from appsettings.json

### ISSUE THREAD

**Issue by miguellira** [SteeltoeOSS/Steeltoe#491]
## Describe the bug
For local development, I can no longer configure Steeltoe Connectors (e.g. Redis) using values set in `appsettings.json`. It appears the extensions only work when both **VCAP_SERVICES** **_and_** **VCAP_APPLICATION** environment variable are set in `launchSettings.json`.

## Steps to reproduce 
1. Use the [Steeltoe Initializer](https://start.steeltoe.io/) app to create a new app using Steeltoe version 3.x and targeting netcoreapp3.1 and add the **Redis** dependency.
2. Add your redis connection information in a **vcap:services** node in your **appsettings.json** file, for instance:
```json
  "vcap:services": {
    "p.redis": [
      {
        "credentials": {
          "host": "x.x.x.x",
          "password": "password",
          "port": 6379
        }
      }
    ]
  }
```
3. Inject `IDistributedCache` to a controller and call `SetStringAsync`
4. The configuration is not used and the following localhost fallback error is displayed:

`RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 6s ago, v: 2.0.593.37019`

5. However, if you add an environment variables named **VCAP_SERVICES** and **VCAP_APPLICATION** in your `launchSettings.json` file with the same json it works fine.

## Expected behavior
The application successfully connects to Redis using values in your `appsettings.json` or `appsettings.Development.json` file.

I believe previous versions of these connectors allowed you to configure your services for local development within `appsettings.json` as detailed here: https://dotnet-cookbook.cfapps.io/core/local_vcap_override_by_pcf/

## Environment (please complete the following information):
 - Platform: Cloud Foundry
 - OS: Windows
 - .NET Version: .NET Core 3.1.9
 - Steeltoe Version: 3.0.1

**Comment by TimHess** [comment]
This should still work without specifying `VCAP_APPLICATION` if you remove `vcap` from the services path in the local file.

Alternatively you can use the shorthand format `redis:client:host`, etc so that Steeltoe doesn't think you're running in a Cloud Foundry environment when you aren't.

**Comment by jkonicki** [comment]
@miguellira I hope Tim's answer helped.  If not please reopen or request to reopen the issue.  

Thanks.

**Comment by miguellira** [comment]
@jkonicki Sorry. I should have followed up to @TimHess response. Truth is I am still having issues configuring even the most basic app via the `appsettings.json` file. However, I'm pretty certain it's either my workstation, my company's setup of these services, or a combination of both.

**Comment by TimHess** [comment]
There are two primary options for setting this information in appsettings.json.

The non-service binding format:
```
"redis": {
  "credentials": {
    "host": "x.x.x.x",
    "password": "password",
    "port": 6379
  }
}
```
or the generic service binding-like format:
```
"services": {
  "p.redis": [ // the name doesn't actually matter here
    {
      "credentials": {
        "host": "x.x.x.x",
        "port": "6379",
        "password": "password",
        // OR
        "uri": "redis://:password@x.x.x.x:6379" // note: use rediss to use a secured connection
      },
      "tags": [ "redis" ] // this could matter if credentials are not provided as URI
    }
  ]
}
```
In order for Steeltoe to read credentials out of a service binding, we have to know what kind of binding it is. For Redis bindings, we recognize by the tag of "redis" or when credentials include a Uri that starts with either `redis://` or `rediss://`. Hope that helps.
