### ISSUE TITLE
ActuatorHypermediaHandler.GetRequestUri does not account for port

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#496]
[Source](https://github.com/SteeltoeOSS/Steeltoe/blob/2.5.1/src/Management/src/EndpointWeb/Handler/ActuatorHypermediaHandler.cs)

**Comment by TimHess** [comment]
@macsux is this having noticeable side affects? I noticed pretty much the same code for [OWIN](https://github.com/SteeltoeOSS/Steeltoe/blob/2.5.1/src/Management/src/EndpointOwin/Hypermedia/ActuatorHypermediaEndpointOwinMiddleware.cs#L51) and [ASP.NET Core](https://github.com/SteeltoeOSS/Steeltoe/blob/2.5.1/src/Management/src/EndpointCore/Hypermedia/ActuatorHypermediaEndpointMiddleware.cs#L63)

**Comment by macsux** [comment]
I haven't tried with .NET core but very noticeable in the local environment when running on non-standard ports, if you browse to actuator hypermedia endpoint all links are broken. 

Keep in mind that the fix should ideally omit port if it's a standard one (80/443). This also needs to take into account (should look at X-Forwarded-Proto header as the app itself may be receiving the request over http, but SSL termination happened at the load balancer and URLs should be https).
