### ISSUE TITLE
Usage of UseEndpoints in IStartupFilter

### ISSUE THREAD

**Issue by kimbell** [SteeltoeOSS/Steeltoe#497]
We are building common libraries for use in our .NET Core services infrastructure. Some of these need to expose endpoints or add custom middleware. We are using Steeltoe for Eureaka, so I did some exploring of your codebase. 

I see a pattern of using an `IStartupFilter `for modifying the endpoints using `UseEndpoints()`. This is not an approach I've seen anywhere else. I asked a question related to this on the ASP.NET Core repo, and got a reply stating that this was not ideal since it would add multiple EndpointMiddlware to the pipeline. 

https://github.com/dotnet/aspnetcore/discussions/27503

I'm curious on how you landed on this approach? I'm also struggling to find a built in way of making the middleware pipeline extendable based on what services have been added. I have some ideas, so if they pan out, I'll let you know how we approached it.

**Comment by TimHess** [comment]
While we define multiple `IStartupFilter`s, I think the intent is that only one should ever actually be used. There could be room for improvement here, at a minimum addressing the issue in the documentation, but for anybody that wants to avoid `UseEndpoints()` being called multiple times, it is also possible to map the endpoints more directly:
```
app.UseEndpoints(endpoints =>
{
    // map individual endpoints
    endpoints.Map<CloudFoundryEndpoint>();
    // map all endpoints
    endpoints.MapAllActuators(MediaTypeVersion);
});
```

cc @hananiel in case I missed anything here

**Comment by kimbell** [comment]
The extension methods for `IHostBuilder  `and `IWebHostBuilder `contains methods like `AddEnvActuator `and `AddHealthActuator`. These methods register an `IStartupFilter` each. 

If you use these methods instead of `AddAllActuators`, a number of `IStartupFilters `will be registered. 

The way I understand the use of these AddXYZActuator is to make it a 'one liner' to set things up, rather than adding things to `IServiceCollection `and `IEndpointRouteBuilder` individually.

**Comment by TimHess** [comment]
Correct. But just because they've been added doesn't mean they've been activated, so for cases where you want more than one you should be able to add them all and then selectively enable only the ones you want. By default there's only a couple that are actually enabled

**Comment by kimbell** [comment]
In the documentation at https://docs.steeltoe.io/api/v3/management/using-endpoints.html 

> Extensions for both IHostBuilder and IWebHostBuilder are included to configure actuators with a single line of code in program.cs:

The intent then seems to be that if you only want a couple of actuators, you can call `AddEnvActuator `and `AddHealthActuator `in program.cs to set things up in an easy way. Since they both register their own `IStartupFilter`, ASP.NET will call them during startup. 

Just to be clear, this is not something that is affecting me; I'm using the `IServiceCollection `and `IEndpointRouteBuilder `approach to have more control over things. I just wanted to highlight it.

**Comment by TimHess** [comment]
I agree, thanks for the feedback! 

I do think this is an area that can (and should) be improved, but it likely isn't a high priority for us right now, so I think we'll leave it open for contribution and be available for guidance for anybody who wants to take a crack at making this part better.

**Comment by hananiel** [comment]
#560 addresses part of this problem - that calling multiple IStartupFilters is no longer a problem. @TimHess  Do we want to remove the multiple IStartupFilters as a convenience pattern and replace it with one. This change will be a breaking change which is why we held off on making it now.

**Comment by TimHess** [comment]
We aren't done here yet, we should obsolete all IStartupFilters that aren't `AllActuatorsStartupFilter` and update all the HostBuilder extensions to TryAdd `AllActuatorsStartupFilter` instead of the independent ones.

Additionally, it looks like we should add the param `Action<IEndpointConventionBuilder> configureEndpoints = null` to the extensions that don't currently have it
