### ISSUE TITLE
Health endpoint details do not display in Spring Boot Admin

### ISSUE THREAD

**Issue by tscrypter** [SteeltoeOSS/Steeltoe#507]
## Describe the bug
When monitoring my Steeltoe applications with Spring Boot Admin, the details of the Health endpoint are not displayed in Spring Boot Admin, not allowing the user to get to the fine grained detail of what's broken that is actually available via the API.

## Steps to reproduce 
1. Build a Steeltoe application that exposes the health endpoint and is configured to always show health details
2. Connect the Steeltoe application to Eureka, with the `Eureka:Instance:HealthCheckUrlPath="/actuator/health"`
3. Start a Spring Boot Admin server, connected to the Eureka instance so it will monitor the Steeltoe application.
4. Compare the application instance details page for the Eureka app to the Steeltoe app in Spring Boot Admin

A repo to see this behavior is [https://github.com/tscrypter/dotnet_exercise](https://github.com/tscrypter/dotnet_exercise)
1. Clone the repo
2. `docker-compose up`
3. Open [http://localhost:8889](http://localhost:8889)
4. Compare the health details for FACILITYSERVICE to SPRING-BOOT-ADMIN-SAMPLE-EUREKA

## Expected behavior
I would expected the health details to be displayed as nested information within the Health section of Spring Boot Admin. This appears to be a difference in the structure of the json being served from the health endpoint.

## Environment (please complete the following information):
 - Platform: Docker
 - OS: Linux
 - .NET Version: .NET Core 3.1.1.02
 - Steeltoe Version: 3.0.1
 - Spring Boot Admin: 2.2.0-SNAPSHOT using the `hananiel/spring-boot-admin-eureka-sample` docker image

## Screenshots
Expected Behavior
![Health_Details_Eureka](https://user-images.githubusercontent.com/413144/98722444-1c624680-235f-11eb-8808-f46026622864.png)

Actual Behavior
![Health_Details_Steeltoe](https://user-images.githubusercontent.com/413144/98722515-2421eb00-235f-11eb-8822-6ef4cd05ea52.png)

## Additional context or links
The JSON response for Health from a Spring Boot application demonstrating the expected behavior:  
```
{
    "status": "UP",
    "details": {
        "discoveryComposite": {
            "status": "UP",
            "details": {
                "discoveryClient": {
                    "status": "UP",
                    "details": {
                        "services": [
                            "spring-boot-admin-sample-eureka",
                            "facilityservice",
                            "mvcdogdaycare"
                        ]
                    }
                },
                "eureka": {
                    "description": "Remote status from Eureka server",
                    "status": "UP",
                    "details": {
                        "applications": {
                            "FACILITYSERVICE": 1,
                            "MVCDOGDAYCARE": 1,
                            "SPRING-BOOT-ADMIN-SAMPLE-EUREKA": 1
                        }
                    }
                }
            }
        },
        "diskSpace": {
            "status": "UP",
            "details": {
                "total": 482197385216,
                "free": 214579535872,
                "threshold": 10485760
            }
        },
        "hystrix": {
            "status": "UP"
        },
        "ping": {
            "status": "UP"
        },
        "refreshScope": {
            "status": "UP"
        }
    }
}
```

The JSON response from a Steeltoe app demonstrating the current behavior:  
```
{
    "status": "UP",
    "readiness": {
        "ReadinessState": "ACCEPTING_TRAFFIC"
    },
    "liveness": {
        "LivenessState": "CORRECT"
    },
    "diskSpace": {
        "total": 482197385216,
        "free": 239145414656,
        "threshold": 10485760,
        "status": "UP"
    },
    "eurekaServer": {
        "remoteInstStatus": "UP",
        "fetch": "Successful",
        "fetchStatus": "UP",
        "fetchTime": "2020-11-10T18:49:38",
        "heartbeat": "Successful",
        "heartbeatStatus": "UP",
        "heartbeatTime": "2020-11-10T18:49:38",
        "status": "UP",
        "applications": {
            "MVCDOGDAYCARE": 1,
            "SPRING-BOOT-ADMIN-SAMPLE-EUREKA": 1,
            "FACILITYSERVICE": 1
        }
    }
}
```
I think the difference is the `details` object in Spring Boot vs Steeltoe.

**Comment by hananiel** [comment]
> I think the difference is the details object in Spring Boot vs Steeltoe.

Exactly what the issue is.
