### ISSUE TITLE
Support for client side decryption in Config Server 

### ISSUE THREAD

**Issue by rtbhosale** [SteeltoeOSS/Steeltoe#509]
Spring config server can be configured to have decryption of encrypted property values either at server side or client side. 

https://cloud.spring.io/spring-cloud-config/reference/html/#_encryption_and_decryption
https://cloud.spring.io/spring-cloud-config/reference/html/#_serving_encrypted_properties

Steeltoe ConfigServer doesn't seems to support the client side decryption.

It would be nice to have this feature as it makes it easier to plug to an existing system which already has client side decryption enabled.

Thank you.

**Comment by fennekit** [comment]
I have written a bit of code for decoding the cipher https://github.com/fennekit/spring-cloud-config-decode

**Comment by hananiel** [comment]
@fennekit Are you planning on maintaining it in your repo or are you thinking of working towards a PR in the Steeltoe repo ?

**Comment by fennekit** [comment]
I will submit a PR in the coming week(s). I may have found an issue in the Spiring Cloud Config which prevents me from generating ciphers for the different options. I am looking to provide a PR for the symmetric encryption.

**Comment by fennekit** [comment]
Manage to decrypt using a keystore as well. So both methods are in scope for the PR
