### ISSUE TITLE
Tracer needs to implement JoinSpan and an option that turns it on and off.

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#510]
Need to implement JoinSpan and an option that turns it on and off. See [Sharing span IDs between Client and Server] : https://docs.spring.io/spring-cloud-sleuth/docs/2.2.5.RELEASE/reference/html/#sharing-span-ids-between-client-and-server.

**Comment by TimHess** [comment]
@hananiel is this a Steeltoe concern, or is it something to request from OpenTelemetry?

**Comment by hananiel** [comment]
Since we have deferred to the OTEL implementation, it is something that needs to be handled there. I vaguely remember this being something that surfaced while testing with early versions of azure spring apps. It might be worth investigating if there is still an issue there or what the current status is.
