### ISSUE TITLE
[QUESTION] Can [SendTo] be used with an async listener

### ISSUE THREAD

**Issue by TravisBoatman** [SteeltoeOSS/Steeltoe#516]
## Question
Can `[SendTo]` be used with an async listener? I tried to do it like the example below but got this error:

```
fail: Steeltoe.Messaging.RabbitMQ.Connection.CachingConnectionFactory[0]
      Unexpected invocation of Steeltoe.Messaging.RabbitMQ.Connection.CachingConnectionFactory+DefaultChannelCloseLogger, with Channel shutdown:(null)
fail: Steeltoe.Messaging.RabbitMQ.Listener.DirectMessageListenerContainer[0]
      Consumer SimpleConsumer [queue=batch_worker, consumerTag=amq.ctag-WO-WNouiLn_SIs0eCd7ttQ identity=59817589] canceled - channel closed
```

## Environment:
 - .NET Core 3.1
 - Steeltoe Version 3.0.1

## Example

```
[RabbitListener(Binding = "MyQueue")]
[SendTo("AnotherQueue")]
public async Task<string> Listen(MyMessage message)
{
    return await DoSomethingAsync(message);
}
```

**Comment by dtillman** [comment]
Hi TravisBoatman,
I believe so... I remember thinking about that use case ... let me dig into a bit more and get back to you.
Dave

**Comment by TravisBoatman** [comment]
@dtillman 
I was able to figure it out. I needed to add `AckMode = "Manual"` to the RabbitListener attribute. Like so:
`[RabbitListener("myQueue", AckMode = "MANUAL")]`
