### ISSUE TITLE
Eureka registers localhost on older Windows server version

### ISSUE THREAD

**Issue by kimbell** [SteeltoeOSS/Steeltoe#519]
We are registering services running on Windows in Eureka. With the 2.X versions, the hostname of the server was registered in Eureka. When we updated to 3.X, I noticed that some services have 127.0.0.1 registered for the host. 

127.0.0.1:service-name:4949

I deployed the same service with with the same codebase to a different environment that has a newer Windows version, and there the problem was gone. The server giving 127.0.0.1 is a Windows Server 2012 R2. It's old, but still supported. 

If there is some configuration that can be added to work around this problem, a documentation update is probably enough.

**Comment by TimHess** [comment]
Have you tried setting `Eureka:Instance:HostName`?

**Comment by kimbell** [comment]
I updated the value in my configuration file, but it didn't make any difference. Still listed as 127.0.0.1

**Comment by TimHess** [comment]
Revisiting this issue after entirely too long, I'm not sure if there is enough information here to reproduce the issue...

If this is still an issue, or if you remember, is there any way to provide more detail about app runtime and/or the Steeltoe settings that produced the problem? 

There are definitely deficiencies in older versions of Steeltoe around detecting hostname and port automatically, along with how the instance id was calculated, and it would also help a lot to know exactly which properties were registered wrong as this could have been a problem in several different areas. For example, the instance id that shows in the eureka dashboard (which is what `127.0.0.1:service-name:4949` looks like) is not necessarily what was registered for the actual service connection info.

**Comment by kimbell** [comment]
I'm a consultant and at the time of reporting this, I was working for an airline. Things happened in 2020 and I have not been involved in this project since then. I don't remember any of the details related to this.
