### ISSUE TITLE
[QUESTION] How to configure RabbitMQ Messaging for PCF/Tanzu

### ISSUE THREAD

**Issue by TravisBoatman** [SteeltoeOSS/Steeltoe#525]
## Question
Our team has implemented the RabbitMQ Messaging library. It works like a charm but configuration seems a bit off.
With the RabbitMQ connector package you can easily setup the service and pass in your configuration object which holds your `VCAP_SERVICES` info. The service magically binds the configuration behind the scenes. 
But I am unable to find a way for RabbitMQ Messaging to read from `VCAP_SERVICES`. Is there a recommended way to grab RabbitMQ connection info from `VCAP_SERVICES` for RabbitMQ Messaging?

## Environment:
 - .NET Core 3.1
 - Steeltoe Version 3.1

**Comment by TimHess** [comment]
Hi @TravisBoatman, does [this sample](https://github.com/SteeltoeOSS/Samples/tree/master/Connectors/src/RabbitMQ) answer your question at all?

**Comment by TravisBoatman** [comment]
@TimHess I've tried this but it did not work. From what I was able to gather the Steeltoe Messaging library does not utilize the Steeltoe Connector at all.

See here in the messaging library a new RabbitMQ connection factory is made. Note that any existing connection factories setup by the connector is not used.

https://github.com/SteeltoeOSS/Steeltoe/blob/e1ca980a657531fef5fe27541072e71ff79ad5e1/src/Messaging/src/RabbitMQ/Connection/CachingConnectionFactory.cs#L167-L174

Then the configuration of the factory is done here. Also note that it uses the `RabbitOptions` object rather than the connector object `RabbitMQProviderConnectorOptions`.

https://github.com/SteeltoeOSS/Steeltoe/blob/e1ca980a657531fef5fe27541072e71ff79ad5e1/src/Messaging/src/RabbitMQ/Connection/CachingConnectionFactory.cs#L587-L658

**Comment by TimHess** [comment]
@dtillman can you comment on Connector/Messaging integration?

**Comment by dtillman** [comment]
@TravisBoatman We have not done any integration with the RabbitMQ Connector yet for RabbitMQ messaging..  

There are several extension methods in [RabbitServicesExtensions](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Messaging/src/RabbitMQ/Extensions/RabbitServicesExtensions.cs) that you can use/build on to create a CachingConnectionFactory from the connectors injected rabbit factory.   

Have a look at 
AddRabbitServices() - adds to the container everything needed .. including the CachingConnectionFactory.
AddRabbitConnectionFactory() - several methods you can use to add/customize the CachinngConnectionFactory.

We hope to add support for Connectors soon...

**Comment by TravisBoatman** [comment]
@dtillman @TimHess 
Does this mean that the messaging library does not work work with PCF? I've tried to implement it and pass in the URI from VCAP_SERVICES to the `RabbitOptions` object but it does not connect.

```csharp
var cfg = hostContext.Configuration.GetSection("vcap:services:p.rabbitmq:0:credentials:protocols:amqp+ssl");
var uri = cfg.GetSection("uri").Value;

services.Configure<RabbitOptions>(x =>
{
    x.Addresses = uri;
});
```

**Comment by TimHess** [comment]
There isn't currently a direct integration, but it should still be possible to stitch these pieces together. The problem you're hitting right there is that Addresses is looking for host + port rather than a full uri. I believe something like this should work:

```csharp
using Steeltoe.Connector;
using Steeltoe.Connector.Services;
...
var serviceInfo = Configuration.GetServiceInfos<RabbitMQServiceInfo>().FirstOrDefault()
                                             ?? new RabbitMQServiceInfo("rabbitmq", "amqp://localhost:5672");
services.Configure<RabbitOptions>(x =>
{
    x.Addresses = serviceInfo.Host + ":" + serviceInfo.Port);
}
```

**Comment by bdeman1** [comment]
Hello, as of date, is there a solution to this issue? We still encounter the same problem.

**Comment by TimHess** [comment]
#609 has been added to support this feature
