### ISSUE TITLE
Cant Get Eureka Service Discovery To Work

### ISSUE THREAD

**Issue by TheLazyLemur** [SteeltoeOSS/Steeltoe#526]
## Question
I cant seem to get Eureka work, I am not listing it as a bug as I am not sure if it is. The issue im having is that my services do not register with Eureka. Im running Eureka with ```docker run --publish 8761:8761 steeltoeoss/eureka-server``` Im am using a webapi project generated by the Steeltoe Initialize. 

## Environment
 - .NET Core 3.1.403
 - Steeltoe 3.0.1

## Additional context or links
Eureka says it is running on 172.17.0.3 although it is still accessible from localhost, I don't think this is the issue though.
My appsettings.json looks like this:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "spring": {
    "application": {
      "name": "TestApi"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": "http://localhost:8761/eureka/",
      "shouldFetchRegistry": "false",
      "shouldRegisterWithEureka": true,
      "validateCertificates": false
    },
    "instance": {
      "port": "5000",
      "ipAddress": "127.0.0.1",
      "preferIpAddress": true
    }
  }
}
```

and my Startup Configurations :

```cs
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDiscoveryClient(Configuration);
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseDiscoveryClient();
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
```

I do notice this warning on startup

```
 No discovery client has been configured, using default no-op discovery client.
```

**Comment by TheLazyLemur** [comment]
Okay... So I found the solution to my problem. I switched  to using Consul and then I just needed to install and extra package.. namely
```
Steeltoe.Discovery.Consul
```
after that it worked perfectly. 

I have not tested it but using 
```
Steeltoe.Discovery.Eureka
```
may fix the issue if you stick to Eureka.
This step is not in the official getting started guide, therefore I will leave this open for now.

**Comment by TimHess** [comment]
@ddieruf is this an issue with Getting Started or the Initializr template?

**Comment by jkonicki** [comment]
Related to #459 - Can we do something similar?
