### ISSUE TITLE
.AddRoundRobinLoadBalancer() causes NotSupportedException in .net5.0

### ISSUE THREAD

**Issue by antonpopov** [SteeltoeOSS/Steeltoe#530]
When using `.AddRoundRobinLoadBalancer()` for client side load balancing in **.net5.0** upon sending a http request an exception is thrown: `NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.`

## Steps to reproduce 
1. Create an ASP.NET Core Web API project
2. Configure a named http client to use `DiscoveryHttpClientHandler `and add `.AddRoundRobinLoadBalancer()`.
```
services.AddHttpClient("test")
        .AddRoundRobinLoadBalancer()
        .ConfigurePrimaryHttpMessageHandler(sp => new DiscoveryHttpClientHandler(sp.GetService<IDiscoveryClient>()))
        .AddTypedClient<ITestService, TestService>();
```
3. Make a request through the http client.

## Environment:
 - Steeltoe Version [3.0.1]
 - .NET Version [.NET5.0]

**Comment by antonpopov** [comment]
I did some research on the issue and I believe [here is the problem](https://github.com/SteeltoeOSS/Steeltoe/blob/a44088421f753f544153124f495782cc1721ee7d/src/Common/src/Common/Discovery/IServiceInstanceProviderExtensions.cs#L53) and it's caused by a [breaking change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete) in .NET 5.0.
Here is a temporary workaround for anyone who has the same issue:
```
<PropertyGroup>
  <TargetFramework>net5.0</TargetFramework>
  <!-- Warning: Setting the following switch is *NOT* recommended in web apps. -->
  <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
</PropertyGroup>
```
N.B. As pointed in Microsoft's documentation this workaround is not recommended as a long term solution due to security reasons.

**Comment by TimHess** [comment]
Thanks for finding this @antonpopov
