### ISSUE TITLE
Metrics observers - reduce the number of default metrics configured 

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#532]
Currently by default we add all available metrics from the runtime and observers. This creates an issue with someone getting started with metrics. Reduce this to a few well known and expected metrics and make others configurable.

**Comment by TimHess** [comment]
Toggles already exist at the observer level, and only [three out of seven observers](https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Management/src/EndpointBase/Metrics/MetricsObserverOptions.cs#L51) are enabled by default.

There is currently no way to toggle which metrics are tracked within a given observer, but most of the observers only record a couple metrics. `EventCounterListener` is the only exception, reporting over 20 metrics
