### ISSUE TITLE
Refactoring the Management endpoints

### ISSUE THREAD

**Issue by kimbell** [SteeltoeOSS/Steeltoe#545]
The discussion on #503 has drifted from the original topic. This issue has been created for the general discussion on management endpoints so that the original issue can resume it's original duty.

My thoughts on improving the management endpoint features can be broken down into the following phases.

Phase 1 is to get #543 merged since that makes testing easier.

Phase 2 is to update the tests so that DI is the primary mechanism for creating objects. This allows us to refactor the internals without breaking too many tests. A lot of tests are currently using `TestHost` and could be updated to use `WebApplicationFactory` that was created by Microsoft for testing purposes; wraps `TestHost` and sets up other things.
Since we are updating tests, it allows us to fix #542. I have an approach that doesn't depend on external libraries that works for most cases; depends on how much you want to analyze the logging output during the test.

Phase 3 is to update the internals of the management endpoint code. I have some ideas on how this can be achieved. One idea I'm toying around with is using an `EndpointDataSource` for the actuator and CloudFoundry endpoints.

**Comment by kimbell** [comment]
I'm looking at this from a .NET Core perspective. Great that there was support for .NET Framework, but long term, Core will be the only game in town. Based on that, there are things that should be done to align it with how .NET Core does things. The big challenge is how do we get there, and how can we incrementally make changes that don't break everything. At some point in the future, the code will just have to accept that .NET Framework is dead and buried. As long as `EndpointBase` is constrained by history, it restricts what type of changes can be made. When that time comes, I don't know. 

I have played around with several ideas on what can be changed, but usually hit a dead end that would cause too many changes that are hard to track or become a binary breaking change. I'm trying to find small changes that don't break things completely and can be used to aid the long term goals of the project; makes it easier to merge between branches. This to delay the split from .NET Framework as long as possible. 

So what types of changes would I like to make? 

The code contains a lot of Option objects. For .NET Core developers, that comes with a lot assumptions since Microsoft has the `IOptions` pattern. It would not be unreasonable for .NET Core developers to think that they could leverage all the possibilities of the IOptions pattern. i.e. `Configure()` and `PostConfigure()`. 

Since Steeltoe isn't using this pattern, it may become a developer surprise. I couldn't find anything in the documentation stating that `IOptions` is not supported. The options pattern is to expose configuration values consumers can change. The Options classes in Steeltoe contain options that can't be changed by consumers; `AllowedVerbs` and `ExactMatch`. Another small surprise. 



Another problem, depending on your point of view, with the codebase is that everything is public. A lot of the classes will most likely not be used by consumers, so some changes probabaly wouldn't result in broken builds. But since they are public, it's not hard to make a breaking change. Long term things should be made internal to make it easier to change implementation details without impacting the public API surface.

Lets assume some endpoint is currently depending on A, B, and C. Then sometime in the future, B should be changed to D and a new dependency on E is added. This is a breaking change for consumers, but it also results in a lot of tests changing just to get things to build. 

This is where IoC containers come into play. Rather than newing up every object explicitly, use the container to create them. 
Over time the dependencies for each service can change without impacting the tests. 

In the tests, something like this can be achieved

```cs
[Fact]
public async Task SomeTest()
{
	// the TestContext is used to set up the IServiceCollection
	// some things like Logging and Options infrastructure is added by default
	using(var tc = new TestContext())
	{
		// each test can add additional dependencies specific for the test
		tc.Services.AddEnvAcutatorServices();
		
		var endpoint = tc.GetService<IEnvService>();
		
		var response = await endpoint.Invoke();
		
		Assert.NotNull(response);
	}
}
```

Will the dependency problem be solved by PR #553? No, but it allows us to start creating tests that don't explicitly new up every single object. At some point in the future, the code behind `AddEnvAcutatorServices` will be radically different from today. What we do achieve with the PR is to push back further the date when a break with .NET Framework happens.


In this comment, https://github.com/SteeltoeOSS/Steeltoe/issues/503#issuecomment-737501108, the idea has been to support exposing actuators on other things than HTTP. That doesn't match very well with the current codebase. Things are called Endpoints, that doesn't technically need to be HTTP, but often will assumed to be. The Options classes contain `AllowedVerbs` and `Path`, and that smells very of HTTP.

If we are going really crazy with changes, then I would propose having an `IEnvService` that exposes the core functionality.This could be exposed through an Endpoint/Actuator, or someone could trigger it via a message on a Kafka topic.

**Comment by kimbell** [comment]
I had a quick look at Nuget, and all the latest versions of Microsoft.Extensions.* are still supported on .NET Framework 4.6.1. 
From a technical point of view, it's possible to create code that runs on both Framework and Core that uses IServiceCollection. 

This would be a breaking change, but if .NET Framework support is really important, it might be something to consider. 
Rather than writing 

```cs
var endpoint = new EnvEndpoint(options, configuration, hostEnvironment, logger);
```
you can write

```cs
var services = new ServiceCollection();
services.AddEnvAcutatorServices();

var provider = services.BuildServiceProvider();
var endpoint = provider.GetService<EnvEndpoint>();
```
With some helper methods, consumers can wrap this to make it easier to use. Since they are on Framework, chances are that they are using static member variables for singletons, so that can be used to hold services. 

The earliest nuget release for EndpointBase was published in December 2017. I'm guessing that the majority of .NET Framework projects using Steeltoe are of a newer vintage; those created between 2002 and 2016 may not be prime candidates. 

This might be a topic for a survey? How important is .NET Framework support?

**Comment by hananiel** [comment]
Regarding .NET framework support, Steeltoe will continue maintaining framework since it is important to our customers. I don't think there is any question about deprecating it. Regarding maintainability, I think its best to leave Endpoint base where it is because changes to the core functionality are isolated from infrastructure concerns. I am not super familiar with WebApplicationFactory, but it sounds like it is there to test complete applications rather than middleware. From Andrew Lock's [blog](https://andrewlock.net/converting-integration-tests-to-net-core-3/): _"Using the TestServer directly like this is very handy for testing "infrastructural" components like middleware, but it's less convenient for integration testing of actual apps. For those situations, the Microsoft.AspNetCore.Mvc.Testing package takes care of some tricky details like setting the ContentRoot path, copying the .deps file to the test project's bin folder, and streamlining TestServer creation with the WebApplicationFactory<> class."_ What we are adding and testing here is literally middleware.  So I don't think it is a step up from what we have with test host. What is needed is more test coverage, not a different way of testing - which would in the short term achieve the opposite effect.

**Comment by kimbell** [comment]
`WebApplicationFactory` uses `TestServer` internally, so it's possible to build up your own wrapper around it. I've used both and find `WebApplicationFactory` easier to build around, it also gives me the closest thing to a real running environment. I've used this for both application testing and library testing that may or may not add middleware. Since it does more than `TestServer`, it may cost more in terms of memory and execution time. For my scenarios this cost has been something I've been willing to pay since it reduces the chances of weird platform issues cropping up when the code runs in an actual application.

`WebApplicationFactory` can use a `Startup` class; not something the `TestServer` knows anything about. Since the `EndpointCore` tests contains more than 40 references to `Startup` classes, using the `WebApplicationFactory` seems like something that can be considered.

**Comment by jkonicki** [comment]
We are reopening this.  

Hi @kimbell.  Thanks again for the contributions to the project.  We would like to discuss this further with you and how we can do this work in smaller slices.  The team is actively working on other priority features, but we think you are addressing areas that need to be considered and updated.  Since some of the work touches a lot of the code, we want to make sure we can prioritize the work you are doing.   We will reach out to discuss.

**Comment by TimHess** [comment]
This should all be resolved, or at least very different now that a large chunk of refactoring work has been completed
