### ISSUE TITLE
register instanceid host in iis inprocess model

### ISSUE THREAD

**Issue by akaxb** [SteeltoeOSS/Steeltoe#546]
## Describe the bug
A clear and concise description of the bug.  
when my asp.net core 3.1 app host in IIS, the url console is 127.0.0.1，so，when i have Multiple instances，the instances name will be the same,such as 127.0.0.1:svaname:port，eureka server think they are a single instance.
i print the console in source code：
![image](https://user-images.githubusercontent.com/6300834/101754289-8ad92680-3b0e-11eb-9f54-6c7971146b35.png)
![image](https://user-images.githubusercontent.com/6300834/101754433-b0fec680-3b0e-11eb-9b6e-37991e0553a9.png)
![image](https://user-images.githubusercontent.com/6300834/101754668-f3280800-3b0e-11eb-9c3f-b18fee056464.png)

**Comment by TimHess** [comment]
Hi @ZuraizAhmedShehzad,

You're welcome to take a look at this issue, but I'm not confident it really is a "good first issue" for somebody new to Steeltoe as it could need to relate to other issues like [this one](https://github.com/SteeltoeOSS/Steeltoe/issues/1107) or [this one](https://github.com/SteeltoeOSS/Steeltoe/issues/490) and there is the potential complexity with setting up an environment to replicate the issue. Happy to help work through it if you are still up for it after those considerations!

If you would prefer something a little more approachable to get started, we would also greatly appreciate some basic validation and potential enhancements of the quick start guides or documentation, such as [this issue for service discovery guides](https://github.com/SteeltoeOSS/Documentation/issues/229)

**Comment by ZuraizAhmedShehzad** [comment]
> Hi @ZuraizAhmedShehzad,
> 
> You're welcome to take a look at this issue, but I'm not confident it really is a "good first issue" for somebody new to Steeltoe as it could need to relate to other issues like [this one](https://github.com/SteeltoeOSS/Steeltoe/issues/1107) or [this one](https://github.com/SteeltoeOSS/Steeltoe/issues/490) and there is the potential complexity with setting up an environment to replicate the issue. Happy to help work through it if you are still up for it after those considerations!
> 
> If you would prefer something a little more approachable to get started, please consider [this issue with endpoint mappings](https://github.com/SteeltoeOSS/Steeltoe/issues/155) and know that we would also greatly appreciate some basic validation and potential enhancements of the quick start guides or documentation, such as [this issue for service discovery guides](https://github.com/SteeltoeOSS/Documentation/issues/229)

Thanks for suggestion Tim. Since I was looking for a good first issue I am looking into the one you have suggested. Thanks !

**Comment by TimHess** [comment]
@akaxb,

Are you still experiencing this issue? Are you able to provide a more complete repro (what are the multiple registrations) so we can better understand the use case? We need to understand how to setup IIS in order to reproduce this so that we can reason about it
