### ISSUE TITLE
Split actuator service collection registration

### ISSUE THREAD

**Issue by kimbell** [SteeltoeOSS/Steeltoe#553]
The EndpointCore project is where all management actuators get added to the `IServiceCollection`. I understand that is mainly due to historical reasons; EndpointBase also supported .NET Framework. Another reason for keeping things in the EndpointBase was to allow other non-http mechanisms to trigger the actuator. 

In order to make it easier to refactor code moving forwards, it would be beneficial if objects could be created through an IoC container. This would allow a great number of tests to focus on functionality rather than how the objects get created. 

For the tests related to EndpointCore, this is doable since they already have code that adds services to the `IServiceCollection`. For tests related to EndpointBase, this isn't possible. 

In EndpointCore there is methods such as `AddEnvActuator`.
In EndpointBase we can add methods such as `AddEnvActuatorServices`

We basically move some of the code to the EndpointBase project, and call it from EndpointCore. 
This is an additive change that doesn't break existing functionality; consumers can still create objects directly without going through an IoC container.

**Comment by hananiel** [comment]
Hey @kimbell  thanks for the issue and PR. Steeltoe continues to support .Net framework in the 2.x line and we will continue to do so. So the reason we kept the base/core division is so it is easy to manage these branches simultaneously. Would your changes make sense in the 2.x line, if they do, then it would be better to make this change in the 2.x line and bring it over.

**Comment by kimbell** [comment]
@hananiel these changes depend on `IServiceCollection`, so technically it could be used on both Core and Framework. I don't believe there is anything stopping developers from using the new IoC framework on .NET Framework (I did that several years ago).

Since the EndpointBase project didn't have a dependency on Microsoft.Extensions.DependencyInjection.Abstractions, I'm guessing this is not a typical scenario for Steeltoe, so it becomes .NET Core only. 

If the code in the master branch is used from .NET Framework, I don't see anything breaking. The assembly just has another nuget reference and some new API's. The public API surface of EndpointBase doesn't have any breaking changes. 

Just for clarity, my understanding is that the code in the master branch is for 3.x and .NET Framework is out of scope for that. Correct?

**Comment by hananiel** [comment]
The goal is that the `EndpointBase` project remains similar between 2.x and master for maintainability. We can add `Microsoft.Extensions.DependencyInjection.Abstractions` although if it's not needed in 2x, that's may be a clue that it doesn't belong there.  In 3.x, regarding .NET framework you are correct. However, I think it might be better to make the split but keep it in core project? I also noticed the new tests only test the new code, which was being tested a different way before. What is the benefit of this change for testing ? Can you point to a gist or sample please of what the end goal of refactoring would look like? Hit me on slack or we can do a video chat if thats more helpful ...

**Comment by kimbell** [comment]
Since this is touching in on the overall refactoring thing I have mentioned in #545, I added a comment there. https://github.com/SteeltoeOSS/Steeltoe/issues/545#issuecomment-748282426

As for the additional tests, they are based on code in the EndpointsCore.Test project and I've added them for the new API's.
