### ISSUE TITLE
Span and trace propagation 

### ISSUE THREAD

**Issue by vd-pltk** [SteeltoeOSS/Steeltoe#557]
Hello, my project relies on a span and trace data propagation between systems, and during migration to the new version of Steeltoe (2.4.4 -> 3.0.2) I have noticed that my code doesn't work as expected. During the investigation, I found interesting lines of code in TracingCore lib that had broken backward compatibility.
It seems that logic here has redundant inversion - in case of **successful context extraction** code creates the **brand new span** without relation to a parent trace.  I suppose that it should work the other way round.

```             

 if (!traceContext.IsValid)
{
      Logger?.LogDebug("HandleStartEvent: Found parent span {parent}", traceContext.ToString());
      Tracer.StartActiveSpan(spanName, traceContext, SpanKind.Server, out span);
}
else
{
      Tracer.StartActiveSpan(spanName, SpanKind.Server, out span);
}

```
https://github.com/SteeltoeOSS/Steeltoe/blob/7821dec4b61de1ba44c14cdff07f099cca6e4ea9/src/Management/src/TracingCore/Observer/AspNetCoreHostingObserver.cs#L125

In the version 2.x. this code worked fine:

https://github.com/SteeltoeOSS/Steeltoe/blob/2.x/src/Management/src/TracingCore/Observer/AspNetCoreHostingObserver.cs#L136

**Comment by hananiel** [comment]
@vd-pltk thanks for this issue. You are correct in that this is backwards or it should say `if (traceContext.isValid)`.
