### ISSUE TITLE
Heap dump functionality when running on a Windows system can fail due to process cloning and other conditions

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#569]
## What is your issue related to? Please describe.
When running a win32 app (.NET Framework) and trying to create a heap dump it can crash.  

There are several areas to check:
1.  Heap dump creates a clone process which could create an out of memory condition resulting in the app “crashing”
2. It appears the process cloning can make it challenging to create a heap dump even if memory is increased in the container.  

## Describe the solution you'd like
Requiring an increase in the container size to make a heap dump is not a great experience.  This also requires a restart which may invalidate the conditions we are trying to gather within the unhealthy container.  

## Alternative solutions
1. Increasing the size of the container and waiting for it to happen again.
2. On CF, SSH into the container and run a utility to execute a heap dump. 

## Additional context
Possible solution for Steeltoe 2.x: Look at creating a sidecar option in order to create the heap dump

## Environment: 
TASW 2.7, Steeltoe 2.x, running win32 apps (might happen with other apps too)

**Comment by TimHess** [comment]
This item is not currently a priority for the core team and may require side car usage. Please let us know if this feature is important to you

**Comment by TimHess** [comment]
Closing due to insufficient interest. If you would like to see this supported, please respond to this issue
