### ISSUE TITLE
BuildInfoContributor exception with PublishSingleFile

### ISSUE THREAD

**Issue by gregolm** [SteeltoeOSS/Steeltoe#572]
https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Management/src/EndpointBase/Info/Contributor/BuildInfoContributor.cs is still using Assembly.Location

This causes the app to crash on startup when compiled with the -P:PublishSingleFile=true flag

It should get the versions without using the filesystem

## Environment (please complete the following information):
 - Steeltoe Version 3.0.2
 - Platform: Pivotal Cloud Foundry & local (OSX)  
 - OS: Mac OSX
 - .NET Version: Core 5.0.101 
 
## Screenshots
When publishing with the  -p:PublishSingleFile=true this causes the error 
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)

The compiler produces the following warning:
 warning IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.   

## Additional context or links
This is the same behavior that was noticed in this bug (now closed)
https://github.com/SteeltoeOSS/Steeltoe/issues/520
but the closing PR https://github.com/SteeltoeOSS/Steeltoe/pull/536 didn't address all the Assembly.Location usage.

**Comment by TimHess** [comment]
Looks like you're right and I missed that, thanks for pointing it out @gregolm - would you like to open a PR to fix it?
