### ISSUE TITLE
Return version info in a way that Spring Boot Admin will display

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#581]
In this image, a Spring app displays a version of 2.3.6 while Steeltoe apps don't show a version:
![image](https://user-images.githubusercontent.com/3947063/106187581-d190e780-6173-11eb-9375-bbf5a68e632b.png)

It looks like this might be coming from the response of `/info` in this location:
```json
{
  "build": {
    ...
    "version": "2.3.6"
    ...
  }
}
```

**Comment by jkonicki** [comment]
Completed in #592
