### ISSUE TITLE
Heap Dump actuator via App Manager on TAS (linux container) does not work

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#585]
When deploying and following the instructions for the CF management sample.  Trying to create a heap dump fails (it downloads an empty dmp file).  The debug logs show the Operation failed.  Seems due to permissions.  

This needs to be verified and if it is an issue with TAS, it will need to be resolved, or at least provide a way to allow a user to have this functionality.

**Comment by jkonicki** [comment]
Exact error message in the logs "[ERR] ptrace(ATTACH, 15) FAILED Operation not permitted"

**Comment by TimHess** [comment]
[CloudFoundry/TAS removes ptrace](https://docs.cloudfoundry.org/concepts/container-security.html#hardening)

[dotnet dumps require ptrace](https://github.com/dotnet/docs/issues/20573#issuecomment-707259394)
