### ISSUE TITLE
`IConfigurationBuilder` object not getting `Label` property from `ConfigServerClientSettings`

### ISSUE THREAD

**Issue by fernandobperezm** [SteeltoeOSS/steeltoe#59]
I'm using Steeltoe for config server reading and discovery. I'm adding the config server info through the `ConfigServerClientSettings` class and the `AddConfigServer()` extension method for the `Microsoft.Extensions.Configuration.ConfigurationBuilder()` class.

Previously I used an `appsettings.json` file to load all the values required by Steeltoe to connect with the Spring Config Server. It worked perfectly and we could get all our config keys. 

However, the team now wants to use the `ConfigServerClientSettings` class to provide this information. Sadly, when I'm using this class, the `Label` property is not being read when I build the Configuration. Moreover, after the initialization of the `ConfigServerClientSettings` class and calling `AddConfigServer(...)` it's still set. 

When I pass through the `builder.Build()` method I see that the property is set to `null`. When I inspect the `builder` variable I see that it has all Spring-related config set properly except for the `label`.

This is a code snippet that shows this strange behavior.
```
LoggerFactory loggerFactory = new LoggerFactory();
string configName = "testConfigName";
string configLabel =  "testConfigLabel";
string configUri = "http://localhost:8888";
string configEnv = "testEnv";
var configServerClientSettings = new ConfigServerClientSettings()
{
    Name = configName,
    Label = configLabel,
    Uri = configUri,
    Environment = configEnv,
    Enabled = true,
};

IConfigurationBuilder builder = new Microsoft.Extensions.Configuration.ConfigurationBuilder().AddConfigServer(configServerClientSettings, loggerFactory);

builder.Build();
```

Do you have any idea what would be causing this issue?

**Comment by TimHess** [comment]
Hi @fernandobperezm,
Sorry for the slow response - you're right, looks like there is a bug here! This property, along with a couple others was being ignored when it was provided this way. The fix should be in our next release, thanks!
