### ISSUE TITLE
Update OpenTelemetry Dependency

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#604]
Open Telemetry has now shipped a stable release, Steeltoe should be updated to use version 1.0.1

**Comment by carlos-vicente** [comment]
Hi guys, do you have a timeline for this? We really want to get cracking with Steeltoe with the first stable OpenTelemetry release

**Comment by TimHess** [comment]
Unfortunately the situation is more than a little bit complex with the way OpenTelemetry completely dropped metrics from the 1.0.1 release and has only shipped beta packages for instrumentation. Our codebase was updated to use those metrics bits which have disappeared, which puts us in an awkward/weird state

**Comment by carlos-vicente** [comment]
yeah, went over the OpenTelemetry documentation and found that they were stating that the metrics API will only be available after .NET 6 gets released... I think we will go with Prometheus-net for metrics collection and endpoint while OpenTelemetry does take this forward..
