### ISSUE TITLE
Add ability to configure RabbitMQ Messaging using the RabbitMQ Connector

### ISSUE THREAD

**Issue by dtillman** [SteeltoeOSS/Steeltoe#609]
It should be easier for a developer to wire up RabbitMQ messaging using the Steeltoe Connector for RabbitMQ.
Currently developers have to manually code the wire-up of the RabbitMQ connection factory from the connector with the RabbitMQ connection cache.

**Comment by jkonicki** [comment]
Hananiel: "Required for SCDF on CF"
