### ISSUE TITLE
Reading configuration from git

### ISSUE THREAD

**Issue by iliya24** [SteeltoeOSS/Steeltoe#610]
Hello
I am following [this tutorial](https://steeltoe.io/app-configuration/get-started/springconfig) step by step but ,and it looks fine but in the end, I see when running the Spring bot it is updated on the git repo but does not get the values as in [this tutorial](https://www.youtube.com/watch?v=hxRjk66s51Q&t=694s&ab_channel=ThinkingMachines)
so the values always null.
I used Steeltoe Initializr to create the project
Do I miss something?
my net core config 
` var builder = WebHost.CreateDefaultBuilder(args)
                .AddConfigServer()
                .UseStartup<Startup>();
            return builder;`
this is my spring boot start

![image](https://user-images.githubusercontent.com/6517507/109128183-eacb8a80-7757-11eb-8b67-49088d48a75e.png)

**Comment by ddieruf** [comment]
Hi @iliya24 can you provide your appsettings.json and (if you are using it) appsettings.development.json?

**Comment by iliya24** [comment]
appsettings.json

`{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
   "spring": {
    "application": {
      "name": "my-values"
    },
    "cloud": {
      "config": {
        "uri": "http://localhost:8888",
        "validateCertificates": false
      }
    }
  }
}
`

appsettings.Development.json
{
 
  "spring": {
    "application": {
      "name": "my-values"
    },
    "cloud": {
      "config": {
        "uri": "http://localhost:8888",
        "validateCertificates": false
      }
    }
  }
  }

**Comment by iliya24** [comment]
Works now the problem was that the name of branch was main and it supposes to be master
as per [https://www.programmersought.com/article/73955775208/](url)

**Comment by jkonicki** [comment]
Note:  I have escalated the following issue with Spring Config team about the `master` vs `main` issue. Hoping it is resolved soon.  
Issue link: https://github.com/spring-cloud/spring-cloud-config/issues/1722
