### ISSUE TITLE
Usage of RefreshActuator with HTTP POST

### ISSUE THREAD

**Issue by iliya24** [SteeltoeOSS/Steeltoe#611]
## Question
I am trying to use RefreshActuator in order to reload configuration in run time
I have followed [this documentation](https://docs.steeltoe.io/api/v3/management/using-endpoints.html#http-access) 
## Environment (please complete the following information):
 - .NET Core 3.1
 - Steeltoe Version [e.g. 3.0.1]
  ```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var builder = WebHost.CreateDefaultBuilder(args)                
                
                .AddRefreshActuator()
                .AddConfigServer()
                
                .UseStartup<Startup>();
            return builder;
        }
```

also tried 
```
 public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var builder = WebHost.CreateDefaultBuilder(args)                
                
                .AddAllActuators()
                .AddConfigServer()
                
                .UseStartup<Startup>();
            return builder;
        }
```

and my appsettings.json is
`"Management": {    
      "Endpoints": {
        "Exposure": {
          "Include": [ "*" ]
        }
      }
    }
  `
and appsettings.Development.json
`"Management": {
    "Endpoints": {
      "Exposure": {
        "Include": [ "*" ]
      }
    }
  }`
but when I call  from postman http://localhost:8080/actuator/refresh it the result is 
![image](https://user-images.githubusercontent.com/6517507/109703009-a566ed00-7b9d-11eb-836a-af8b72739484.png)

and in my webapi the new value is not reflected in the configuration but if I check the spring server values it is updated  
`http://localhost:8888/my-values/default` i see new values
I have tried to use `IOptionsMonitor<Logging>`  and also DI the `IConfiguration` both are not updated with new values

**Comment by TimHess** [comment]
Try using a `GET` request instead of `POST`.

I'm not sure why the verb isn't defined in the docs, but since there is no request body it makes the most sense to be `GET`

**Comment by iliya24** [comment]
HI
I tried to use post as per this tutorial `https://www.youtube.com/watch?v=yNnLICy2zk4&ab_channel=JavaBrains`
the name is "Dynamic config with spring Boot - Microservice configuration with Spring Boot [13]"
I tried to get as u suggested it returns some configurations and did update the values ;)
pls can u check the tutorial and see why in steeltoe it is different or why the post is not working , the body suppose to be empty again as in the tutorial above.

**Comment by TimHess** [comment]
As far back as I can recall, this endpoint has been setup for GET out of the box, but there is an `AllowedVerbs` config property that _should_ allow the actuator to listen for POST requests. Unfortunately that setting does not appear to be working with current version. This _could_ be related to changes during the transition to endpoint routing, but that's a guess at this point.

**Comment by patrickcbrown** [comment]
Hi, this appears to still be an issue, is there a plan to fix this so it aligns with Javas actuator/refresh behavior?

**Comment by thompson-tomo** [comment]
@TimHess with the changes in https://github.com/SteeltoeOSS/Steeltoe/commit/9dd18a23d6db5c735e4b868fd4ea240a63034b5e it appears to have been switched to the POST. Is there a need to back port the changes to v3. Note the changes in the above i would consider a breaking change as the current solution has removed the GET

**Comment by TimHess** [comment]
Right again @thompson-tomo, thanks for looking into this. It would be nice to ensure that developers have a choice of http verb as the configuration is documented to permit. Given the scope of that changeset I don't know offhand that it will be straightforward to backport anything, but if you have time and interest in making sure that POST can be configured for this actuator in v3 that would be appreciated
