### ISSUE TITLE
Validate support for Entity Framework 6.3.0 for Oracle drivers

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#619]
Oracle drivers do not currently support .NET 3.1 core and .NET 5.  Once available, needs to validated with EF Core 6.x

**Comment by TimHess** [comment]
Still not supported in `Oracle.ManagedDataAccess.EntityFramework v21.3.0`

**Comment by TimHess** [comment]
Closing this issue until such time as this scenario is supported by Oracle
