### ISSUE TITLE
PostgreSQL CloudFoundry SocketException (111)

### ISSUE THREAD

**Issue by matohoza** [SteeltoeOSS/Steeltoe#621]
## Describe the bug
With Steeltoe 3.0.2 the extension method IWebHostBuilder.AddCloudFoundryConfiguration has no effect. The application tries to connect to a database with some default values: '' (emptystring) on localhost:5432 (where nothing is listening).

## Steps to reproduce 
1. Create an ASP .NET Web Api project with PostgreSQL, Npgsql and Steeltoe
2. Add references:
3. Deploy application on CloudFoundry and bind a PostgreSQL DB Service
4. Access the database

## Expected behavior
Successful database access

## Environment:
 - Steeltoe.Connector.EFCore 3.0.2
 - Steeltoe.Extensions.Configuration.CloudFoundryCore 3.0.2
 - Platform: Cloud Foundry
 - OS: Linux
 - .NET Version .NET 5.0
 - Microsoft.EntityFrameworkCore 5.0.3
 - Npgsql.EntityFrameworkCore.PostgreSQL 5.0.2

## CF Application variables VCAP_SERVICES part
`VCAP_SERVICES=`
`{`
`  "postgresql-database": [`
`    {`
`      "label": "postgresql-database",`
`      "provider": null,`
`      "plan": "default",`
`      "name": "DBService",`
`      "tags": [],`
`      "instance_name": "DBService",`
`      "binding_name": null,`
`      "credentials": {`
`        "database": "dbservice",`
`        "external-hostname": "yyyyyyyyyyyyyyyyy.ch",`
`        "external-port": "30517",`
`        "external-replica-hostname": "",`
`        "external-replica-port": "",`
`        "hostname": "xxxxxx.dddd-postgresql.svc.cluster.local",`
`        "jdbcurl": "jdbc:postgresql://xxxxxx.dddd-postgresql.svc.cluster.local:5432/dbservice?user=999999&password=123456",`
`        "name": "dbservice",`
`        "password": "123456",`
`        "port": "5432",`
`        "replica-hostname": "",`
`        "replica-port": "",`
`        "uri": "postgresql://999999:123456@xxxxxx.dddd-postgresql.svc.cluster.local:5432/dbservice",`
`        "username": "999999"`
`      },`
`      "syslog_drain_url": null,`
`      "volume_mounts": []`
`    }`
`  ]`
`}`

## Log output
`fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]`
`      An error occurred using the connection to database '' on server 'tcp://localhost:5432'.`
`fail: Microsoft.EntityFrameworkCore.Query[10100]`
`      An exception occurred while iterating over the results of a query for context type 'TestApp.Net5DbContext'.`
`      System.InvalidOperationException: An exception has been raised that is likely due to a transient failure.`
`       ---> Npgsql.NpgsqlException (0x80004005): Exception while connecting`
`       ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused 127.0.0.1:5432`
`         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)`
`         at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)`

**Comment by TimHess** [comment]
Do you have a nuget reference for `Steeltoe.Connector.CloudFoundry`? This is a requirement when deploying to Cloud Foundry

**Comment by TimHess** [comment]
If adding the nuget reference did not resolve this issue, please feel free to re-open it
