### ISSUE TITLE
With 3.0.0 version of Steeltoe getting Socket Exception Error

### ISSUE THREAD

**Issue by standardissue** [SteeltoeOSS/Steeltoe#622]
Hi 

with latest version of Steeltoe , we are getting connection refused error. It was wroking fine previous version of Steeltoe . 
We are using linux container for pusing this to cloud. Below are the exception details.

An unhandled Mvc exception was encountered.","Exception":"System.Net.Http.HttpRequestException: Connection refused\n ---> 
System.Net.Sockets.SocketException (111): Connection refused\n at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port,
 CancellationToken cancellationToken)\n --- End of inner exception stack trace ---\n at System.Net.Http.ConnectHelper.ConnectAsync(String host, 
 Int32 port, CancellationToken cancellationToken)\n at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, 
 CancellationToken cancellationToken)\n at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken 
 cancellationToken)\n at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n at 
 System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n
 at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n at
 System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n at
 Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n 
 at Steeltoe.Common.Http.Discovery.DiscoveryHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n at
 Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n
 at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n at

**Comment by TimHess** [comment]
It looks like this stack trace is related to service discovery, but without more information the best I can do is speculate that you're missing a reference to `Steeltoe.Connector.CloudFoundry`.

Please provide (at least) the Steeltoe references you have in your .csproj, optionally the relevant parts of program.cs and startup.cs so that we know which packages you're using and how you're trying to use them

**Comment by standardissue** [comment]
I already have added Steeltoe.Connector.CloudFoundry.
![References](https://user-images.githubusercontent.com/3368897/110747899-9e2a8980-8204-11eb-9e37-5162e25c53bf.png)

Program.cs looks like as
 .UseCloudHosting()
                        .AddCloudFoundryActuators()
                        .AddCloudFoundryConfiguration()
                        .AddServiceDiscovery(options => options.UseEureka())
                        .UseStartup<Startup>();

In appsettings.json
{
  "AllowedHosts": "*",
   "spring": {
    "application": {
      "name": "vendordetail"
    }
  },
  "eureka": {
    "client": {
      "shouldRegisterWithEuerka": true
    },
    "instance": {
      "port": 5000,
      "nonSecurePortEnabled": false,
      "securePortEnabled": true,
      "appname": "vendordetail"
    }
  }
}

This service is getting registered with service discovery without an issue. We are getting above issue only when some other api is trying to call and they are not not able to connect this this service and getting Connection refused 111 error.

**Comment by TimHess** [comment]
Your settings are telling Steeltoe to register your app as listening for HTTPS connections on port 5000, which doesn't seem right for a Cloud Foundry environment. If that's not right when deployed, but is what you want locally, consider moving the settings that don't apply in the deployment environment over to appsettings.development.json

**Comment by standardissue** [comment]
Hi Tim
I have upgraded Steeltoe versions to 3.0.2 and added some proxy settings and now my problem has been resolved. Thanks for your assistance.
