### ISSUE TITLE
Deploy .NET archive (instead of docker image)  to SCDF

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#627]
SCDF has multiple options to deploy applications. All the supported file resolution types are here -> https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-register-stream-apps
Currently we only support docker with steeltoe and need to support a non-docker way.

**Comment by jkonicki** [comment]
Closing in favor of #646.
