### ISSUE TITLE
Investigate discrepancies between Steeltoe and Spring prometheus endpoints

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#634]
From reporter:
"Why is the prometheus output is not consistent with what comes out of Spring/Java.  My assumption is that this has a lot to do with .NET and how it works.  Question is, can the output be tweaked to be same or at least similar to what comes out of Spring?  We are trying to rationalize their monitoring of different apps.  "

**Comment by TimHess** [comment]
Closing due to insufficient interest. If you would like to see this supported, please respond to this issue.
