### ISSUE TITLE
Address build system flakiness 

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#635]
We use Azure DevOps on the free for OSS tier. Even without known availability issues, the tests often inexplicably fail without any information. Under resourced (CPU/Memory) agents may be the cause. When failures happen, the amount of visibility to underlying issue is generally low. We need to come up with ways to mitigate the problem. Possible solutions:
 - host our own agents for admin-level visibility. 
 - breaking down the tasks by namespace to be shorter running and yet be able to aggregate test coverage from multiple tasks.

**Comment by hananiel** [comment]
started tracking some of the crashes here: https://docs.google.com/spreadsheets/d/1S7iRK4Qw620K8cPxk2eOggYdPChraUG4uSikwFLWN9A/edit#gid=0

**Comment by jkonicki** [comment]
@hananiel Didn't we get past these issues?

**Comment by jkonicki** [comment]
In addition, we should not publish our test coverage unless the build passes

**Comment by TimHess** [comment]
> In addition, we should not publish our test coverage unless the build passes

Specifically, [#659](https://github.com/SteeltoeOSS/Steeltoe/pull/659/files#diff-7915b9b726a397ae7ba6af7b9703633d21c031ebf21682f3ee7e6a4ec52837a5R134) moved us from the deprecated `PublishBuildArtifacts` task to the newer `PublishPipelineArtifact`, where ["Deleting or overwriting Pipeline Artifacts is not currently supported"](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#artifacts-in-release-and-deployment-jobs). Using the condition `succeeded()` should be all that's needed to prevent artifact issues from failing a build on re-run if a test fails

**Comment by jkonicki** [comment]
Closing - #690 improved this, we can take a better look later if still a major problem
