### ISSUE TITLE
app.UseEndpoints should be called once in app

### ISSUE THREAD

**Issue by Lonli-Lokli** [SteeltoeOSS/Steeltoe#637]
## Describe the bug
app.UseEndpoints should not be called multiple times, see https://github.com/dotnet/aspnetcore/issues/17750#issuecomment-564508302

## Expected behavior
No additional calls to endpoints

## Environment (please complete the following information):
 - Steeltoe Version 2.3.0
 - Platform: CF
 - OS:  Windows
 - .NET Version .NET Core 3.1

**Comment by TimHess** [comment]
Unless I'm forgetting something, `UseEndpoints` isn't used at all in any 2.x version of Steeltoe and I believe we've already corrected issues in 3.x, can you point to something specific please?

**Comment by Lonli-Lokli** [comment]
Sorry, we are using 3.0.2.

Nevermind, I see similar (closed) https://github.com/SteeltoeOSS/Steeltoe/issues/497

Do you have pland to release https://github.com/SteeltoeOSS/Steeltoe/pull/591 ?
