### ISSUE TITLE
Steeltoe connectors are difficult to use and have inconsistent configuration approach

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/Steeltoe#638]
## Problem
Currently, Steeltoe connectors architecture creates a number of problems that make it very difficult to work with as a developer

1. Connectors configuration do not expose a native way of attaching multiple instances. For example, in `appsettings.json` we may have this.
``` json
{
  "MySql": {
    "Client": {
      "SslMode": "none",
      "ConnectionString": "Server=localhost;Database=steeltoe;Uid=steeltoe;Pwd=steeltoe;sslmode=none;"
    }
  }
}|
```
If my application wants to use more than one instance of MySQL, one has to resort to using the subset of CloudFoundry configuration syntax: 
```json
...
"services": {
        "local-mysql": [
            {
                "name": "myMySqlService",
                "credentials": {
                    "uri": "mysql://newuser0:password@localhost:3306/testdata"
                }
            },
            {
                "name": "myOtherMySqlService",
                "credentials": {
                    "uri": "mysql://newuser1:password@localhost:3306/moretestdata"
                }
            }
        ]
     }
...
```

This is not purely an expanded syntax but is in fact a very different way of expressing configuration as the second follows CloudFoundry service binding conventions. The content of `credentials` block is also not what is in shorthand format but uses very specific key names (`uri` as above)  and format (as can be seen by URI connection string syntax which is not the standard way of expressing connection strings). All this leaks heavy CloudFoundry configuration bias into the architecture and prevents making predictable configuration decisions as developers.

2. Currently, querying which services are "bound" to the app is only possible via expanded CF specific syntax (which relies on `ServiceInfo` objects. If one wanted to make decisions in code on the presence of binding, the long syntax has to be used.
3. The construction pipeline is unnecessarily complex. `ServiceInfoCreatorFactory` is used to locate alternative implementations of ServiceInfoCreatorFactory via assembly scanning. Each one is reflectively interrogated to see if it should become the primary creator with no order of precedence. This `ServiceInfoCreator` or alternative `CloudFoundryServiceInfoCreator` is then used to instantiate `ServiceInfoFactory` objects. There are environmental-specific logic such as requiring the presence of VCAP_SERVICES environmental variable even if config data itself is read from `IConfiguration` that also make it difficult to consistently replicate configuration reading without knowing all these *quirks*. Each creator then reads a `Service` class (which directly corresponds to a single CloudFoundry binding in it's data structure, even though it is meant to be generic), feeds it into a relevant factory, and creates ServiceInfo. Each connector now exposes a per secice type options class, that is populated from the relevant ServiceInfo via another factory class with the help of "configurer". Example:
https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Connectors/src/ConnectorBase/MySql/MySqlProviderConnectorFactory.cs
https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Connectors/src/Abstractions/Services/MySqlServiceInfo.cs
https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Connectors/src/ConnectorBase/MySql/MySqlProviderConnectorOptions.cs
https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Connectors/src/ConnectorBase/MySql/MySqlProviderConfigurer.cs
Which again used to configure a relevant concrete connection object. 

The above highlights a very high-level summary of a pipeline with a lot of branches, exceptions, and *quirks* that makes creating consistent and predictable results between what appears in configuration providers and how it is applied by connector very difficult for developers and nearly impossible to extend due to sheer complexity.

## Recommended high-level refactoring goals
Perform refactoring to produce clear architectural roles for objects that are 
1. Consistent with overall .NET configuration architecture (using Options pattern)
2. Perform a distinct functional role and a useful abstraction where necessary. Current code has too much redundancy between objects.
3. Simple to understand

Eliminate unnecessary fine graining of connection strings in strongly type object when it is not necessary (breaking things up into host, port, etc). This just brings confusion to straight forward cases where configuration should just be a single string.

## Recommended approach
1. Establish a baseline platform-neutral representation of each service type identified by type and name. Example:
``` yaml
Services:
  MySql:
  - Name: default
    ConnectionString: Server=myServerAddress;Port=3306;Option=131072;Stmt=;Database=myDataBase
  - Name: another
    ConnectionString: Server=myServerAddress;Port=3306;Option=131072;Stmt=;Database=anotherDb
```
2. Introduce an adapter configuration providers that convert service binding from one format into the standard steeltoe baseline. Such adapters would read platform-specific binding information (such as `vcap:services` block contributed by CloudFoundryConfigurationProvider) and convert it into the baseline format via their own configuration layer. As such as they act similarly to placeholder providers with conversion mapping rules hardcoded and expressed via what are now `ServiceInfoFactory` objects. The end result is that the configuration object will have a single *consistent* layer of configuration that will act as the source of all the service binding information.
3. Rename objects to express their true purpose. Ex
`Service` -> `CloudFoundryServiceBinding`
4. Make ServiceInfo objects inherit from Service (which represents generic binding with arbitrary json block). These should be bound by a single interface or a base class and not distinctly different objects. 
5. Remove things like `Tags` and `ServicePlan` from common service representation object (which is platform neutral) - those are CF / Open Service Broker specific concepts. We can still expose them via some kind of generic "Metadata" dictionary, similar to what all kubernetes objects have.
6. Move everything towards Options pattern, resolvable via DI. Maintain clear seperation of what is platform specific and what is connector neutral config, and allow resolution of each independently (technically CF binding becomes not a connector concept but a subset of CF config contributor). As such I can resolve something like IEnumerable<CloudFoundryServiceBinding> to get specific bindings as provide by vcap:services block or IEnumerable<ServiceInfo> which includes things that are platform-independent from `services` block, without any uri or CF specific format representation.

**Comment by bart-vmware** [comment]
I'm working on an extensive redesign of connectors in Steeltoe v4. Features:
- Universal configuration and API shape for single/multiple (named) service bindings.
- Leverage .NET connection strings (agnostic to the driver-specific parameters).
- Support CloudFoundry and Kubernetes/TAP service bindings, as well as local-only connection strings.
- (A small set of) known cloud-provided parameters are merged into the local connection string from `appsettings.json`. This delegates to driver-supplied [DbConnectionStringBuilder](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbconnectionstringbuilder#remarks) implementations.
- Provide injectable (named) `IOptions` that expose the merged connection string.
- Provide an injectable factory to obtain a (named) driver-specific connection/client instance (such as `NpgsqlConnection`, `IMongoClient`, `IConnectionMultiplexer`, etc).

High-level overview of the execution flow:
1. Read service bindings into cloud-agnostic configuration keys (for example: `steeltoe:service-bindings:postgresql:sampleServiceBindingName:username`), tailored to driver-specific connection string parameters. For example: `...:host` for PostgreSQL, but `...:server` for SQL Server.
a. A CloudFoundry configuration source reads from the `VCAP_SERVICES` environment variable and produces these keys.
a. A Kubernetes/TAP configuration source reads from secret files on disk and produces the same keys.
2. Take the produced keys and merge them into an optional local connection string using driver-provided builders. The resulting connection string is stored at another configuration key, such as: `steeltoe:service-bindings:postgresql:sampleServiceBindingName:ConnectionString`. If `appsettings.json` only contains the default connection string and there's a single named cloud service binding, then these are merged together (the actual conditions are more complex).
4. Register default/named `IOptions` that are connector-specific. For example, `PostgreSqlOptions` and `MySqlOptions` both derive from `ConnectionStringOptions`, but provide no additional typed properties.
5. Per connector type, a singleton factory is added to the service container. For example `ConnectorFactory<PostgreSqlOptions, NpgsqlConnection>` and `ConnectorFactory<RedisOptions, IConnectionMultiplexer>`. The factory provides a `Get(string? name)` method that returns an equivalently typed `Connector` that exposes the named `IOptions`, along with a method to obtain a driver-specific connection/client instance. Depending on the type of connector, this method either returns a new instance each time or caches the first one, based on documented best practices for the .NET driver.
6. Health contributors are registered accordingly.
8. During startup, a callback can be provided to instantiate the driver-specific connection/client instance and/or the health contributor. Both callbacks take an `IServiceProvider` to access additional dependencies (including the corresponding `IOptions` to obtain the connection string). For Entity Framework Core, a similar callback is available.

Example configuration for the default service binding using MySQL:
```json
  "Steeltoe": {
    "Client": {
      "MySql": {
        "Default": {
          "ConnectionString": "Server=localhost;Database=steeltoe;User=steeltoe;Password=steeltoe;Connection Timeout=15"
        }
      }
    }
  }
```

And for multiple named MySQL bindings:
```json
  "Steeltoe": {
    "Client": {
      "MySql": {
        "myMySqlServiceOne": {
          "ConnectionString": "Server=localhost;Port=3307;Database=db1;User=user1;Password=password1;Connection Timeout=20"
        },
        "myMySqlServiceTwo": {
          "ConnectionString": "Server=localhost;Port=3308;Database=db2;User=user2;Password=password2;Connection Timeout=25"
        }
      }
    }
  }
```

Support matrix:

| Service                                                           | Drivers                                                                                                                                                                                                      | Entity Framework Core                                                                                                                                                                      | Connection                                                                                                                                                                          | Platform     | Provider                                                                                                                                                                | Bindings                                                                                                                                                                   | Name                   |
| ----------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------- |
| [PostgreSQL](https://www.postgresql.org/)                         | [npgsql](https://www.nuget.org/packages/Npgsql)                                                                                                                                                              | [Npgsql.EntityFrameworkCore.PostgreSQL](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL)                                                                              | ([spec](https://www.npgsql.org/doc/connection-string-parameters.html))                                                                                                              | CloudFoundry | [VMware Tanzu Cloud Service Broker for Azure](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-index.html): PostgreSQL                | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-reference-azure-postgresql.html#binding-credentials-5))                         | csb-azure-postgresql   |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for GCP](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-GCP/1.2/csb-gcp/GUID-index.html): PostgreSQL                      | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-GCP/1.2/csb-gcp/GUID-reference-gcp-postgresql.html#binding-credentials-6))                               | csb-google-postgres    |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for AWS](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-index.html): PostgreSQL                      | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-reference-aws-postgres.html#binding-credentials-3))                                 | csb-aws-postgresql     |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | TAP          | PostgreSQL by Bitnami via [Services Toolkit](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/services-toolkit-install-services-toolkit.html)       | ([spec](https://github.com/spring-cloud/spring-cloud-bindings#postgresql-rdbms))                                                                                           | postgresql-unmanaged   |
| [MySQL](https://www.mysql.com/)                                   | [MySqlConnector](https://www.nuget.org/packages/MySqlConnector), [MySql.Data](https://www.nuget.org/packages/MySql.Data)                                                                                     | [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql), [MySql.EntityFrameworkCore](https://www.nuget.org/packages/MySql.EntityFrameworkCore) | ([spec](https://mysqlconnector.net/connection-options/)), ([spec](https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html#connection-parameters-base)) | CloudFoundry | [VMware SQL with MySQL for Tanzu Application Service](https://docs.vmware.com/en/VMware-SQL-with-MySQL-for-Tanzu-Application-Service/3.0/mysql-for-tas/index.html)      | ([spec](https://docs.vmware.com/en/VMware-SQL-with-MySQL-for-Tanzu-Application-Service/3.0/mysql-for-tas/use.html#mysql-environment-variables-9))                          | p.mysql                |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for Azure](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-index.html): MySQL                     | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-reference-azure-mysql.html#binding-credentials-4))                              | csb-azure-mysql        |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for GCP](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-GCP/1.2/csb-gcp/GUID-index.html): MySQL                           | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-GCP/1.2/csb-gcp/GUID-reference-gcp-mysql.html#binding-credentials-5))                                    | csb-google-mysql       |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for AWS](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-index.html): MySQL                           | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-reference-aws-mysql.html#binding-credentials-3))                                    | csb-aws-mysql          |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | TAP          | MySQL by Bitnami via [Services Toolkit](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/services-toolkit-install-services-toolkit.html)            | ([spec](https://github.com/spring-cloud/spring-cloud-bindings#mysql-rdbms))                                                                                                | mysql-unmanaged        |
| [SQL Server](https://www.microsoft.com/en-us/sql-server)          | [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient), [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient)                                           | [Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer)                                                                          | ([spec](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.connectionstring#remarks))                                                              | CloudFoundry | [VMware Tanzu Cloud Service Broker for Azure](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-index.html): MSSQL                     | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-reference-azure-mssql.html#binding-credentials-4))                              | csb-azure-mssql        |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | TAP          | N/A                                                                                                                                                                     | ([spec](https://github.com/spring-cloud/spring-cloud-bindings#sqlserver-rdbms))                                                                                            |                        |
| [CosmosDB](https://azure.microsoft.com/en-us/products/cosmos-db/) | [Microsoft.Azure.Cosmos](https://www.nuget.org/packages/Microsoft.Azure.Cosmos)                                                                                                                              | [Microsoft.EntityFrameworkCore.Cosmos](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos)                                                                                | N/A                                                                                                                                                                                 | CloudFoundry | [VMware Tanzu Cloud Service Broker for Azure](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-index.html): CosmosDB SQL API          | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-reference-azure-cosmosdb-sql.html#binding-credentials-3))                       | csb-azure-cosmosdb-sql |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | TAP          | N/A                                                                                                                                                                     |                                                                                                                                                                            |                        |
| [MongoDB](https://www.mongodb.com/)                               | [MongoDB.Driver](https://www.nuget.org/packages/MongoDB.Driver)                                                                                                                                              | N/A                                                                                                                                                                                        | ([spec](https://www.mongodb.com/docs/manual/reference/connection-string/))                                                                                                          | CloudFoundry | [VMware Tanzu Cloud Service Broker for Azure](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-index.html): CosmosDB Mongo API        | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-reference-azure-cosmosdb-mongo.html#binding-credentials-3))                     | csb-azure-mongodb      |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | TAP          | N/A                                                                                                                                                                     | ([spec](https://github.com/spring-cloud/spring-cloud-bindings#mongodb))                                                                                                    |                        |
| [RabbitMQ](https://www.rabbitmq.com/)                             | [RabbitMQ.Client](https://www.nuget.org/packages/RabbitMQ.Client)                                                                                                                                            | N/A                                                                                                                                                                                        | ([spec](https://www.rabbitmq.com/uri-spec.html))                                                                                                                                    | CloudFoundry | [VMware RabbitMQ® for Tanzu® Application Service™](https://docs.vmware.com/en/VMware-RabbitMQ-for-Tanzu-Application-Service/2.2/tanzu-rmq/GUID-index.html)              | ([spec](https://docs.vmware.com/en/VMware-RabbitMQ-for-Tanzu-Application-Service/2.2/tanzu-rmq/GUID-reference.html#vcapservices-0))                                        | p.rabbitmq             |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | TAP          | RabbitMQ by Bitnami via [Services Toolkit](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/services-toolkit-install-services-toolkit.html)         | ([spec](https://github.com/spring-cloud/spring-cloud-bindings#rabbitmq))                                                                                                   | rabbitmq-unmanaged     |
| [Redis](https://redis.io/)                                        | [StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis), [Microsoft.Extensions.Caching.StackExchangeRedis](https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis) | N/A                                                                                                                                                                                        | ([spec](https://stackexchange.github.io/StackExchange.Redis/Configuration.html))                                                                                                    | CloudFoundry | [Redis for VMware Tanzu Application Service](https://docs.vmware.com/en/Redis-for-VMware-Tanzu-Application-Service/3.1/redis-tanzu-application-service/GUID-index.html) | ([sample](https://docs.vmware.com/en/Redis-for-VMware-Tanzu-Application-Service/3.1/redis-tanzu-application-service/GUID-using.html#use-the-redis-service-in-your-app-13)) | p-redis                |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for Azure](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-index.html): Redis                     | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-Azure/1.4/csb-azure/GUID-reference-azure-redis.html#binding-credentials-3))                              | csb-azure-redis        |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for GCP](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-GCP/1.2/csb-gcp/GUID-index.html): Redis (beta)                    | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-GCP/1.2/csb-gcp/GUID-reference-gcp-redis.html#binding-credentials-2))                                    | csb-google-redis       |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | CloudFoundry | [VMware Tanzu Cloud Service Broker for AWS](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-index.html): Redis                           | ([spec](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-reference-aws-redis.html#binding-credentials-3))                                    | csb-aws-redis          |
|                                                                   |                                                                                                                                                                                                              |                                                                                                                                                                                            |                                                                                                                                                                                     | TAP          | Redis by Bitnami via [Services Toolkit](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/services-toolkit-install-services-toolkit.html)            | ([spec](https://github.com/spring-cloud/spring-cloud-bindings#redis))                                                                                                      | redis-unmanaged        |
