### ISSUE TITLE
PlaceholderResolver should allow null resolution if key is not present

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#674]
Consider the assertion below : https://github.com/SteeltoeOSS/Steeltoe/blob/9600ed0dc6f34813fc83b4a6111376655861abcd/src/Configuration/test/PlaceholderCore.Test/PlaceholderServiceCollectionExtensionsTest.cs#L60

It would be better to resolve to <null>. Second, we have a mechanism to provide a default value but no way to specify null as the default value.

**Comment by jkonicki** [comment]
We should ensure that we are following something similar to the Spring property placeholder.  Needs to be investigated.

**Comment by TimHess** [comment]
Should be resolved by #1135
