### ISSUE TITLE
CONTRIBUTING.md link pints to defunct branch

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Steeltoe#677]
In the site README, the `CONTRIBUTING.md` link points to:
```
https://github.com/SteeltoeOSS/.github/blob/master/CONTRIBUTING.md
```
 
Expected/suggested link:
```
https://github.com/SteeltoeOSS/.github/blob/main/CONTRIBUTING.md
```

**Comment by jkonicki** [comment]
Fixed in https://github.com/SteeltoeOSS/Steeltoe/commit/8e8490c2bd5e0e443bbd5ab26faf2937f7aa8099
