### ISSUE TITLE
Missing `.ConfigureAwait(false)` in all await call

### ISSUE THREAD

**Issue by pengweiqhca** [SteeltoeOSS/steeltoe#70]
Missing `.ConfigureAwait(false)` could be deadlocks  in asp.net when call async method in sync method.

https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
https://blogs.msdn.microsoft.com/alazarev/2017/05/20/fun-with-configureawait-and-deadlocks-in-asp-net/
https://medium.com/rubrikkgroup/understanding-async-avoiding-deadlocks-e41f8f2c6f5d
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

**Comment by TimHess** [comment]
I think we got all them all, thanks for your contribution!
