### ISSUE TITLE
Possible exception on configuration reload - Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by mzakrzewski** [SteeltoeOSS/Steeltoe#704]
## Describe the bug
I'm currently researching an invalid operation exception in an application when binding configuration. I haven't conclusively narrowed it down but my research so far raises concern for how the ConfigServerConfigurationProvider is implemented. This application is using env variables, cloud foundry configuration and config server configuration providers.

Based on changes made in the framework configuration providers (i.e. https://github.com/dotnet/extensions/pull/1202), and seeing that the `AddConfigServerClientSettings` method in `ConfigServerConfigurationProvider` is directly changing the `Data` dictionary, I believe there is the potential that a configuration reload() could result in an InvalidOperationException.

To my knowledge, we're not calling Reload() on configuration when this is being encountered, but I thought it best to let you know that there may be an issue with how this is implemented: https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs#L422

## Expected behavior
I would expect a call to reload configuration would not throw an invalid operation exception because a collection has been modified.

## Environment (please complete the following information):
 - Steeltoe Version: 3.0.2
 - Platform: Cloud Foundry 
 - OS: Linux
 - .NET Version: .net core 3.1.13 
 - Any other library versions to note: N/A

**Comment by TimHess** [comment]
Quick investigation reveals that the potential for this kind of issue was removed in #185 but then reintroduced by #270 ... looks like a bug to me, @mzakrzewski do you want to submit a PR?

**Comment by mzakrzewski** [comment]
Yep, I'll submit a PR; hopefully this week. Thanks.
