### ISSUE TITLE
[GitInfoContributor] commit time is not human readable

### ISSUE THREAD

**Issue by DaviGia** [SteeltoeOSS/Steeltoe#706]
## Is your feature request related to a problem? Please describe.
The _GitInfoContributor_ transforms the `git.commit.time` into a timestamp (in general any value associated to a key named "time"). This appears to be done on purpose (see permalink below), so I don't know if it's needed for a specific case. Nonetheless the timestamp is not human readable as the ISO8601 data representation. Currently Spring does not perform this value transformation and from SpringBootAdmin this value does not seem to be processed at all. The result is that SBA shows `git.commit.time` value with different formats:

``` sh
# spring
2021-06-28T07:46:08Z
# steeltoe
1624613217000
```

## Describe the solution you'd like
In my opinion datetime values retrieved from this actuator should always be sent using a human readable format. In any case using ISO8601 format will result in a value that it's both human and machine readable. 

## Additional content
Here is the custom code that performs the value transformation:

https://github.com/SteeltoeOSS/Steeltoe/blob/9322d0627673c9c96d71b584d190284649c4005d/src/Management/src/EndpointBase/Info/Contributor/GitInfoContributor.cs#L84-L99

**Comment by TimHess** [comment]
@DaviGia thanks for pointing this out. I can't find any reason there should be a mismatch between Steeltoe and Spring here, I'm not sure why the code is that way today. We'd be happy to accept a PR for the fix if you're willing

**Comment by DaviGia** [comment]
> @DaviGia thanks for pointing this out. I can't find any reason there should be a mismatch between Steeltoe and Spring here, I'm not sure why the code is that way today. We'd be happy to accept a PR for the fix if you're willing

I've created the PR.
