### ISSUE TITLE
Profiles in Bootstrapper

### ISSUE THREAD

**Issue by ddieruf** [SteeltoeOSS/Steeltoe#721]
## Is your feature request related to a problem? Please describe.
Nope

## Describe the solution you'd like
Have the concept of profiles in Bootstrapper, where it uses the ASPNET_ENVIRONMENT to apply an opinion on how to configure a component.

It ends up being a matrix of a given component's default values compared to different environments and deciding how the default should be changed.

## Describe alternatives you've considered
I haven't

## Additional context
Thinking about management endpoints, depending on your environment you may want them all exposed or only a few. If I am developing then I want them all available. If I am in staging then I only want relevant debugging endpoints available. If in production then I don't want anything exposed.

Thinking of logging levels, in development I want the Steeltoe.* packages at an `information` level but in production I want them at an `error` level.

**Comment by TimHess** [comment]
This is an interesting idea, but seems like it could get very complicated very quickly and would have a pretty broad impact on Steeltoe if we were to do it well. I don't see it as a priority at this time as I don't see a realistic way to accomplish the goals. 

Feel free to reopen the issue with additional context, use cases, or ideas about how to accomplish these or related ideas.
