### ISSUE TITLE
AddDynamicSerilog do not inject IDiagnosticContext

### ISSUE THREAD

**Issue by DaviGia** [SteeltoeOSS/Steeltoe#726]
## Describe the bug
`.AddDynamicSerilog()` extension method do not inject `IDiagnosticContext`. That is a difference with `.UseSerilog()` method and  causes `IApplicationBuilder.UseSerilogRequestLogging()` (Serilog.AspNetCore) method to throw exception because no IDiagnosticContext is found.

## Steps to reproduce 
1. Create a basic aspnetcore microservice
2. Add `Steeltoe.Extensions.Logging.DynamicSerilogBase` and `Serilog.AspNetCore` packages
3. Use Steeltoe Autoconfig or .AddDynamicSerilog in Program.cs:

``` cs
return builder
                //.AddDynamicSerilog((builderContext, loggerConfig) =>
                //{
                //    // Read Serilog configuration
                //    loggerConfig.ReadFrom.Configuration(builderContext.Configuration);
                //})
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
                .AddSteeltoe(loggerFactory: initLoggerFactory);
```
4. Add Serilog request logging middleware in Startup.cs:
``` cs
public void Configure(IApplicationBuilder app, IHostEnvironment env)
{
    app.UseSerilogRequestLogging();
}
```

## Expected behavior
`AddDynamicSerilog` should inject `IDiagnosticContext`. In general I think that `AddDynamicSerilog` should emulate `UseSerilog` logic as much as possible.

## Environment (please complete the following information):
 - Steeltoe 3.1.0
- OS: Windows
- .NET Core 3.1.0
- Serilog.AspNetCore 4.1.0

## Additional content
- [Serilog.AspNetCore IDiagnosticContext creation](https://github.com/serilog/serilog-aspnetcore/blob/094f15cb9b12790a3fd040d603dd3042e5f92c4d/src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs#L150)

**Comment by hananiel** [comment]
@DaviGia I looked at this a little. I am not sure we can support this in our repo. The best thing to do might be to add this yourself - something like this: 
```
                var diagnosticContext = new Serilog.Extensions.Hosting.DiagnosticContext(null);

                // Consumed by e.g. middleware
                builder.Services.AddSingleton(diagnosticContext);

                // Consumed by user code
                builder.Services.AddSingleton<IDiagnosticContext>(diagnosticContext);
```
This would have to be tested. If you can think of a way to do this in steeltoe without taking further dependencies, please submit a PR.

**Comment by hananiel** [comment]
You could consider asking serilog to make this [method ](https://github.com/serilog/serilog-aspnetcore/blob/094f15cb9b12790a3fd040d603dd3042e5f92c4d/src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs#L139)public.

**Comment by DaviGia** [comment]
> This would have to be tested. If you can think of a way to do this in steeltoe without taking further dependencies, please submit a PR.

My temporary fix to make it work was pretty much identical to your proposal, i.e.:

``` cs
//# Startup.cs ConfigureServices
// Attach DiagnosticContext for SerilogRequestLoggingMiddleware
var diagnosticContext = new DiagnosticContext(null);
services.AddSingleton(diagnosticContext);
services.AddSingleton<IDiagnosticContext>(diagnosticContext);
```

So I can confirm that it works just fine.

> You could consider asking serilog to make this method public.

I will consider it. Thank you for now.

**Comment by jkonicki** [comment]
Closing as there is no work on Steeltoe side, need to address this in Serilog or use workaround.
