### ISSUE TITLE
How to use jwt authentication without username and password

### ISSUE THREAD

**Issue by yhjhoo** [SteeltoeOSS/Steeltoe#73]
In the example of jwt authentication, it configures both client Id and client secret which I don't want. 

Is there some similiar configuration like "security.oauth2.resource.jwt.key-uri" in spring-boot?

**Comment by jkonicki** [comment]
No, we don't have that option available in Steeltoe.

**Comment by yhjhoo** [comment]
that's very bad news. Good to hear MS provide this thing. tks for the help

**Comment by jkonicki** [comment]
Hi @yhjhoo,  It was not my original intention to close this ticket.  So, I am going to reopen this as hopefully you or someone in the community would like to contribute something that would satisfy this request.  This is currently not a team priority, but we are willing to assist in helping with a solution.

**Comment by TimHess** [comment]
This should be a function of the ASP.NET Core JWT auth library, I do not see anything for Steeltoe to do here
