### ISSUE TITLE
.Net Core Dockerized WebAPI failing to register with Eureka server

### ISSUE THREAD

**Issue by Ed87** [SteeltoeOSS/Steeltoe#730]
I have a .Net Core 3.1 WebAPI running as a Docker container + Eureka server running as Docker also. When I run the API from Visual Studio it registers successfully with the Eureka Docker instance and I can see the service in Eureka console. But once I dockerize the API and run it I am getting connection error as below :

`fail: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
productsapi_1   |       RegisterAsync Failed
productsapi_1   | System.Net.Http.HttpRequestException: Connection refused
productsapi_1   |  ---> System.Net.Sockets.SocketException (111): Connection refused
productsapi_1   |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
productsapi_1   |    --- End of inner exception stack trace ---
productsapi_1   |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
......
productsapi_1   |    at Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient.RegisterAsync(InstanceInfo info)
productsapi_1   | fail: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
productsapi_1   |       Register Failed
productsapi_1   | System.Net.Http.HttpRequestException: Connection refused
productsapi_1   |  ---> System.Net.Sockets.SocketException (111): Connection refused
productsapi_1   |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
productsapi_1   |    --- End of inner exception stack trace ---
productsapi_1   |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
.....
productsapi_1   |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
productsapi_1   |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean 
disposeCts)
productsapi_1   |    at Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient.RegisterAsync(InstanceInfo info)
productsapi_1   |    at Steeltoe.Discovery.Eureka.DiscoveryClient.RegisterAsync()
productsapi_1   | info: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
productsapi_1   |       Registartion fail. HeartBeat not start
productsapi_1   | fail: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
productsapi_1   |       DoGetApplicationsAsync Failed
productsapi_1   | System.Net.Http.HttpRequestException: Connection refused
productsapi_1   |  ---> System.Net.Sockets.SocketException (111): Connection refused
.....`

This is after running docker-compose up.Eureaka and API containers are both up but the service does not seem to be registering. This is how my WebAPI looks like :

Startup.cs

`public void ConfigureServices(IServiceCollection services)
    {
        .....       
        services.AddDbContext<ApplicationDbContext>(o => o.UseMySql(Configuration.GetConnectionString("mysqlconnection")));
        services.AddDiscoveryClient(Configuration);
    }
    
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {        
       .....
        app.UseHttpsRedirection();
        app.UseRouting();
        app.UseAuthorization();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
        app.UseDiscoveryClient();
    }`

Docker compose

`version: '3.4'
services:
  productsapi:
    build: .
    ports: 
      - "5050:5000"
    depends_on:
      - eurekaserver
   
  eurekaserver:
    image: steeltoeoss/eureka-server:latest
    ports:
      - '8761:8761'`

Appsettings.json

` {
     ...
  "AllowedHosts": "*",
  ...
  "eureka": {
    "client": {
      "shouldRegisterWithEureka": true,
      "serviceUrl": "http://eurekaserver:8761/eureka",
      "ValidateCertificates": false
    },
    "instance": {
      "appName": "ProductService",
      "port": "5050",
      "hostName": "localhost"
    }
  }
}`

What am I missing ?

## Environment :
 - .Net Core 3.1 
 - Steeltoe.Discovery.ClientCore 2.1.1
 - Docker Engine - Community Ver  20.10.6 + WSL2 
-  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

**Comment by ccheetham** [comment]
I think it's because even though you have in your Docker compose:
```
depends_on:
  - eurekaserver
```

your Eureka client `producsapi` is attempting to connect to the Eureka service before it's listening on its port.  From Docker compose's perspective, the service is available even though it may be a several seconds before the service has fully started and is accepting connections.

Here's a solution to this problem:

     https://github.com/vishnubob/wait-for-it

From the above's docs, it's a "script that will wait on the availability of a host and TCP port."

You can see an example of its use in this `docker-compose.yaml`:

    https://github.com/steeltoeoss-incubator/InitializrWorkspace/blob/main/docker-compose.yaml#L23

**Comment by TimHess** [comment]
Steeltoe 2.1.1 is nearly 3 years old and pre-dates .NET Core 3.1, is that a typo? If that's accurate, the first thing to do would be upgrade to a newer version. 

After confirming the Steeltoe version, my next question is how much time are you giving it to register? `docker-compose up` won't wait for Eureka to be up before starting the .NET app(s), so they won't be able to register until the next heartbeat cycle (30 second interval by default)

I just opened a PR that [updates the sample app to .net core 3.1](https://github.com/SteeltoeOSS/Samples/pull/215), so you may want to see if that runs for you.

**Comment by Ed87** [comment]
+1 @TimHess  finally got it working with  this [https://github.com/SteeltoeOSS/Samples/pull/215](url) tweak. My appsettings.json looks like this : 
`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "mysqlconnection": "server=mysqldata;port=3306;database=ProductsDB;userid=dbuser;password=Ithu@1111;"
  },
  "PaymentsServiceUri": "http://PaymentService/api/payment",
  "spring": {
    "application": {
      "name": "ProductService"
    }
  },
  "eureka": {
    "client": {
      "shouldRegisterWithEureka": true,
      "serviceUrl": "http://eurekaserver:8761/eureka",
      "ValidateCertificates": false,
      "RegistryFetchIntervalSeconds": "15"
    },
    "instance": {
      "appName": "ProductService",
      "port": "5050",
      "hostName": "localhost",
      "LeaseRenewalIntervalInSeconds": "15"
    }
    }
  }

`

**Comment by Ed87** [comment]
How do I re-use the running Eureka container so that I register additional instances on it. I have a second microservice with docker-compose as below but when I run docker-compose up Docker attempts to spin up another container for Eureka and complains that "Port is already in use"  .
Docker-compose

`version: '3.4'
services:
  paymentsapi:
    build: .
    ports: 
      - "5040:5000"
    depends_on:
      - mysqldata
       - eurekaserver
   
  eurekaserver:
    image: steeltoeoss/eureka-server:latest
    ports:
      - '8761:8761'
       

  mysqldata:
    image: mysql:5.7
    ports:
      - '33306:3306'
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: PaymentsDB
       MYSQL_USER: xxxx
       MYSQL_PASSWORD: xxxx
    volumes:
       - dbdata:/var/lib/mysql
    

volumes:
    dbdata:`
