### ISSUE TITLE
Why does test Steeltoe.Common.Security.Test.ConfigurationExtensionsTest::ConfigurationExtensionsTest fail when using Sandbox

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Steeltoe#736]
Prior to Sandbox, the test arrangement was:

```
var filename = "fakeCertificate.p12";
await File.WriteAllTextAsync(filename, "cert1");
```

When the test arrangement is rewritten to use a Sandbox. it fails:

```
using var sandbox = new Sandbox();
var filename = sandbox.CreateFile("fakeCertificate.p12", "cert1");
```

It seems the test should succeed with either arrangement.  A notable difference in the arrangements is that the prior arrangment filename is a relative path, whereas the Sandbox arrangement filename is an absolute path.

**Comment by bart-vmware** [comment]
Related issue: #1314.

**Comment by TimHess** [comment]
#1306 re-worked `CertificateOptions` to consistently bind certificates at the `IOptions` layer rather than doing anything other than path management in `IConfiguration` and this is no longer an issue (all related tests are using Sandbox now)
