### ISSUE TITLE
Update RabbitMQ.Client to 6.2.2

### ISSUE THREAD

**Issue by lxw2016** [SteeltoeOSS/Steeltoe#749]
We want to monitor the application with AppDynamics, per AppDynamics, in order to monitor it in linux container, it has to be rabbitmq.client v6+, right now the Steeltoe.Messaging.RabbitMQ is v5.1.2.

Change the refrenced package of RabbitMQ.Client from 5.1.2 to 6.2.2

**Comment by jkonicki** [comment]
Originally RabbitMQ client 6.x was not working as expected, so we held off on the update.  We should now take a closer look to see if we can get past some of the issues.
