### ISSUE TITLE
Add support for RabbitMQ Quorum Queue

### ISSUE THREAD

**Issue by dtillman** [SteeltoeOSS/Steeltoe#775]
RabbitMQ has add a new HA queue call a Quorum Queue.  We need to add support

**Comment by dmitrynovik** [comment]
Any work done on this issue?
I am doing a demo on Steeltoe Streams and it creates a classic exclusive Rabbit queue. I want to create a Quorum Queue.

**Comment by TimHess** [comment]
Hi @dmitrynovik,

Unfortunately, we have not yet worked on this issue and do not currently know the level of effort required to complete the work.
