### ISSUE TITLE
Improve Eureka Startup Experience

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#786]
Most developers expect the startup experience for service discovery to be pretty smooth and fast, even when starting Eureka and multiple services at the same time. It is mysterious for new developers and/or feels like a waste of time to have to wait a minute or more for everything to be running and for registry lookups to work. Consider alternative retry procedures (or timings) during startup and/or more helpful logging when things don't go right.

See #785 or [this SO question](https://stackoverflow.com/questions/68475246/net-core-dockerized-webapi-failing-to-register-with-eureka-server/68518241) for examples

**Comment by bart-vmware** [comment]
We can:
- Improve the Steeltoe docker image (see https://github.com/SteeltoeOSS/Dockerfiles/issues/33)
- In the sample, lower the value for `Eureka:Instance:LeaseRenewalIntervalInSeconds` so that heartbeats/re-registrations run more often
- Mention these in the documentation

**Comment by bart-vmware** [comment]
See also: https://blogs.asarkar.com/technical/netflix-eureka/
