### ISSUE TITLE
Use 'StringBuilder.Append(char)' instead of 'StringBuilder.Append(string)' when the input is a constant unit string

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#792]
Fix all [CA1834](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1834) complaints

This should only be applied in `main` and does not need to be backported

**Comment by anmol-Git** [comment]
I will like to work on this issue , Can you Please assign this issue to me.

**Comment by TimHess** [comment]
Sorry @anmol-Git, it looks like @NemrudDemir already completed the work in #793
