### ISSUE TITLE
Allow /refresh to complete without returning contents of configuration

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#810]
The contents of IConfiguration could be very large in some cases, resulting in less than ideal response times for calls to /refresh.

It would be nice if there was a way to prevent the contents from being returned. The toggle should live in `IRefreshOptions` and the default behavior should be to return contents. If the switch is turned off, a single item should be returned that indicates returning IConfiguration content has been disabled.

**Comment by Vadimur** [comment]
#811
