### ISSUE TITLE
Actuators not working in Kubernetes

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Steeltoe#813]
## Describe the bug
The code at [k8sSteelToe NET -6 branch](https://github.com/VenkateshSrini/K8sSteelToe/tree/NET-6) is coded with SteelToe and uses SteelToe.management with spring boot admin server. After incorporating the steeltoe management endpoints, the endpoint http://localhost:5000/actuators work as expected when running from local. But when the app is hosted in Kubernetes the endpoints are not accessible. The kubernetes Admin server client end point and application base URL are configured using the secrets

## Steps to reproduce 
1. First get the code from the URL (https://github.com/VenkateshSrini/K8sSteelToe/tree/NET-6). Run it locally. Then access it using http://localhost:5000/actuators. The application works as expected
2. Deploy the [service account](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/src/service-account.yaml). Then deploy the [config map](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/src/configmap.yml) [Admin server client configuration](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/src/SpringbootServerAdminUrConfigMap.yml) [Admin server call back Uri](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/src/SpringBootAdminCallback.yml) [application secrets](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/src/Secrets.yml) [Admin server](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/src/SpringBootAdmin.yaml).
3. Then deploy the application [deployment.yaml](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/deployment/k8sconfig-deployment.yaml) and [service.yaml](https://github.com/VenkateshSrini/K8sSteelToe/blob/NET-6/deployment/k8sconfig-service.yaml) on any kubernetes cluster. The k8sconfig service is deployed in the local cluster and is exposed in port 5046. SO when we access the port http://localhost:5046/actuator we get http status code 404. 

## Expected behavior
The actuator endpoint should get displayed as it is done when running application in debug mode

## Environment (please complete the following information):
 - Steeltoe Version :3.1.0
 - Platform: Single node Kubernetes cluster that comes with Docker 
 - OS: local debugging windows 11. Hosted in Linux docker 
 - .NET Version :.NET 6
 - Any other library versions to note

## Screenshots
as attached herewith

## Additional context or links
**local**
<img width="951" alt="local" src="https://user-images.githubusercontent.com/1167152/143898919-afebd869-9aee-404d-857e-cb1ec3e2b258.png">
**docker hosted**
<img width="930" alt="Docker hosted  png" src="https://user-images.githubusercontent.com/1167152/143899079-718d76b4-9f24-4eb8-90e9-fc5062614850.png">
 problem here.

**Comment by TimHess** [comment]
Hi @VenkateshSrini,
Have you tried the sample [here](https://github.com/SteeltoeOSS/Samples/tree/main/Management/src/Kubernetes)? Everything there seems to be working fine for me on .NET Core 3.1 and .NET 6 with Steeltoe 3.1.0 or 3.1.1

**Comment by VenkateshSrini** [comment]
@TimHess ,

Sorry for the delayed update here. I was able to get it working. When I hosted on the docker I had to use HTTP://host.docker.internal:portname. I'm not sure why it does not work if just simple provide HTTP://localhost:port name. If possible could you please explain me that

**Comment by TimHess** [comment]
@VenkateshSrini, in order to use `localhost` in docker/k8s, the applications would need to be running within the same container. Since Spring Boot Admin is in one container and the app is in another, you need to use a different hostname (like host.docker.internal)

**Comment by VenkateshSrini** [comment]
@TimHess . I get it. But however, if we want to see the UI of the spring boot admin server or the API hosted container, it is still accessible using the UI HTTP://localhost:<port>. How does that work then? Is this confusion comes only when accessing the intercluster communication

**Comment by TimHess** [comment]
@VenkateshSrini your browser is operating from the host level, the machine knows how to translate the request (via NAT) into the internal docker network

**Comment by VenkateshSrini** [comment]
@TimHess Thanks for answering all my queries. One last query, when I host this application in AKS or EKS, how should I give the address, will it be the service name and the port  that is got as an output of `kubectl get svc` command or will it be something else.

**Comment by TimHess** [comment]
@VenkateshSrini you're welcome. When your app is running in the same namespace, you should be able to use [Kubernetes' built-in DNS](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)

**Comment by VenkateshSrini** [comment]
@TimHess, Thanks you very much
