### ISSUE TITLE
Update config server provider for .NET 6

### ISSUE THREAD

**Issue by stamahto** [SteeltoeOSS/Steeltoe#814]
## Is your feature request related to a problem? Please describe.
Extension "AddConfigServer()" don't exists on builder, which is type: WebApplicationBuilder in .Net 6 (used to be: IHostBuilder in previous versions).

## Describe the solution you'd like
Update configServer extension to type WebApplicationBuilder.

## Additional context
.Net 6 has a new approach for building project. The startup class no longer exists and everything has been moved to program.cs, and the data type for the builder has changed. This is why the extension for the AddConfigServer() method no longer works.

![image](https://user-images.githubusercontent.com/57343418/141104637-1fe7bca1-b800-4c0d-b079-16475c90e617.png)

**Comment by TimHess** [comment]
`AddConfigServer` should still work just fine when you use `WebApplication.CreateBuilder().Configuration.AddConfigServer()`, but additional extensions should be added for all Steeltoe config providers. This would be a good candidate for a PR for anybody interested
