### ISSUE TITLE
Communication between Spring boot admin server and SteelToe Management actuators to use gRpc

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Steeltoe#817]
## Is your feature request related to a problem? Please describe.
There are two kinds of deployment that are possible with Spring boot admin server and .NET core SteelToe apps. Sometimes it would be in the same cluster and in some scenario it would be deployed on separate cluster other than apps. In all the cases we would like to have the spring boot admin server and SteelToe Actuator use gRpc to communicate rather than rest. 
## Describe the solution you'd like
SteelToe apps can communicate with SpringBoot Admin server using Steel Admin client library and steel toe actuator. The feature we are asking here is that we that communication to be able to happen on gRpc. When getting the details of admin client details, there should be an additional option to state whether the access should be based on Http or gRpc. The admin server should also expose two endpoints one for Http access and another for gRpc access. When running in the same cluster we could use the gRpc endpoint whereas when running in a heterogeneous cluster Http could be a good option without any tweaking to LLB or any other additional gateway configurations.

## Describe alternatives you've considered
None

**Comment by TimHess** [comment]
@VenkateshSrini does Spring Boot Admin support gRPC? I'm not finding any information on support from that end

**Comment by VenkateshSrini** [comment]
@TimHess. I see this project https://github.com/yidongnan/grpc-spring-boot-starter and hence assumed that Spring boot admin server has now started supporting gRpc

**Comment by VenkateshSrini** [comment]
@TimHess  I have raised a feature request also here [Spring boot admin server with gRpc endpoints](https://github.com/codecentric/spring-boot-admin/issues/2131)

**Comment by TimHess** [comment]
Hi @VenkateshSrini,
Seeing the response to the linked issue , it looks like there's not much for us to do here, sorry. If either Spring Boot or SBA adds support in the future we can revisit, but I'm going to close this issue for now

**Comment by VenkateshSrini** [comment]
@TimHess The Spring boot admin server is expecting the actuator teams to publish a proto that they can use to gather the data and put it up on a pleasing UI. So from SteelToe the proto has to be published is my understanding.
