### ISSUE TITLE
Consider an IEndpointRouteBuilderExtensions.MapAllActuators that takes no parameters

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#827]
Currently MapAllActuators forces you to pass an Action for ConventionBuilder or null. See [SO issue](https://stackoverflow.com/questions/71163854/why-is-endpoints-mapallactuators-failing)

**Comment by stamahto** [comment]
I would also appreciate it 👍

**Comment by bart-vmware** [comment]
This was implemented in #1155.

**Comment by bart-vmware** [comment]
It's in the 4.x line, which hasn't been released yet.
