### ISSUE TITLE
await _discoveryBase.LookupServiceAsync(current).ConfigureAwait(false)

### ISSUE THREAD

**Issue by the-king-z** [SteeltoeOSS/Steeltoe#832]
DiscoveryHttpMessageHandler.cs
It can work well without ConfigureAwait(false), but it is easy to report errors
![image](https://user-images.githubusercontent.com/88300903/159985725-cd1d8dc6-8e61-47ac-a166-9daecf86317a.png)
https://devblogs.microsoft.com/dotnet/configureawait-faq/

**Comment by TimHess** [comment]
Steeltoe is general-purpose library code. Recommendation per that link...

> This leads to the general guidance of: if you’re writing general-purpose library code, use `ConfigureAwait(false)`. This is why, for example, you’ll see every (or almost every) await in the .NET Core runtime libraries using `ConfigureAwait(false)` on every `await`; with a few exceptions, in cases where it doesn’t it’s very likely a bug to be fixed. For example, _this PR_ fixed a missing `ConfigureAwait(false)` call in HttpClient.
