### ISSUE TITLE
Metrics causing high/increasing CPU consumption

### ISSUE THREAD

**Issue by christianerbsmehl** [SteeltoeOSS/Steeltoe#833]
## Describe the bug
Hi there, we are experiencing a strange behavior with our apps since we switched from Steetoe 2 to Steeltoe 3. CPU consumption seems to be increasing steadily over time, even if there is literally zero traffic on our apps (which is mostly the case overnight).

I tried to narrow it down and found out that this problem vanishes if we completely disable metrics aggregation for our apps. Since there is no convenient way of doing so (disabling metrics endpoint does not prevent subscription to metrics), I looked up [the source](https://github.com/SteeltoeOSS/Steeltoe/blob/f1ba2c1ba9bc3b94d446e595b142df219211b0c1/src/Management/src/EndpointCore/ActuatorServiceCollectionExtensions.cs) and enabled all actuators except `Metrics` and `Prometeus`.

Code looks like the following (CORS configured elsewhere):

```csharp
// in ConfigureSerivces()

services.AddActuatorManagementOptions(Configuration);
services.AddCloudFoundryActuator(Configuration);
services.AddEnvActuator(Configuration);
services.AddHealthActuator(Configuration);
services.AddHeapDumpActuator(Configuration);
services.AddHypermediaActuator(Configuration);
services.AddInfoActuator(Configuration);
services.AddMappingsActuator(Configuration);
services.AddLoggersActuator(Configuration);
services.AddTraceActuator(Configuration);
services.AddRefreshActuator(Configuration);
 
if (Platform.IsWindows)
{
    services.AddThreadDumpActuator(Configuration);
}

// in Configure()

endpoints.Map<CloudFoundryEndpoint>();
endpoints.MapAllActuators(null);
```

## Steps to reproduce 
1. Create an app with .NET Core 3.1 and enable all actuators
2. Deploy app (to foundation without Prometheus endpoint, see below) and see CPU consumption increase over time

## Expected behavior
CPU load should be near zero if there is no traffic on the app.

## Environment (please complete the following information):
 - Steeltoe Version: 3.1.3
 - Platform: PCF/Tanzu 2.11.15
 - OS: Linux
 - .NET Version: .NET Core 3.1 (Buildpack 2.3.38)
 - Appdynamics Buildpack v5.0.166 / Agent 21.12.1

## Screenshots
CPU% of app with metrics / Prometheus:
![image](https://user-images.githubusercontent.com/48787792/160347731-91b8c7d4-58d9-4410-83f0-1a103c20a84d.png)

CPU% of app without metrics / Prometheus:
![image](https://user-images.githubusercontent.com/48787792/160352122-95f3129a-6f3d-4212-878d-103a4906dea4.png)
(different app, but looked same as above before metrics disabled)

## Additional context or links
NOTE: We **do not have** a Prometheus instance configured in our Cloud Foundry foundation, so metrics collection is kinda pointless. I'd like to have a convenient way to disable it.
May this also explain the issue, since the aggregated data never gets fetched / posted to Prometheus?

**Comment by hananiel** [comment]
@christianerbsmehl thanks for the issue. We have recently reworked the metrics implementation. Can you try the latest dev feed nuget for steeltoe and see if you have same issue?

**Comment by TimHess** [comment]
@christianerbsmehl Steeltoe 3.2.0 includes significant changes to metrics and this issue is expected to be resolved. Please try it out when you can and re-open this issue if you are still having problems

**Comment by christianerbsmehl** [comment]
The issue is gone with Steeltoe 3.2.x and .NET 6. Thanks for investigating.
