### ISSUE TITLE
Unable to see MSMQ traces in Zipkin or Jaeger 

### ISSUE THREAD

**Issue by spanhotra** [SteeltoeOSS/Steeltoe#834]
I have implemented the following

Publisher
Service1 -> publishing message -> MSMQ 

Subscriber
MSMQ -> Rabbit Listeners -> Service2

It is working great!!

But I want to see this interaction in the trace on zipkin or Jaeger, I am unable to find the AMQP queries, only Http are there.

**Comment by TimHess** [comment]
Hi @spanhotra, thanks for filing this issue. 

This is ultimately a feature request for [Open Telemetry](https://github.com/open-telemetry/opentelemetry-dotnet) (it would probably ultimately go in [this repo](https://github.com/open-telemetry/opentelemetry-dotnet-contrib) but I can't say for sure where they would want it). There is currently no support for instrumentation of MSMQ interactions, so somebody would need to write that first, and contribute it if they were so inclined. Steeltoe would not be the right place for that code to live, but it would be possible to include that piece (once it exists) in the delegate that configures traces. 

Given that there is nothing to do in Steeltoe, I'm going to close this issue now, but if I've misunderstood or there's more to say it's ok to reopen

**Comment by spanhotra** [comment]
Team,

Open Telemetry has the feature, 
I believe when you are sending/receiving messages to/from MSMQ or Redis [these two only I have tested]
the Activity or Tags are not being created and sent on to Jaeger.

Please add those in the default integration
