### ISSUE TITLE
Unable to see RabbitMQ/Redis traces in Zipkin or Jaeger

### ISSUE THREAD

**Issue by spanhotra** [SteeltoeOSS/Steeltoe#838]
@TimHess ,

Open Telemetry has the feature, 
I believe when you are sending/receiving messages to/from MSMQ or Redis [these two only I have tested]
the Activity or Tags are not being created and sent on to Jaeger.

Please add those in the default integration

_Originally posted by @spanhotra in https://github.com/SteeltoeOSS/Steeltoe/issues/834#issuecomment-1091987840_

**Comment by spanhotra** [comment]
Basically, when I am adding this call. 
`builder.Services.AddDistributedRedisCache(builder.Configuration);`

I am expecting SteelToe to add Redis Instrumentation from within.

**Comment by dtillman** [comment]
@spanhotra 
We think this is a good idea to support and will look at adding support in an upcoming release.
Of course, we're always open to a PR  :-)
Dave

**Comment by spanhotra** [comment]
@dtillman Thank you Dave.
But a quick correction I wanted RabbitMQ, not MSMQ, this is my bad.

Now because RabbitMQ is being quite extensively used in SteelToe, I would expect tracing should work out of the box.
