### ISSUE TITLE
Wavefront Trace exporter: Add support for Red Metrics

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#845]
Currently the steeltoe Wavefront exporter adds spans and traces. To enable the Red metrics dashboard we need the ability to send [Red Metrics](https://docs.wavefront.com/trace_data_details.html#red-metrics).

**Comment by TimHess** [comment]
Wavefront EOL has been announced https://support.broadcom.com/web/ecx/support-content-notification/-/external/content/release-announcements/0/25153
