### ISSUE TITLE
Add PR template to improve GitHub Community Standards

### ISSUE THREAD

**Issue by bart-vmware** [SteeltoeOSS/Steeltoe#851]
The [GitHub Community Standards](https://github.com/SteeltoeOSS/Steeltoe/community) for this repo have all the boxes checked, except for a PR template.

Examples from other projects:
- https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/dotnet/aspnetcore/blob/main/.github/pull_request_template.md
- https://github.com/dotnet/efcore/blob/main/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/fluentassertions/fluentassertions/blob/develop/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/xunit/xunit/blob/main/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/Humanizr/Humanizer/blob/main/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/App-vNext/Polly/blob/master/.github/pull_request_template.md
- https://github.com/icsharpcode/SharpZipLib/blob/master/.github/PULL_REQUEST_TEMPLATE.md

There's some guidance at https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/ and https://www.gitkraken.com/blog/enhancing-pull-request-descriptions-templates, but I think we should keep it as basic as possible. The longer it gets, the more people are going to dislike it (so delete it all upfront or refrain from opening PRs). I've seen that happen with the issue template at a former open-source project I maintained: once we required more info, people started using the chat instead.

In my opinion, the PR template should just be a basic checklist like https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/PULL_REQUEST_TEMPLATE.md. Such a quick reminder helped me on several occasions when I forgot to update the docs.

Feedback welcome!

**Comment by TimHess** [comment]
Adding a PR template is a great idea. I agree that it should be little more than a basic checklist, though I would like to include something that indicates additional content such as a description, summary or general notes could/should be included. Basically something in between what JsonApiDotNetCore and AspNetCore do. 

This seems like a good addition to the checklist from Humanizr:
`If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution`

Is it redundant to have a checkbox for signing CLA? There is a bot that will check for that, but occasionally PRs sit waiting for that step

**Comment by bart-vmware** [comment]
@TimHess  Thanks for the feedback. I'd like the template to be new-user-friendly, while at the same time not getting in the way too much for regular contributors.

So I've created #852. Please let me know what you think.
