### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by ronivars** [SteeltoeOSS/Steeltoe#855]
## Question
I'm storing my variable on git,
When I start my web API it's working fine, and I get the variables.
How do I get the changes by run time and prevent downtime?

## Environment (please complete the following information):
 - .NET Version [e.g. .NET Core 3.1.4, ..NET 6.0] 
 - Steeltoe Version [e.g. 3.1.3]

## Additional context or links

Only when I restart my service does it's getting the changes.
How can I refresh the steeltoeoss/config-server to get the changes to form git files? (Have any interval option to config when running the docker )
How my service can get those changes?
In all video tutorials just mention the refresh option.

**Comment by TimHess** [comment]
Hi @ronivars,

That feature was added in 3.2.0 and is not present in 3.1.4. 3.2.0 has just released, please try again after updating to the latest version.

**Comment by TimHess** [comment]
Please re-open this issue if you still have a problem after upgrading to 3.2.0

**Comment by ronivars** [comment]
Thanks, @TimHess.
Sorry for the delay.
It's working.
