### ISSUE TITLE
Steeltoe Dynamic Logging with appsettings.json configuration not working

### ISSUE THREAD

**Issue by tigerplush** [SteeltoeOSS/Steeltoe#857]
## Describe the bug
Logging to console or to file with serilog configured by appsettings.json is not working after upgrading to .net6.0

## Steps to reproduce 
1. Download sample project from steeltoe initializr with .net6.0 and steeltoe 3.2.0-rc1
2. Add Steeltoe.Extensions.Logging.DynamicSerilogCore package
3. Add
`"Serilog": {
        "Using": [ "Serilog.Sinks.Console" ],
        "MinimumLevel": "Debug",
        "WriteTo": [
            { "Name": "Console" }
        ],
        "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
    }`
to appsettings.json
4. Add `using Steeltoe.Extensions.Logging.DynamicSerilog;` to Program.cs
5. Add `.AddDynamicSerilog()` to program.cs' CreateHostBuilder
6. Refactor WeatherForecastController to use Log.Information instead of _logger.LogInformation

## Expected behavior
Console shows an Info Event with the text 'Getting Forecast'

## Actual behavior
Log.Information will not be logged.

## Environment (please complete the following information):
 - Steeltoe Version 3.2.0-rc1
 - OS: Windows 10
 - .NET Version 6.0

## Screenshots
![2022-05-27_12h22_42](https://user-images.githubusercontent.com/64077786/170681772-038a8ae0-4e74-4ea2-8849-8a5dab30ff69.png)

## Additional Info
This works in another project .net5.0 and steeltoe 3.1.2.
If you reset the sample project to .net5.0, steeltoe 3.1.2 and dynamicSerilogCore Package to 3.1.3 it works too

**Comment by hananiel** [comment]
I am not sure - what else could be different, but I tested with both 3.2.0-rc1 as well as the latest 3.2.0 and it appears to be working fine. I am attaching a tar zip of the solution I used to test (which I created from initializr): 
[SerilogBug.tar.gz](https://github.com/SteeltoeOSS/Steeltoe/files/8789738/SerilogBug.tar.gz) 
And here is the info log 

![serilogbug](https://user-images.githubusercontent.com/887691/170790744-4bdc4705-7104-4b65-adab-48073984c62b.PNG)
 
```
 λ dotnet --version
6.0.203
```

**Comment by tigerplush** [comment]
@hananiel Your WeatherForecastController.cs still uses the injected ILogger, not the Serilog Log.Information();
which I think uses the microsoft logging extension, not the serilog

**Comment by tigerplush** [comment]
Downgrading steeltoe from 3.2.0 to 3.1.3 reenables Serilogs

**Comment by hananiel** [comment]
Although it uses the microsoft logging abstraction, it still uses serilog to use the logging - all the serilog configuration will be respected - along with making it dynamic.

**Comment by TimHess** [comment]
@tigerplush Is the use of Microsoft's logging abstractions suitable, or do you need/expect to work with Serilog directly?

**Comment by tigerplush** [comment]
@TimHess I work with steeltoe 3.1.3 for now as everything works as it's already been implemented, so I'm good

**Comment by selimgul** [comment]
Hi,
I have faced the same problem. My app targets net6.0. When I upgrade Steeltoe package versions from 3.1.3 to 3.2.0, I lost all logs.
