### ISSUE TITLE
Allow for certificate authentication with RabbitMQ

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#859]
## Is your feature request related to a problem? Please describe.
My organisation's rabbitmq servers only allow for connection via certificates but steeltoe only allows username/password.

## Describe the solution you'd like
To be able provide the rabbitmq service connector with the parameters required for a certificate based Rabbitmq connection.

## Describe alternatives you've considered
no alternatives other than using rabbitmq library directly.

## Additional context
Organisation is very secure cautious hence certificate based authentication

**Comment by TimHess** [comment]
Which Steeltoe components are you using? Connectors, Messaging, Stream, all of the above?

**Comment by TimHess** [comment]
Are the certs provided in VCAP_SERVICES? If it isn't a heavy lift we might be able to do this for 3.2.1, but I don't know offhand how much work is required to get certs and plug them into the client

**Comment by thompson-tomo** [comment]
The certs are stored directly on file system & simply a path & password is passed to the connection factory. As an example: [https://weblogs.asp.net/jeffreyabecker/Using-SSL-client-certificates-for-authentication-with-RabbitMQ#:~:text=%20Using%20SSL%20client%20certificates%20for%20authentication%20with,configured%20you%20can%20begin%20configuring%20client...%20More%20](https://weblogs.asp.net/jeffreyabecker/Using-SSL-client-certificates-for-authentication-with-RabbitMQ#:~:text=%20Using%20SSL%20client%20certificates%20for%20authentication%20with,configured%20you%20can%20begin%20configuring%20client...%20More%20 test)

On review of code, I guess all that is needed is an extension to src/Connectors/src/ConnectorBase/RabbitMQ/RabbitMQProviderConnectorFactory.cs to if a cert path is provided via the new property on config, the method is found & then used just like setUri. Same would be for cert password. Note auth mechanism also needs to be set.

**Comment by bart-vmware** [comment]
There's a good chance this works for connectors in Steeltoe v4, which just takes any locally configured [TLS query string parameters](https://www.rabbitmq.com/uri-query-parameters.html#tls) from appsettings.json and passes them to the underlying RabbitMQ client.

To also make this work in CF/TAP, we'd first need a definition of service bindings, so we can map the settings accordingly.
