### ISSUE TITLE
Dynamic Serilog is not working after upgrading to 3.2.0

### ISSUE THREAD

**Issue by spanhotra** [SteeltoeOSS/Steeltoe#860]
## Describe the bug
After I upgraded to DynamicSerilog 3.2.0 from 3.1.3, I noticed, that the application is hung up at app.Run()
Even while debugging, the browser does not open up.

## Steps to reproduce 
1. Upgrade existing application to 3.2.0
2. Start to Debug in VS Code
3. The browser won't open

## Expected behavior
The browser should open

## Environment (please complete the following information):
 - Steeltoe Version 3.2.0
 - Platform: Local
 - OS: Windows
 - .NET Version .NET 6 
 - Any other library versions to note

## Additional context or links

Downgrading to 3.1.3 works but it does not capture Span ID and Trace ID, which is provided in 3.2.0 [Issue](https://github.com/SteeltoeOSS/Steeltoe/issues/835)

Packages used
   ```
 <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="6.0.3" />
    <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.2.0" />
    <PackageReference Include="Steeltoe.Common.Hosting" Version="3.2.0" />
    <PackageReference Include="Steeltoe.Connector.ConnectorCore" Version="3.2.0" />
    <PackageReference Include="Steeltoe.Extensions.Logging.DynamicLogger" Version="3.2.0" />
    <PackageReference Include="Steeltoe.Extensions.Logging.DynamicSerilogCore" Version="3.2.0" />
    <PackageReference Include="Steeltoe.Management.EndpointCore" Version="3.2.0" />
    <PackageReference Include="Steeltoe.Management.TracingCore" Version="3.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />

```

**Comment by hananiel** [comment]
Hi @spanhotra  I tested with 3.2.0 and with 6.0.302 SDK and using this sample: https://github.com/SteeltoeOSS/Samples/tree/main/Management/src/AllActuators

I did see this issue earlier and I am suspecting it is no longer an issue. Can you create a simple reproduction repo  with a global.json that would lock the sdk version?

**Comment by hananiel** [comment]
Closing as not-reproducible for now. Feel free to reopen with a reproduction as either a github repo or a zip file.
