### ISSUE TITLE
Using 3.2.0 Eureka Discovery Client against Eureka Server 1.10.17

### ISSUE THREAD

**Issue by osmedd** [SteeltoeOSS/Steeltoe#865]
## Question
We have been successfully using the Steeltoe Discovery Client through version 2.5.5 against the most recent Netflix Eureka server for several years now.  Upgrading to Steeltoe 3.2.0 we get errors like this when enabling registry fetching:
```
info: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
      Failed to deserialize response
      System.Text.Json.JsonException: '0x1F' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```
We see similar issues ("Fetch disgarded, race condition") as was related in issue #785 and testing against the steeltoeoss eureka server does not show the same issue.

Any recommendations on whether I can tweak some API version setting or something in 3.2.0 to make it talk to a maintained but not newest eureka server?  Unfortunately, I do not have control of the eureka server, so I am assuming we will need to stick with 2.5.5.

It seems that registering a service works fine with 3.2.0, I was planning to test as a last resort if I could disable registry fetching and use a discovery client instance to just do a single lookup. 

Thanks for any enlightenment.

## Environment (please complete the following information):
 - .NET 6
 - Steeltoe Version 3.2.0
 - Eureka server 1.10.17

**Comment by osmedd** [comment]
I have two test projects to simplify this, one (the "server") that is the result of "dotnet new webapi" that I added Steeltoe.Discovery.ClientCore and Steeltoe.Discovery.Eureka, the other (the "lookup" test) has Steeltoe.Discovery.Eureka.

Server registers fine if just eureka:client:shouldRegisterWithEureka is true, with eureka:client:shouldFetchRegistry is false.  Failure if both are true (as noted in my question).

Lookup finds server fine if eureka:client:shouldFetchRegistry is true.  Registering with eureka is false.

The issue seems to be with having registering and fetching running at the same time.

**Comment by ccheetham** [comment]
@osmedd I see you are running Eureka Server 1.10.17.  Can you provide details on how you are running that?  E.g., a 1.10.17 WAR release running in Jetty or Tomcat.

**Comment by osmedd** [comment]
Pardon my rusty Java knowledge but my reading of the project and scripts is that they are running jetty 9.4.39 with the 1.10.17 eureka.war deployed under that.

**Comment by dtillman** [comment]
@osmedd:  
Just following up to let you know I have recreated your issue and trying to determine where we broke this.
3.1.3 seems to work fine .. don't see issue... but 3.2.0 seems to have broken things...

**Comment by TimHess** [comment]
Thanks for reporting this @osmedd and @witskeeper, this does appear to have been a result of compressed content that the Eureka HttpClient was not configured to handle anymore, broken in #778. 

I did notice that in the image referenced by @witskeeper that the Eureka base path is different, so if anybody else wanted to try things out with that image they would need to use  `http://localhost:8761/eureka/v2/` for the Eureka serviceUrl
