### ISSUE TITLE
Cloud Foundry Service Options mapping properties with hyphen

### ISSUE THREAD

**Issue by NotARealBarista** [SteeltoeOSS/Steeltoe#870]
## Question
When attempting to use the Cloud Foundry service mapper, my credentials with hyphens are not being mapped. 
Is there any way to achive that?

Here is my service configuration in appsettings.Development:

```   
"kafka-topic-service": [
        {
          "name": "topic name",
          "credentials": {
            "password": "random",
            "security-protocol": "SASL_SSL",
            "group-id": "all",
            "bootstrap-servers": "some servers",
            "topic": "topic name",
            "sasl-mechanism": "SCRAM-SHA-512",
            "user": "user name",
          },
          "syslog_drain_url": null,
          "volume_mounts": []
        }
      ]
```

The properties with a hyphen (e.g. bootstrap-servers, group-id) are not mapped to my object. I tried different annotations but without success:

```
[DataContract]
public class KafkaTopicOptions : CloudFoundryServicesOptions
{
    [DataMember(Name = "credentials")]
    [JsonProperty("credentials")]
    public KafkaTopicCredentials Credentials { get; set; } = new();
}

[DataContract]
public class KafkaTopicCredentials
{
    [DataMember(Name = "bootstrap-servers")]
    [JsonProperty("bootstrap-servers")]
    public string BootstrapServers { get; set; } = string.Empty;

    [DataMember(Name = "group-id")]
    [JsonProperty("group-id")]
    public string GroupId { get; set; } = string.Empty;

...
}
```

Here is the output:

![output](https://user-images.githubusercontent.com/98881846/172842019-d8927db0-14ba-4c2d-ade4-bd9ea7fc606f.PNG)

Thank you!

## Environment (please complete the following information):
 - .NET Version .NET 6
 - Steeltoe Version 3.2.0

**Comment by dtillman** [comment]
@NotARealBarista   Can you try using ConfigurationKeyNameAttribute on the property to see if that works...

**Comment by dtillman** [comment]
Glad it worked!
