### ISSUE TITLE
RFC: Steeltoe 4.0 support for .NET Core 3.1 - Ends July 15th

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#874]
## Summary
As you may be aware, Microsoft plans to [end support for .NET Core 3.1 on December 13, 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). Development on Steeltoe 4.0 has recently begun and may not ship before this date, so we are considering proactively dropping support for this release. We plan to finalize a decision by July 15th, please share any comments before then.

No changes are being proposed for other Steeltoe release lines at this time.

## Why make this move?
In order to reduce the maintenance burden on contributors, Steeltoe [follows the life cycle of .NET runtimes and Microsoft’s support policies](https://github.com/SteeltoeOSS/Steeltoe/wiki/Steeltoe-Support-Versions#net-runtime-support). Additionally, once Microsoft stops performing security patches for a given runtime, it is in all of our best interest to move to a newer runtime.

## Why now?
Steeltoe 4.0 is a great time to make this move.  We will be performing significant code modernization efforts that will require breaking changes. Changing target runtimes during this release cycle allows us to take advantage of new features and functionality in the runtime right now. Additionally, this change allows users of Steeltoe to continue to develop against the latest and most feature-rich releases from .NET.

## What can you do?
We would love to hear from you!  If you have any questions or concerns about this change, please leave your comments below.  
We welcome you to bring your opinions in issues, contribute code, request features, and join the discussions.  Feel free to bring up any Steeltoe related questions or requests to our [Steeltoe Slack Channel](https://slack.steeltoe.io) or join the [Community Call](https://steeltoe.io/community) (the next opportunity is July 12th).

Thank you,

The Steeltoe Team

**Comment by bart-vmware** [comment]
The article at https://andrewlock.net/stop-lying-about-netstandard-2-support/#when-a-package-lies-about-net-standard-2-0 describes how (and explains why) Microsoft is actively _preventing_ users to use .NET Core 3.1 after support expiry.

Therefore I don't think it makes sense for Steeltoe to support .NET Core 3.1 any longer than Microsoft does.
