### ISSUE TITLE
Steeltoe 3.2.0 breaks Serilog structured logging

### ISSUE THREAD

**Issue by christianerbsmehl** [SteeltoeOSS/Steeltoe#895]
## Describe the bug
After upgrading `Steeltoe.Extensions.Logging.DynamicSerilogBase` from version `3.1.3` to `3.2.0`, structured logging with Serilog is broken, which means that message properties are not extracted from the log message. Additionally, the console output is not colored anymore. 
I created a sample project to demonstrate the issue: https://github.com/christianerbsmehl/steeltoe-serilog

To narrow down the problem, I configured the Serilog file sink with the compact JSON formatter. I found out, that with DynamicSerilogBase 3.2.0 the message template is missing the curly braces around the message properties:

```json
{"@t":"2022-07-27T06:47:51.8714481Z","@mt":"Log should have a value property which value is 'value'.","SourceContext":"TestLogger","RequestId":"0HMJFJFMGJECV:00000001","RequestPath":"/log","ConnectionId":"0HMJFJFMGJECV","Scope":["MyScope"],"Application":"MyApplication"}
```

Using DynamicSerilogBase 3.1.3, output looks like this:

```json
{"@t":"2022-07-27T06:48:30.0176676Z","@mt":"Log should have a {value} property which value is 'value'.","value":"value","SourceContext":"TestLogger","Scope":["MyScope"],"RequestId":"0HMJFJG1S4BTS:00000001","RequestPath":"/log","ConnectionId":"0HMJFJG1S4BTS","Application":"MyApplication"}
```

Note the curly braces around `value` in the message template and the extracted `"value":"value"` property.

## Steps to reproduce 
1. Create a .NET 6 App using `Steeltoe.Extensions.Logging.DynamicSerilogBase 3.2.0` and `Serilog.AspNetCore 6.0.1`
2. Configure Logging using

In `Program.cs`:
```csharp
builder.Logging.AddDynamicSerilog(new LoggerConfiguration().ReadFrom.Configuration(builder.Configuration));
```

In `appSettings.json`:
```json
"Serilog": {
    "IncludeScopes": false,
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Warning",
        "System.Net.Http.HttpClient": "Warning"
      }
    },
    "Properties": {
      "Application": "MyApplication"
    },
    "Enrich": [ "FromLogContext" ],
    "Using": [ "Serilog.Sinks.Console" ],
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Application} {SourceContext}: {Message:lj}{NewLine}{Exception}"
        }
      },
      {
        "Name": "File",
        "Args": {
          "path": "./logs/serilog-sample.json",
          "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"
        }
      }
    ]
  }
```

For details please refer to the sample project I provided above.

## Expected behavior
Message properties should be extracted again and the message template should have curly braces around properties.

## Environment
 - Steeltoe Version: 3.2.0
 - Platform: Cloud Foundry Linux / local Windows development environment
 - OS: Linux/Windows
 - .NET Version: .NET 6

**Comment by hananiel** [comment]
@christianerbsmehl I took a look at this. In 3.2 we added the [feature ](https://github.com/SteeltoeOSS/Steeltoe/issues/835) to add support for IDynamicMessageProcessor which adds things like span and traceID to add context to logs. Unfortunately, I think this broke compatibility with the structured logging. I am looking for a work around.

**Comment by hananiel** [comment]
@christianerbsmehl the short answer to this is that the IDynamicMessageProcessor adds context to logs by calling the formatter ahead of time and then appends data. Whereas the serilog implementation uses the values in TState of Log<TState> to render the the structured logs. So this is obviously a problem - we can pick one or the other - either have structured logs preserved or lose the ability add trace context. I am guessing this cannot be fixed in Steeltoe code base.
