### ISSUE TITLE
Review API Surface area in Steeltoe.Common

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#898]
See https://github.com/SteeltoeOSS/Steeltoe/issues/897#issuecomment-1198088843.

**Comment by bart-vmware** [comment]
Consider adding an extension method to set up `IApplicationInstanceInfo`. See the conversation at https://github.com/SteeltoeOSS/Samples/pull/331#discussion_r1646201252.

**Comment by TimHess** [comment]
We should be able to close #590 during this review
