### ISSUE TITLE
DNS configuration to get list of Eureka Servers

### ISSUE THREAD

**Issue by aivans** [SteeltoeOSS/steeltoe#9]
Configuration of Eureka Servers through DNS is crucial for having a HA setup.
<https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2> describes the use of TXT DNS records. The Client would retrieve the list of available Eureka Servers by doing a dns lookup and parsing the list of servers.
`eureka.shouldUseDns=true`

Do you plan to support this?
Otherwise the project is not really usable in a proper production environment.

**Comment by dtillman** [comment]
In the 2.x release line we added the ability to configure multiple Eureka Server URLs ... see the [docs](https://steeltoe.io/docs/4-discovery/3-netflix-eureka#eureka-settings)..  The Eureka client will then try those URLs in a round robin fashion much like the Nefflix Java client does today.  This should give you some degree of HA with regard to service discovery.

Also, if you need to managed the URLs centrally, you can use the config server to do so.

Dave
