### ISSUE TITLE
Hystrix Dashboard Breaking after update Steeltoe 3.2 version with DotNet6

### ISSUE THREAD

**Issue by deepakapj** [SteeltoeOSS/Steeltoe#960]
## Describe the bug
After updating Steeltoe 3.2 version with DotNet6 sometime Circuit section is not loading in dashboard  and sometimes only few circuits display not all. 

but older version "Steeltoe.CircuitBreaker.Hystrix.MetricsEventsCore" Version="2.1.1" with netstadared2.0 is working fine with same API

## Steps to reproduce 
1. DotNet6 + Steeltoe 3.2
2. Start the Load and Open Hystrix Dashboard 
3. Circuit sections will not display sometimes and sometime few Circuits is showing

## Expected behavior
sometime Circuit section is not loading in dashboard  and sometimes only few circuits display not all. 

## Environment (please complete the following information):
 -  Steeltoe 3.2 version
 - DotNet6
 -

## Screenshots
If applicable, add[Hytrix Issues with Dotnet6.docx](https://github.com/SteeltoeOSS/Steeltoe/files/9213611/Hytrix.Issues.with.Dotnet6.docx)screenshots to help explain your problem.

## Additional context or links
[Hytrix Issues with Dotnet6.docx](https://github.com/SteeltoeOSS/Steeltoe/files/9213612/Hytrix.Issues.with.Dotnet6.docx)

![image](https://user-images.githubusercontent.com/103513170/181622423-183f855a-d251-4ec7-b609-6f3fdf7ad37b.png)

![image](https://user-images.githubusercontent.com/103513170/181622441-3f800e1c-0aea-4302-812b-fa73fca2932c.png)

**Comment by dtillman** [comment]
@deepakapj : 
Thanks ... I'm getting ready to look at this... and was wondering if you had any more detail on your environment/setup ... are you using Docker (.e. g. app running in Docker,   dashboard in Docker, everything running locally????) .  
 
Also, wondering if you have a sample that I should use to start with to repo the problem?

Thanks
Dave

**Comment by TimHess** [comment]
Closing due to lack of response for additional information. If there is still an issue here, please provide more information and ideally a sample app that reproduces the problem.
