### ISSUE TITLE
Access to OpenIdConnectOptions

### ISSUE THREAD

**Issue by pnguyen535** [SteeltoeOSS/steeltoe#97]
Hi

I am using asp.net core, I ran into the issue with ClaimsTransformation as described in the link below. Is there a way to open up the OpenIdConnectOptions oidcOptions

Thank you

https://stackoverflow.com/questions/47929027/getting-access-token-within-claims-transformer-in-asp-net-core

**Comment by TimHess** [comment]
@pnguyen535 does the commit listed above accomplish give you what you're looking for?

**Comment by pnguyen535** [comment]
hi @TimHess ,

I think I made a mistake on requested open up "CloudFoundryOpenIdConnectOptions". What I really want is to after to access OpenIdConnectOption to intercept/load additional claims after the TokenValidated.

Thanks

// the ClaimsIdentity is built off the id_token, but scopes are returned in the access_token. Copy them as claims
            oidcOptions.Events.OnTokenValidated = MapScopesToClaims;
   

        internal static readonly Func<TokenValidatedContext, Task> MapScopesToClaims = (context) =>
        {
            // get claimsId
            ClaimsIdentity claimsId = context.Principal.Identity as ClaimsIdentity;

            // get scopes
            var scopes = context.TokenEndpointResponse.Scope;

            // make sure id has scopes
            foreach (var scope in scopes.Split(' '))
            {
                if (!claimsId.Claims.Any(c => c.Type == "scope" && c.Value.Equals(scope)))
                {
                    claimsId.AddClaim(new Claim("scope", scope));
                }
            }

            return Task.FromResult(0);
        };

**Comment by pnguyen535** [comment]
hi @TimHess 

I looked at the code, I think it should be done similar to  AddCloudFoundryJwtBearer Extension.

.AddCloudFoundryJwtBearer(this AuthenticationBuilder builder, string authenticationScheme, string displayName, IConfiguration config, Action<JwtBearerOptions, IConfiguration> configurer)

Thank you

**Comment by TimHess** [comment]
Does this work for you? https://github.com/SteeltoeOSS/steeltoe/commit/7d7aab838b256a90b563ff5b527b74c9b4a0df44

**Comment by TimHess** [comment]
Included in 2.3.0, which is preparing to ship right now

**Comment by pnguyen535** [comment]
wonderful. Thank you

**Comment by pnguyen535** [comment]
Hi @TimHess

I pulled the latest nuget package 2.3.0 but it doesn't seem to have this update included.

Thanks

**Comment by TimHess** [comment]
What does your package reference look like?

**Comment by pnguyen535** [comment]
Never mind, I got it working 
Thank you 


Sent from Yahoo Mail for iPhone


On Thursday, August 22, 2019, 9:39 AM, Tim Hess <notifications@github.com> wrote:


What does your package reference look like?
