### ISSUE TITLE
StreamHost Implementation of Streams is confusing

### ISSUE THREAD

**Issue by Layla-P** [SteeltoeOSS/Steeltoe#979]
Current implementation of Streams requires user to add the stream-related service to the StreamHost Builder, like so:
```
await StreamHost.CreateDefaultBuilder<ProducerVotingService>(args)
                 .ConfigureWebHostDefaults(webhostBuilder => webhostBuilder.UseStartup<Startup>())
                 .RunConsoleAsync();
```
under the hood this implementation of the generic host builder does the following:
1. It calls the code below
```
 _hostBuilder = hostBuilder.AddSpringBootConfiguration()
                                .ConfigureServices((context, services) => services.AddStreamServices<T>(context.Configuration));
```
2. which does this
```
public static IHostBuilder AddStreamServices<T>(this IHostBuilder builder)
    {
        return builder.AddSpringBootConfiguration()
            .ConfigureServices((context, services) =>
            {
                services.AddStreamServices<T>(context.Configuration);
                services.AddHostedService<StreamLifeCycleService>();
            });
    }
```

IMO, this obfuscates what is actually happening and deviates from how other services are added with Steeltoe.

I think it would be better to primarily document adding Streams like so:
```
await Host.CreateDefaultBuilder(args)
                 .AddStreamServices<ProducerVotingService>()
                 .ConfigureWebHostDefaults(webhostBuilder => webhostBuilder.UseStartup<Startup>())
                 .RunConsoleAsync();
```

Which more easily supports the minimal hosting model like this:

```
using Microsoft.AspNetCore.Mvc;
using Steeltoe.Stream.Extensions;
using VoteProducer;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.AddStreamServices<ProducerVotingService>();
builder.Services.AddSingleton<ProducerVotingService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();


app.MapGet("/weatherforecast", (ProducerVotingService vs, string choice)  =>
{
    var response = vs
                   .Record(new Vote { Choice = choice ?? "default" });
    return response? 200 : 500;
});


app.Run();
```

Then as an alternative implementation for a service that is solely meant to stream, offer the `StreamHost` implementation

**Comment by hananiel** [comment]
When using a web application built with the minimal WebApplicationBuilder extensions, the preferred way at the moment is to use service collection extension methods - as noted. I will update the documentation to clarify, But in the general case of building Steeltoe  stream applications the primary way would be to use the StreamHost extensions. Noted that the current implementation adds functionality using IServiceCollection extension, but using a RabbitMQHost/StreamHost gives a simplified model of adding additional configuration, managing the life cycle and registering call backs - very similar to the default Host implementations, which in the future will reduce the amount of setup that will be required.

**Comment by hananiel** [comment]
The StreamsHost is not the same as the Generic host, it has additional lifecycle elements - which is the purpose of having a custom host. So no your sample does not do the same thing. See here: https://github.com/SteeltoeOSS/Steeltoe/blob/095967c0f58afa27d3e5968dc2af5548a04f9dd6/src/Stream/src/Stream/StreamHost/StreamHost.cs#L40 So your sample will not have the same functionality. So at the moment, there is no way to use WebApplication Builder - even though it may work, it is not recommended - we will have to build this into the webapplication builder separately.  I created this ticket to track this: https://github.com/SteeltoeOSS/Steeltoe/issues/1014

**Comment by hananiel** [comment]
resolved by https://github.com/SteeltoeOSS/Documentation/pull/283
