### ISSUE TITLE
Repackage Steeltoe.Commons.Utils into discrete packages

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Steeltoe#988]
## Is your feature request related to a problem? Please describe.
Using `Steeltoe.Commons.Utils` is an all-or-nothing proposition: you get all the utilities or you get none.

## Describe the solution you'd like
Split the package into discrete packages, e.g. `Steeltoe.Commons.Utils.IO`

**Comment by TimHess** [comment]
This namespace will probably be made internal or removed as it is currently only used in Steeltoe tests
